#!/usr/bin/env python3
"""Turn protocol/fixtures/*.json into C test-vector headers.

Run by the host-test and ztest builds (CMake custom command) whenever a
fixture, include/ctag/proto_msgs.h or this script changes, so the C vectors
can never go stale. Standard library only.

Usage: gen_vectors.py <output directory> [--root <repository root>]
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]

# Value kinds of serial CBOR keys that JSON cannot express (companion
# protocol/cbor_msgs.py KEYS): byte strings are hex in the fixtures.
CBOR_BSTR = {"uuid", "fontpack_id", "layout", "key", "digest", "data", "uuid_filter"}
CBOR_INT = {"rssi"}


class Header:
    """One generated header: byte arrays first, then declarations."""

    def __init__(self, name: str, includes: tuple[str, ...] = ()) -> None:
        self.name = name
        self.includes = ("stdbool.h", "stddef.h", "stdint.h", *includes)
        self.blobs: list[str] = []
        self.body: list[str] = []
        self._count = 0

    def blob(self, data: bytes) -> str:
        """Emit a byte array (never empty: C99 has no zero-length arrays)."""
        ident = f"{self.name}_b{self._count}"
        self._count += 1
        values = data if data else b"\0"
        lines = [", ".join(f"0x{b:02x}" for b in values[i : i + 12]) for i in range(0, len(values), 12)]
        self.blobs.append(f"static const uint8_t {ident}[] = {{\n\t" + ",\n\t".join(lines) + "\n};")
        return ident

    def hexblob(self, text: str) -> tuple[str, int]:
        data = bytes.fromhex(text)
        return self.blob(data), len(data)

    def ident(self) -> str:
        ident = f"{self.name}_x{self._count}"
        self._count += 1
        return ident

    def write(self, out: Path) -> None:
        guard = f"{self.name.upper()}_H_"
        text = [
            "/* Generated by tests/host/gen_vectors.py from protocol/fixtures. Do not edit. */",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            *(f"#include <{inc}>" for inc in self.includes),
            "",
            *self.blobs,
            "",
            *self.body,
            "",
            f"#endif /* {guard} */",
            "",
        ]
        (out / f"{self.name}.h").write_text("\n".join(text), encoding="utf-8", newline="\n")


def c_str(text: str) -> str:
    return json.dumps(text, ensure_ascii=True)


def status(name: str | None) -> str:
    return "-1" if name is None else f"CTAG_STATUS_{name}"


def load(root: Path, name: str) -> Any:
    return json.loads((root / "protocol" / "fixtures" / name).read_text(encoding="utf-8"))


def gen_crc32(root: Path) -> Header:
    h = Header("v_crc32")
    rows = []
    for v in load(root, "crc32.json")["vectors"]:
        ident, n = h.hexblob(v["data"])
        rows.append(f"\t{{{c_str(v['name'])}, {ident}, {n}u, 0x{v['crc32']:08x}u}},")
    h.body += [
        "struct v_crc32 {\n\tconst char *name;\n\tconst uint8_t *data;\n\tsize_t len;\n\tuint32_t crc;\n};",
        "static const struct v_crc32 v_crc32[] = {", *rows, "};",
    ]
    return h


def gen_cobs(root: Path) -> Header:
    fx = load(root, "cobs.json")
    h = Header("v_cobs")
    h.body.append("struct v_cobs {\n\tconst char *name;\n\tconst uint8_t *dec;\n\tsize_t dec_len;\n"
                  "\tconst uint8_t *enc;\n\tsize_t enc_len;\n};")
    for key, var in (("vectors", "v_cobs"), ("decode_only", "v_cobs_decode_only")):
        rows = []
        for v in fx[key]:
            dec, dn = h.hexblob(v["decoded"])
            enc, en = h.hexblob(v["encoded"])
            rows.append(f"\t{{{c_str(v['name'])}, {dec}, {dn}u, {enc}, {en}u}},")
        h.body += [f"static const struct v_cobs {var}[] = {{", *rows, "};"]
    rows = []
    for v in fx["decode_errors"]:
        enc, en = h.hexblob(v["encoded"])
        rows.append(f"\t{{{c_str(v['name'])}, NULL, 0u, {enc}, {en}u}},")
    h.body += ["static const struct v_cobs v_cobs_errors[] = {", *rows, "};"]
    h.body.append("struct v_cobs_stream {\n\tconst char *name;\n\tconst uint8_t *in;\n\tsize_t in_len;\n"
                  "\tconst uint8_t *const *frames;\n\tconst size_t *frame_lens;\n\tsize_t n_frames;\n"
                  "\tuint32_t errors;\n\tuint32_t oversize;\n};")
    rows = []
    for v in fx["stream"]:
        inp, n = h.hexblob(v["input"])
        frames = [h.hexblob(f) for f in v["frames"]]
        fid, lid = h.ident(), h.ident()
        h.body.append(f"static const uint8_t *const {fid}[] = {{{', '.join(f for f, _ in frames)}}};")
        h.body.append(f"static const size_t {lid}[] = {{{', '.join(f'{n}u' for _, n in frames)}}};")
        rows.append(f"\t{{{c_str(v['name'])}, {inp}, {n}u, {fid}, {lid}, {len(frames)}u, "
                    f"{v['errors']}u, {v['oversize']}u}},")
    h.body += ["static const struct v_cobs_stream v_cobs_stream[] = {", *rows, "};"]
    return h


def gen_serial(root: Path) -> Header:
    fx = load(root, "serial_frames.json")
    h = Header("v_serial")
    h.body.append("struct v_serial_frame {\n\tconst char *name;\n\tuint8_t type;\n\tuint16_t request_id;\n"
                  "\tuint8_t flags;\n\tuint8_t credits;\n\tconst uint8_t *payload;\n\tsize_t payload_len;\n"
                  "\tconst uint8_t *decoded;\n\tsize_t decoded_len;\n\tconst uint8_t *wire;\n"
                  "\tsize_t wire_len;\n};")
    rows = []
    for v in fx["frames"]:
        p, pn = h.hexblob(v["payload"])
        d, dn = h.hexblob(v["decoded"])
        w, wn = h.hexblob(v["wire"])
        rows.append(f"\t{{{c_str(v['name'])}, {v['type']}u, {v['request_id']}u, {v['flags']}u, "
                    f"{v['credits']}u, {p}, {pn}u, {d}, {dn}u, {w}, {wn}u}},")
    h.body += ["static const struct v_serial_frame v_serial_frames[] = {", *rows, "};"]
    h.body.append("struct v_serial_invalid {\n\tconst char *name;\n\tconst uint8_t *decoded;\n"
                  "\tsize_t len;\n\tint check; /* enum ctag_serial_check */\n};")
    checks = {"len": "CTAG_SERIAL_CHECK_LEN", "crc": "CTAG_SERIAL_CHECK_CRC",
              "version": "CTAG_SERIAL_CHECK_VERSION"}
    rows = []
    for v in fx["invalid"]:
        d, dn = h.hexblob(v["decoded"])
        rows.append(f"\t{{{c_str(v['name'])}, {d}, {dn}u, {checks[v['error']]}}},")
    h.body += ["static const struct v_serial_invalid v_serial_invalid[] = {", *rows, "};"]
    return h


def _cbor_fields(h: Header, fields: dict[str, Any]) -> tuple[str, int]:
    """Emit a ctag_cbor_field array for a fixture map; returns (ident, count)."""
    rows = []
    for name, value in fields.items():
        key = f"CTAG_CBOR_KEY_{name.upper()}"
        if name in CBOR_BSTR:
            data, n = h.hexblob(value)
            rows.append(f"\t{{.key = {key}, .kind = CTAG_CBOR_BSTR, .v.str = {{{data}, {n}u}}}},")
        elif isinstance(value, bool):
            rows.append(f"\t{{.key = {key}, .kind = CTAG_CBOR_BOOL, .v.b = {str(value).lower()}}},")
        elif isinstance(value, int) and name in CBOR_INT:
            rows.append(f"\t{{.key = {key}, .kind = CTAG_CBOR_INT, .v.i = {value}}},")
        elif isinstance(value, int):
            rows.append(f"\t{{.key = {key}, .kind = CTAG_CBOR_UINT, .v.u = {value}u}},")
        elif isinstance(value, str):
            rows.append(f"\t{{.key = {key}, .kind = CTAG_CBOR_TSTR, "
                        f".v.str = {{(const uint8_t *){c_str(value)}, {len(value.encode())}u}}}},")
        elif name == "counters":
            ident = h.ident()
            items = ", ".join(f"CTAG_CBOR_COUNTER({c_str(k)}, {v}u)" for k, v in value.items())
            h.body.append(f"static const struct ctag_cbor_counter {ident}[] = {{{items}}};")
            rows.append(f"\t{{.key = {key}, .kind = CTAG_CBOR_COUNTERS, "
                        f".v.counters = {{{ident}, {len(value)}u}}}},")
        elif isinstance(value, dict):
            ident, n = _cbor_fields(h, value)
            rows.append(f"\t{{.key = {key}, .kind = CTAG_CBOR_MAP, .v.map = {{{ident}, {n}u}}}},")
        else:
            maps = [_cbor_fields(h, item) for item in value]
            ident = h.ident()
            items = ", ".join(f"{{{i}, {n}u}}" for i, n in maps)
            h.body.append(f"static const struct ctag_cbor_map {ident}[] = {{{items}}};")
            rows.append(f"\t{{.key = {key}, .kind = CTAG_CBOR_MAPS, .v.maps = {{{ident}, {len(maps)}u}}}},")
    ident = h.ident()
    h.body += [f"static const struct ctag_cbor_field {ident}[] = {{", *rows, "};"]
    return ident, len(rows)


def gen_serial_cbor(root: Path) -> Header:
    h = Header("v_serial_cbor", ("ctag/ctag_cbor.h",))
    rows = []
    for v in load(root, "serial_frames.json")["frames"]:
        p, pn = h.hexblob(v["payload"])
        fields, n = _cbor_fields(h, v["fields"]) if v["fields"] else ("NULL", 0)
        rows.append(f"\t{{{c_str(v['name'])}, {fields}, {n}u, {p}, {pn}u}},")
    h.body += [
        "struct v_cbor_frame {\n\tconst char *name;\n\tconst struct ctag_cbor_field *fields;\n"
        "\tsize_t count;\n\tconst uint8_t *payload;\n\tsize_t len;\n};",
        "static const struct v_cbor_frame v_cbor_frames[] = {", *rows, "};",
    ]
    return h


def _struct_fields(msgs_h: str, struct: str) -> dict[str, str]:
    """C field name -> declaration of `struct <struct>` in proto_msgs.h."""
    match = re.search(rf"struct {struct} {{\n(.*?)\n}};", msgs_h, re.S)
    if match is None:
        return {}
    fields = {}
    for line in match.group(1).splitlines():
        decl = line.split("/*")[0].strip().rstrip(";")
        name = re.split(r"[\s*]", decl)[-1].split("[")[0]
        fields[name] = decl
    return fields


def gen_mesh(root: Path) -> Header:
    """Emits v_mesh_run(): generated checks over the generated codecs."""
    fx = load(root, "mesh_msgs.json")
    msgs_h = (root / "include" / "ctag" / "proto_msgs.h").read_text(encoding="utf-8")
    h = Header("v_mesh", ("string.h", "ctag/proto_msgs.h"))
    code = ["static void v_mesh_run(void)", "{"]
    for v in fx["vectors"]:
        snake = v["name"].lower()
        struct = f"ctag_mesh_{snake}"
        params, n = h.hexblob(v["params"])
        access, an = h.hexblob(v["access"])
        up = v["name"]
        assert an == n + 3, v["name"]
        code += [
            f"\t{{ /* {up} */",
            f"\t\tCHECK(CTAG_MESH_OPCODE_{up} == 0x{v['opcode']:06x}u);",
            f"\t\tCHECK({access}[0] == (uint8_t)(CTAG_MESH_OPCODE_{up} >> 16));",
            f"\t\tCHECK({access}[1] == (uint8_t)CTAG_MESH_OPCODE_{up});",
            f"\t\tCHECK({access}[2] == (uint8_t)(CTAG_MESH_OPCODE_{up} >> 8));",
            f"\t\tCHECK(memcmp(&{access}[3], {params}, {n}u) == 0);",
        ]
        decls = _struct_fields(msgs_h, struct)
        if not decls:
            code += [f"\t\tCHECK(CTAG_MESH_{up}_LEN == {n}u);", "\t}"]
            continue
        code += [
            f"\t\tstruct {struct} m;",
            f"\t\tuint8_t out[{n}u + 1u];",
            "",
            f"\t\tCHECK({struct}_unpack(&m, {params}, {n}u) == 0);",
        ]
        for name, value in v["fields"].items():
            decl = decls[name]
            if isinstance(value, str):
                data, dn = h.hexblob(value)
                if decl.startswith("const uint8_t *"):
                    code.append(f"\t\tCHECK(m.{name}_len == {dn}u);")
                code.append(f"\t\tCHECK(memcmp(m.{name}, {data}, {dn}u) == 0);")
            else:
                code.append(f"\t\tCHECK((int64_t)m.{name} == (int64_t){value}LL);")
        code += [
            f"\t\tCHECK({struct}_pack(&m, out, sizeof(out)) == (int){n});",
            f"\t\tCHECK(memcmp(out, {params}, {n}u) == 0);",
            f"\t\tCHECK({struct}_pack(&m, out, {n}u - 1u) == -EMSGSIZE);",
            "\t}",
        ]
    for v in fx["errors"]:
        up = next(x["name"] for x in fx["vectors"] if x["op"] == v["op"])
        struct = f"ctag_mesh_{up.lower()}"
        params, n = h.hexblob(v["params"])
        err = f"-{v['error']}"
        if _struct_fields(msgs_h, struct):
            code += [
                f"\t{{ /* {v['name']} */",
                f"\t\tstruct {struct} m;",
                "",
                f"\t\tCHECK({struct}_unpack(&m, {params}, {n}u) == {err});",
                "\t}",
            ]
        else:
            # A message without fields has only its _LEN macro (0): longer is -EMSGSIZE.
            code.append(f"\tCHECK({err} == -EMSGSIZE && {n}u > CTAG_MESH_{up}_LEN);")
    code.append("}")
    h.body += code
    return h


def gen_layouts(root: Path) -> Header:
    fx = load(root, "layouts.json")
    h = Header("v_layouts", ("ctag/proto_ids.h",))
    h.body.append("struct v_layout {\n\tconst char *name;\n\tconst uint8_t *data;\n\tsize_t len;\n"
                  "\tconst uint8_t *digest;\n\tint status;\n};")
    rows = []
    names = []
    for v in fx["valid"]:
        d, n = h.hexblob(v["hex"])
        dig, _ = h.hexblob(v["digest"])
        rows.append(f"\t{{{c_str(v['name'])}, {d}, {n}u, {dig}, CTAG_STATUS_OK}},")
        names.append(v["name"])
    h.body += ["static const struct v_layout v_layouts_valid[] = {", *rows, "};"]
    rows = []
    for v in fx["invalid"]:
        d, n = h.hexblob(v["hex"])
        rows.append(f"\t{{{c_str(v['name'])}, {d}, {n}u, NULL, {status(v['status_name'])}}},")
    h.body += ["static const struct v_layout v_layouts_invalid[] = {", *rows, "};"]
    h.body.append("struct v_panel_check {\n\tsize_t layout;\n\tuint16_t width;\n\tuint16_t height;\n"
                  "\tint status;\n};")
    rows = [f"\t{{{names.index(v['layout'])}u, {v['native_width']}u, {v['native_height']}u, "
            f"{status(v['status_name'])}}}," for v in fx["panel_checks"]]
    h.body += ["static const struct v_panel_check v_panel_checks[] = {", *rows, "};"]
    return h


def gen_render(root: Path) -> Header:
    fx = load(root, "render.json")
    h = Header("v_render")
    h.body.append(f"#define V_RENDER_STRIP_ROWS {fx['strip_rows']}u")
    h.body.append("struct v_render {\n\tconst char *name;\n\tuint16_t width;\n\tuint16_t height;\n"
                  "\tuint8_t planes;\n\tuint8_t plane_flags;\n\tconst uint8_t *layout;\n\tsize_t len;\n"
                  "\tsize_t plane_len;\n\tconst uint8_t *plane_sha256[2];\n\tconst uint8_t *frame_digest;\n"
                  "\tconst uint8_t *plane_bytes[2]; /* NULL when the fixture has no planes_hex */\n};")
    rows = []
    for v in fx["scenarios"]:
        p = v["panel"]
        lay, n = h.hexblob(v["layout_hex"])
        shas = [h.hexblob(s)[0] for s in v["planes_sha256"]] + ["NULL"] * (2 - len(v["planes_sha256"]))
        dig, _ = h.hexblob(v["frame_digest"])
        planes = [h.hexblob(x)[0] for x in v.get("planes_hex", [])]
        planes += ["NULL"] * (2 - len(planes))
        rows.append(f"\t{{{c_str(v['name'])}, {p['width']}u, {p['height']}u, {p['planes']}u, "
                    f"{p['plane_flags']}u, {lay}, {n}u, {v['plane_len']}u, {{{shas[0]}, {shas[1]}}}, {dig}, "
                    f"{{{planes[0]}, {planes[1]}}}}},")
    h.body += ["static const struct v_render v_render[] = {", *rows, "};"]
    return h


def gen_qr(root: Path) -> Header:
    h = Header("v_qr")
    h.body.append("struct v_qr {\n\tconst char *text;\n\tuint8_t ecc;\n\tuint8_t version;\n\tuint8_t size;\n"
                  "\tconst uint8_t *rows; /* size rows of (size + 7) / 8 bytes, MSB first */\n};")
    rows = []
    for v in load(root, "qr.json")["vectors"]:
        data, _ = h.hexblob("".join(v["rows"]))
        rows.append(f"\t{{{c_str(v['text'])}, {v['ecc']}u, {v['version']}u, {v['size']}u, {data}}},")
    h.body += ["static const struct v_qr v_qr[] = {", *rows, "};"]
    return h


def gen_fontpack(root: Path) -> Header:
    fx = load(root, "fontpack.json")
    h = Header("v_fontpack", ("ctag/proto_ids.h",))
    pack = (root / "protocol" / "fixtures" / fx["file"]).read_bytes()
    hd = fx["header"]
    ident = h.blob(pack)
    pack_id, _ = h.hexblob(hd["pack_id"])
    content, _ = h.hexblob(hd["content_hash"])
    h.body += [
        f"#define V_FONTPACK_DATA {ident}",
        f"#define V_FONTPACK_LEN {len(pack)}u",
        f"#define V_FONTPACK_TOTAL {hd['total_size']}u",
        f"#define V_FONTPACK_STRIKE_COUNT {hd['strike_count']}u",
        f"#define V_FONTPACK_STRIKE_OFF {hd['strike_table_offset']}u",
        f"#define V_FONTPACK_BITMAP_OFF {hd['bitmap_area_offset']}u",
        f"#define V_FONTPACK_BITMAP_SIZE {hd['bitmap_area_size']}u",
        f"#define V_FONTPACK_PACK_ID {pack_id}",
        f"#define V_FONTPACK_CONTENT_HASH {content}",
    ]
    h.body.append("struct v_strike {\n\tuint16_t face;\n\tuint8_t size_px;\n\tuint32_t glyph_count;\n"
                  "\tuint32_t index_off;\n};")
    rows = [f"\t{{{s['face_id']}u, {s['size_px']}u, {s['glyph_count']}u, {s['index_off']}u}},"
            for s in fx["strikes"]]
    h.body += ["static const struct v_strike v_fontpack_strikes[] = {", *rows, "};"]
    h.body.append("struct v_glyph {\n\tuint16_t face;\n\tuint8_t size_px;\n\tuint16_t glyph_id;\n"
                  "\tuint32_t bitmap_off;\n\tuint8_t width;\n\tuint8_t height;\n\tint8_t bearing_x;\n"
                  "\tint8_t bearing_y;\n\tuint16_t advance;\n\tconst uint8_t *bitmap;\n\tsize_t bitmap_len;\n};")
    rows = []
    for g in fx["glyphs"]:
        bm, n = h.hexblob(g["bitmap"])
        rows.append(f"\t{{{g['face']}u, {g['size_px']}u, {g['glyph_id']}u, {g['bitmap_off']}u, {g['width']}u, "
                    f"{g['height']}u, {g['bearing_x']}, {g['bearing_y']}, {g['advance']}u, {bm}, {n}u}},")
    h.body += ["static const struct v_glyph v_fontpack_glyphs[] = {", *rows, "};"]
    h.body.append("struct v_corruption {\n\tconst char *name;\n\tsize_t offset;\n\tint boot_status;\n"
                  "\tint install_status;\n};")
    rows = [f"\t{{{c_str(c['name'])}, {c['offset']}u, {status(c['boot_status'])}, "
            f"{status(c['install_status'])}}}," for c in fx["corruptions"]]
    h.body += ["static const struct v_corruption v_fontpack_corruptions[] = {", *rows, "};"]
    return h


def gen_fragments(root: Path) -> Header:
    fx = load(root, "fragments.json")
    h = Header("v_fragments")
    h.body.append(f"#define V_FRAG_PAYLOAD {fx['fragment_payload']}u")
    h.body.append("struct v_frag {\n\tconst char *name;\n\tuint16_t max_message;\n\tuint8_t seq_start;\n"
                  "\tuint8_t seq_next;\n\tconst uint8_t *msg;\n\tsize_t msg_len;\n"
                  "\tconst uint8_t *const *frags;\n\tconst size_t *frag_lens;\n\tsize_t n_frags;\n"
                  "\tsize_t error_at;\n};")

    def frags(values: list[str]) -> tuple[str, str]:
        blobs = [h.hexblob(f) for f in values]
        fid, lid = h.ident(), h.ident()
        h.body.append(f"static const uint8_t *const {fid}[] = {{{', '.join(b for b, _ in blobs)}}};")
        h.body.append(f"static const size_t {lid}[] = {{{', '.join(f'{n}u' for _, n in blobs)}}};")
        return fid, lid

    rows = []
    for v in fx["vectors"]:
        msg, n = h.hexblob(v["message"])
        fid, lid = frags(v["fragments"])
        rows.append(f"\t{{{c_str(v['name'])}, {v['max_message']}u, {v['seq_start']}u, {v['seq_next']}u, "
                    f"{msg}, {n}u, {fid}, {lid}, {len(v['fragments'])}u, 0u}},")
    h.body += ["static const struct v_frag v_frag[] = {", *rows, "};"]
    rows = []
    for v in fx["errors"]:
        fid, lid = frags(v["fragments"])
        rows.append(f"\t{{{c_str(v['name'])}, {v['max_message']}u, 0u, 0u, NULL, 0u, {fid}, {lid}, "
                    f"{len(v['fragments'])}u, {v['error_at']}u}},")
    h.body += ["static const struct v_frag v_frag_errors[] = {", *rows, "};"]
    return h


def gen_tag_txn(root: Path) -> Header:
    fx = load(root, "tag_txn.json")
    h = Header("v_tag_txn", ("ctag/proto_ids.h",))
    h.body += [
        f"#define V_TXN_PANEL_PLANES {fx['panel']['planes']}u",
        f"#define V_TXN_PANEL_PLANE_LEN {fx['panel']['plane_len']}u",
        "struct v_txn_rec {\n\tbool present;\n\tuint32_t tag_id;\n\tuint32_t epoch;\n\tuint32_t revision;\n"
        "\tuint64_t update_id;\n\tconst uint8_t *digest;\n\tint status;\n\tint state;\n};",
    ]

    def rec(r: dict[str, Any] | None) -> str:
        if r is None:
            return "{false, 0u, 0u, 0u, 0u, NULL, 0, 0}"
        dig, _ = h.hexblob(r["digest"])
        state = {"DISPLAYED": 0, "REFRESH_INTENT": 1}[r["state"]]
        return (f"{{true, {r['tag_id']}u, {r['epoch']}u, {r['revision']}u, {r['update_id']}u, {dig}, "
                f"{status(r['status_name'])}, {state}}}")

    h.body.append("struct v_txn_frame_begin {\n\tconst char *name;\n\tstruct v_txn_rec stored;\n"
                  "\tuint32_t epoch;\n\tuint32_t revision;\n\tconst uint8_t *digest;\n\tuint8_t planes;\n"
                  "\tuint16_t plane_len;\n\tbool accept;\n\tbool duplicate;\n\tint status;\n};")
    rows = []
    for v in fx["frame_begin"]:
        f, e = v["frame"], v["expect"]
        dig, _ = h.hexblob(f["digest"])
        rows.append(f"\t{{{c_str(v['name'])}, {rec(v['stored'])}, {f['epoch']}u, {f['revision']}u, {dig}, "
                    f"{f['planes']}u, {f['plane_len']}u, {str(e['accept']).lower()}, "
                    f"{str(e['duplicate']).lower()}, {status(e['status_name'])}}},")
    h.body += ["static const struct v_txn_frame_begin v_txn_frame_begin[] = {", *rows, "};"]
    h.body.append("struct v_txn_boot {\n\tconst char *name;\n\tstruct v_txn_rec stored;\n"
                  "\tstruct v_txn_rec expect;\n\tbool persist;\n\tbool flag;\n};")
    rows = []
    for v in fx["boot"]:
        e = v["expect"]
        rows.append(f"\t{{{c_str(v['name'])}, {rec(v['stored'])}, {rec(e['record'])}, "
                    f"{str(e['persist']).lower()}, {str(e['challenge_flag_bit0']).lower()}}},")
    h.body += ["static const struct v_txn_boot v_txn_boot[] = {", *rows, "};"]
    return h


def gen_enrollment(root: Path) -> Header:
    fx = load(root, "enrollment.json")
    h = Header("v_enrollment", ("ctag/proto_ids.h",))
    f = fx["fields"]
    blob, n = h.hexblob(fx["blob"])
    secret, _ = h.hexblob(f["secret"])
    h.body += [
        f"#define V_ENROLL_BLOB {blob}",
        f"#define V_ENROLL_BLOB_LEN {n}u",
        f"#define V_ENROLL_MAGIC 0x{f['magic']:08x}u",
        f"#define V_ENROLL_VERSION {f['version']}u",
        f"#define V_ENROLL_BOARD {f['board']}u",
        f"#define V_ENROLL_PANEL {f['panel']}u",
        f"#define V_ENROLL_FLAGS {f['flags']}u",
        f"#define V_ENROLL_TAG_ID {f['tag_id']}u",
        f"#define V_ENROLL_SECRET {secret}",
        f"#define V_ENROLL_CRC32 0x{f['crc32']:08x}u",
        "struct v_enroll_invalid {\n\tconst char *name;\n\tconst uint8_t *blob;\n\tsize_t len;\n\tint status;\n};",
    ]
    rows = []
    for v in fx["invalid"]:
        b, bn = h.hexblob(v["blob"])
        rows.append(f"\t{{{c_str(v['name'])}, {b}, {bn}u, {status(v['status_name'])}}},")
    h.body += ["static const struct v_enroll_invalid v_enroll_invalid[] = {", *rows, "};"]
    return h


def gen_session(root: Path) -> Header:
    fx = load(root, "session.json")
    h = Header("v_session", ("ctag/proto_ids.h",))
    for key in ("tag_secret", "nonce_b", "nonce_t", "caps", "hello", "challenge", "k_epoch", "th", "mac_b",
                "mac_t", "auth", "auth_ok", "k_b2t", "k_t2b"):
        ident, n = h.hexblob(fx[key])
        h.body += [f"#define V_SESSION_{key.upper()} {ident}", f"#define V_SESSION_{key.upper()}_LEN {n}u"]
    relayed = fx["caps_relayed"]
    for key in ("caps", "th", "auth"):
        ident, n = h.hexblob(relayed[key])
        h.body += [f"#define V_SESSION_RELAYED_{key.upper()} {ident}",
                   f"#define V_SESSION_RELAYED_{key.upper()}_LEN {n}u"]
    assert relayed["status_name"] == "AUTH_FAILED"
    stale = fx["stale_epoch"]
    ident, n = h.hexblob(stale["error"])
    h.body += [f"#define V_SESSION_STALE_STORED_EPOCH {stale['stored_epoch']}u",
               f"#define V_SESSION_STALE_ERROR {ident}", f"#define V_SESSION_STALE_ERROR_LEN {n}u",
               f"#define V_SESSION_STALE_STATUS {status(stale['status_name'])}"]
    nxt, _ = h.hexblob(fx["k_epoch_next"]["k_epoch"])
    bad, _ = h.hexblob(fx["bad_mac_b"]["mac_b"])
    ex = fx["nonce_example"]
    nonce, _ = h.hexblob(ex["nonce"])
    h.body += [
        f"#define V_SESSION_TAG_ID {fx['tag_id']}u",
        f"#define V_SESSION_EPOCH {fx['epoch']}u",
        f"#define V_SESSION_NEXT_EPOCH {fx['k_epoch_next']['epoch']}u",
        f"#define V_SESSION_K_EPOCH_NEXT {nxt}",
        f"#define V_SESSION_BAD_MAC_B {bad}",
        f"#define V_SESSION_NONCE_DIR CTAG_REC_DIR_{ex['direction']}",
        f"#define V_SESSION_NONCE_COUNTER {ex['counter']}u",
        f"#define V_SESSION_NONCE {nonce}",
        "struct v_record {\n\tconst char *name;\n\tint dir; /* enum ctag_rec_dir */\n\tuint32_t counter;\n"
        "\tuint8_t type;\n\tconst uint8_t *plaintext;\n\tsize_t pt_len;\n\tconst uint8_t *record;\n"
        "\tsize_t len;\n};",
    ]
    rows = []
    for r in fx["records"]:
        pt, pn = h.hexblob(r["plaintext"])
        rc, rn = h.hexblob(r["record"])
        rows.append(f"\t{{{c_str(r['type_name'])}, CTAG_REC_DIR_{r['direction']}, {r['counter']}u, "
                    f"{r['type']}u, {pt}, {pn}u, {rc}, {rn}u}},")
    h.body += ["static const struct v_record v_session_records[] = {", *rows, "};"]
    rows = []
    for r in fx["tampered"]:
        rc, rn = h.hexblob(r["record"])
        rows.append(f"\t{{{c_str(r['name'])}, CTAG_REC_DIR_{r['direction']}, {r['expected_counter']}u, 0u, "
                    f"NULL, 0u, {rc}, {rn}u}},")
    h.body += ["static const struct v_record v_session_tampered[] = {", *rows, "};"]
    return h


GENERATORS = (gen_crc32, gen_cobs, gen_serial, gen_serial_cbor, gen_mesh, gen_layouts, gen_render, gen_qr,
              gen_fontpack, gen_fragments, gen_tag_txn, gen_enrollment, gen_session)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("out", type=Path)
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    for gen in GENERATORS:
        gen(args.root).write(args.out)


if __name__ == "__main__":
    main()
