"""Protocol identifiers and constants (mirror of include/ctag/proto_ids.h).

DO NOT EDIT: generated by tools/codegen.py from protocol/spec.yaml.
spec sha256: 729103a9c513c5cf7b1375863b9aa16dc9ab6358ecc6f294edd8c30edee628ce
"""

from __future__ import annotations

import uuid
from enum import IntEnum, IntFlag
from typing import Final

SPEC_VERSION: Final = 2
SPEC_SHA256: Final = "729103a9c513c5cf7b1375863b9aa16dc9ab6358ecc6f294edd8c30edee628ce"

# ---- Constants (spec: constants) ----
PROTO_VERSION: Final = 1  # Version carried by serial frames, mesh CAPS, GATT HELLO and layout headers
SERIAL_MAX_FRAME: Final = 4096  # Maximum DECODED serial frame (header + payload + CRC)
SERIAL_HEADER_LEN: Final = 8  # Serial frame header length
SERIAL_CRC_LEN: Final = 4  # CRC-32/IEEE trailer length
SERIAL_MAX_PAYLOAD: Final = 4084  # SERIAL_MAX_FRAME - header - CRC
SERIAL_MAX_ENCODED: Final = 4128  # Worst-case COBS-encoded frame incl. 0x00 delimiter (4096 + ceil(4096/254) + 1, rounded up)
SERIAL_DEFAULT_CREDITS: Final = 4  # Frames each side may send before the first credit grant
SERIAL_EVENT_RETAIN: Final = 16  # Unacknowledged gateway events (EVT_RESULT etc.) kept for re-send
SERIAL_IDEMPOTENCY_SLOTS: Final = 32  # Recent op_id -> status entries the gateway remembers
MESH_COMPANY_ID: Final = 0xFFFF  # Bluetooth SIG company id used by vendor models. 0xFFFF = SIG test/unassigned value; production needs an assigned id
MESH_MAX_VENDOR_PARAMS: Final = 160  # Maximum vendor-model message parameter bytes
MESH_MIN_SEG: Final = 16  # Minimum CONFIG_BT_MESH_TX_SEG_MAX / RX_SEG_MAX
MESH_DEFAULT_TTL: Final = 5  # Default TTL for gateway<->bridge messages
MESH_RESULT_RETRIES: Final = 5  # Bridge re-sends of DELIVERY_RESULT until RESULT_ACK
MESH_RESULT_RETRY_MS: Final = 2000  # Interval between DELIVERY_RESULT re-sends
RESULT_FLAG_DUPLICATE: Final = 0x01  # DELIVERY_RESULT / EVT_RESULT flags bit0: the tag re-sent its stored ACK (RESULT.flags.bit0)
RESULT_FLAG_ESCALATED: Final = 0x02  # DELIVERY_RESULT / EVT_RESULT flags bit1: an unauthenticated tag status ended the job after 3 consecutive refusals (protocol.md 10)
LAYOUT_TYPICAL_MAX: Final = 1024  # Typical logical card upper bound (design target, not enforced)
LAYOUT_HARD_MAX: Final = 4096  # Hard maximum logical screen size in bytes
LAYOUT_SERIAL_MAX: Final = 4000  # Largest layout the companion sends: DELIVER_LAYOUT's CBOR envelope must fit SERIAL_MAX_PAYLOAD (bridges still accept up to LAYOUT_HARD_MAX)
LAYOUT_MAX_GLYPHS: Final = 512  # Hard maximum positioned glyphs per screen
LAYOUT_MAX_COMMANDS: Final = 256  # Hard maximum commands per screen
LAYOUT_CHUNK_DATA_MAX: Final = 150  # Layout bytes per mesh LAYOUT_CHUNK
LAYOUT_MAX_CHUNKS: Final = 28  # ceil(LAYOUT_HARD_MAX / LAYOUT_CHUNK_DATA_MAX)
LAYOUT_DIGEST_LEN: Final = 16  # Layout digest = SHA-256(layout bytes) truncated to 16 bytes
LAYOUT_QR_MAX_TEXT: Final = 96  # Maximum QR payload bytes (short token-free https link)
LAYOUT_MAX_QR: Final = 4  # Hard maximum QR commands per screen (render cost, protocol.md 4.3)
LAYOUT_MAX_LINE_STEPS: Final = 16384  # Hard maximum of the sum over LINE commands of max(|dx|,|dy|)+1 (render cost, protocol.md 4.3)
LAYOUT_MAX_SIDE: Final = 2048  # Maximum layout width/height in pixels (§4.3)
QR_MIN_VERSION: Final = 1  # Nayuki encodeText minVersion (§4.4)
QR_MAX_VERSION: Final = 10  # Nayuki encodeText maxVersion (§4.4)
ICON_FACE_ID: Final = 0  # Font-pack face id of the icon face (glyph id = icon id)
ENROLLMENT_VERSION: Final = 1  # Version byte of the UICR enrollment blob (§9)
TAG_TXN_RECORD_LEN: Final = 60  # Persisted tag display record length (§6)
TAG_TXN_RECORD_VERSION: Final = 1  # Persisted tag display record version (§6)
FONTPACK_ID_LEN: Final = 8  # Font-pack id = first 8 bytes of the pack content SHA-256
FRAME_DIGEST_LEN: Final = 32  # Frame digest = SHA-256 over plane 0 bytes then plane 1 bytes
MAX_BRIDGES: Final = 5  # Bridges per gateway (qualified topology)
MAX_TAGS: Final = 20  # Tags per gateway (qualified topology)
MAX_TAGS_PER_BRIDGE: Final = 20  # Assignment table size on a bridge
TAG_KEY_LEN: Final = 16  # Per-epoch tag authorization key length (K_epoch)
TAG_SECRET_LEN: Final = 32  # Per-tag enrollment secret length
TAG_NONCE_LEN: Final = 16  # Handshake nonce length, each side
TAG_MAC_LEN: Final = 16  # Truncated HMAC-SHA256 length in the handshake
TAG_RECORD_MIC_LEN: Final = 8  # AES-CCM tag length on records
TAG_RECORD_BUF: Final = 256  # Tag reassembly buffer size (two of these)
TAG_RECORD_PAYLOAD_MAX: Final = 192  # Maximum plaintext payload per authenticated record
TAG_PLANE_DATA_MAX: Final = 189  # Image bytes per PLANE_DATA record (192 - 3 header bytes)
TAG_RECORD_WIRE_MAX: Final = 205  # type(1) + counter(4) + TAG_RECORD_PAYLOAD_MAX + mic(8)
TAG_CTRL_MSG_MAX: Final = 64  # Maximum reassembled control message
ATT_MTU: Final = 23  # Compatibility baseline ATT MTU
ATT_VALUE_MAX: Final = 20  # ATT_MTU - 3
FRAG_PAYLOAD_MAX: Final = 19  # ATT_VALUE_MAX - 1 fragment header byte
TAG_WAKE_PERIOD_MS: Final = 30000  # Nominal RTC wake period
TAG_WAKE_JITTER_MS: Final = 3000  # Uniform +/- jitter added to each wake
TAG_ADV_WINDOW_MS: Final = 2000  # Connectable advertising window per wake
TAG_ADV_INTERVAL_MS: Final = 250  # Advertising interval during the window
TAG_SESSION_TIMEOUT_MS: Final = 20000  # Tag drops a connection with no progress for this long
BRIDGE_CONN_ATTEMPT_MS: Final = 1000  # Bounded BLE connection initiation (mesh is suspended meanwhile)
BRIDGE_STRIP_ROWS: Final = 16  # Native panel rows per rendering strip
BRIDGE_TAG_BACKOFF_MS: Final = 15000  # Minimum wait before retrying a tag after a failed attempt
BRIDGE_MAX_SUSPENDS_PER_MIN: Final = 6  # Upper bound on mesh suspend/resume cycles per minute (anti-starvation)
FONT_SIZES: Final[tuple[int, ...]] = (16, 24, 32,)  # Glyph strike sizes in pixels
ICON_SIZES: Final[tuple[int, ...]] = (16, 24, 32, 48,)  # Icon strike sizes in pixels
FONTPACK_WORKING_SPACE: Final = 16777216  # 16 MiB bridge working space in the flash sizing rule (production parts; development boards may configure a smaller one, docs/fontpack.md §3)
FONTPACK_DIR_SIZE: Final = 65536  # Slot directory area at the START OF THE WORKING SPACE (offset 2 * slot_size), docs/fontpack.md §3
SECURE_PROTO_VERSION: Final = 2  # Secure-setup protocol version reported by IDENTIFY / IDENT and the v2 advertising ver byte (serial framing keeps PROTO_VERSION)
DEVICE_ID_LEN: Final = 16  # device_id = SHA-256(label | role | ik_pub)[0:16]
IDENTITY_KEY_LEN: Final = 32  # X25519 identity / controller public key length
AUTHORITY_KEY_LEN: Final = 32  # Ed25519 authority public key length
GRANT_SIG_LEN: Final = 64  # Ed25519 signature length of a grant
GRANT_MAX: Final = 192  # Largest canonical CBOR grant a device accepts
CHALLENGE_LEN: Final = 16  # Single-use device challenge carried by IDENTIFY / IDENT
OWNER_LEN: Final = 16  # Owner = profile UUID bytes
PROOF_LEN: Final = 16  # Truncated HMAC proofs (setup, root, maintenance)
SETUP_SECRET_LEN: Final = 10  # Factory setup secret (80 bits) printed on bridge/tag labels
SETUP_PAYLOAD_LEN: Final = 15  # Setup code payload: (0x20|role) u8, short_id u32le, setup secret
SETUP_CODE_LEN: Final = 25  # Setup code symbols: 24 Crockford base32 + 1 check symbol
SETUP_CODE_POLY: Final = 0x25  # GF(32) modulus x^5+x^2+1; check = sum over data symbols v_i (i from 0) of alpha^(i+1) * v_i with alpha = 2: catches every single substitution and adjacent transposition
OP_KEY_LEN: Final = 32  # Tag operational root / bridge maintenance key length
STATIC_OOB_LEN: Final = 32  # Mesh static OOB value length (HMAC-SHA256 provisioning)
TUNNEL_DATA_MAX: Final = 150  # Payload bytes per mesh TUNNEL_DATA fragment
TUNNEL_MSG_MAX: Final = 400  # Largest reassembled tunnel message (serial TUNNEL_SEND data)
PAIR_MSG_MAX: Final = 320  # Largest reassembled message on the tag PAIR characteristic
DISCOVER_MAX_S: Final = 120  # Longest DISCOVER window
DISCOVERED_MIN_INTERVAL_MS: Final = 5000  # EVT_DISCOVERED at most once per (bridge, tag) per this interval
SECURE_MAX_FAILURES: Final = 3  # Consecutive failed proofs before a tag skips its next wake window


class Status(IntEnum):
    """Status codes shared by serial, mesh, GATT and receipts."""

    OK = 0  # Success
    ACCEPTED = 1  # Accepted for asynchronous processing
    DUPLICATE = 2  # Already processed; the stored result is returned
    BUSY = 3  # Temporarily unable (queue full, one-outstanding-send rule); retry later
    NO_RESOURCES = 4  # Out of memory/slots
    INVALID = 5  # Malformed or out-of-bounds input
    UNSUPPORTED = 6  # Unknown message/command/version feature
    NOT_FOUND = 7  # Unknown node, tag, update or op
    STALE_EPOCH = 8  # Assignment epoch older than the stored one
    STALE_REVISION = 9  # Revision older than the displayed/desired one
    REVISION_CONFLICT = 10  # Same (epoch, revision) with a different digest
    FONTPACK_MISMATCH = 11  # Layout references a font pack the bridge does not have active
    DIGEST_MISMATCH = 12  # Computed digest differs from the announced one
    INCOMPLETE = 13  # Missing chunks/records
    AUTH_FAILED = 14  # Handshake MAC, record MIC or counter check failed
    TIMEOUT = 15  # Operation timed out
    CONNECT_FAILED = 16  # BLE connection could not be established
    DISCONNECTED = 17  # Link dropped mid-session
    MESH_SUSPEND_FAILED = 18  # bt_mesh_suspend() rejected; no connection was attempted
    MESH_RESUME_FAILED = 19  # bt_mesh_resume() failed; session aborted, recovery entered
    PANEL_ERROR = 20  # Panel controller error (SPI, BUSY stuck, bad staging)
    REFRESH_TIMEOUT = 21  # BUSY did not release within the panel's refresh bound
    STORAGE_ERROR = 22  # Persistent storage read/write failed
    DISPLAY_STATE_UNKNOWN = 23  # Reset between physical refresh and result persistence; screen content uncertain
    CANCELLED = 24  # Cancelled by a newer revision, reassignment or operator
    NOT_ASSIGNED = 25  # Tag is not assigned to this bridge (or epoch differs)
    TOO_LARGE = 26  # Exceeds a hard size/count limit
    CRC_ERROR = 27  # Frame/strike CRC mismatch
    VERSION_MISMATCH = 28  # Peer protocol version not supported
    SECURITY_CONFIG = 29  # Missing/invalid key material or enrollment; stop and report
    INTERNAL = 30  # Unexpected internal error
    PROVISIONING_ACTIVE = 31  # Refused while provisioning/configuration is in progress
    EXPIRED = 32  # Job TTL elapsed before delivery
    SUPERSEDED = 33  # Replaced by a newer revision for the same tag/slot
    AUTH_REQUIRED = 34  # v2: the request needs a secure session (plaintext refused)
    NOT_OWNER = 35  # v2: the session's controller may not do this in the device's ownership state
    GRANT_INVALID = 36  # v2: grant malformed, wrong device/role/challenge/controller, or bad signature
    STALE_GENERATION = 37  # v2: grant gen_from is not the device's current generation
    PROOF_FAILED = 38  # v2: setup, root or maintenance proof did not verify
    LOCKED = 39  # v2: pairing is locked (removed bridge awaiting recommissioning, anti-brute-force pause)


class DeliveryStage(IntEnum):
    """Delivery stages."""

    QUEUED = 0  # Created by Cremind's projection worker
    COMPANION_ACCEPTED = 1  # Committed to the companion's durable queue
    GATEWAY_RECEIVED = 2  # Gateway acknowledged DELIVER_LAYOUT (serial ACK)
    BRIDGE_RECEIVED = 3  # Bridge validated the complete layout (LAYOUT_STATUS OK)
    TRANSFERRING = 4  # Bridge authenticated with the tag and is streaming the image
    REFRESHING = 5  # Tag validated the frame and started the panel refresh
    DISPLAYED = 6  # Tag reported BUSY complete and persisted the result (terminal)


class DeliveryOutcome(IntEnum):
    """Terminal delivery outcomes."""

    DISPLAYED = 0  # Refresh completed and ACKed
    SUPERSEDED = 1  # A newer revision replaced this one before display
    EXPIRED = 2  # TTL elapsed
    CANCELLED = 3  # Operator/ownership change cancelled it
    FAILED = 4  # Permanent failure (security/config/invalid) — stop and report
    UNCERTAIN = 5  # Refresh may or may not have happened (DISPLAY_STATE_UNKNOWN, lost result)


class SerialFlag(IntFlag):
    """Serial header flags bits."""

    RESPONSE = 0x01  # This frame answers request_id
    EVENT = 0x02  # Unsolicited event (request_id = 0)


class SerialMsg(IntEnum):
    """Serial message types."""

    HELLO = 0x01  # h2d: {proto, name} -> {status, proto, fw, build, boot_id, caps:{max_frame, credits, max_bridges, max_tags, role}}
    PING = 0x02  # h2d: {} -> {status, uptime_s}
    REBOOT = 0x03  # h2d: {op_id} -> {status}; device reboots after responding
    EVENT_ACK = 0x04  # h2d: {seq} -> {status}; releases retained events with seq <= given
    INFO = 0x05  # h2d: {} -> {status, fw, build, boot_id, caps, counters}
    IDENTIFY = 0x06  # h2d: v2 plaintext: {} -> {status, proto, role, device_id, ik, fw, build, board, owner_state, gen, authority_id?, challenge}
    SECURE_OPEN = 0x07  # h2d: v2 plaintext: {data} -> {status, data}: Noise IK message 1, then message 2; replaces any session
    SECURE_DATA = 0x08  # h2d: v2 carrier, both directions: {data} -> {status, data?}: one Noise transport message (type, flags, request_id, CBOR); a plaintext answer means the session failed
    CLAIM = 0x09  # h2d: v2 gateway, unowned: {grant, sig} -> {status, gen}
    RECOVER = 0x0A  # h2d: v2 gateway, owned, new controller: {grant, sig} -> {status, gen}
    RELEASE = 0x0B  # h2d: v2 any role: {grant, sig, release_stage} -> {status, gen, data?} (tag: stage 0 returns a fresh setup payload, stage 1 commits)
    STATUS = 0x0C  # h2d: v2 any role: {} -> {status, owner_state, gen, authority_id?, owner?, controller_match, challenge, root_proof?}
    PAIR = 0x0D  # h2d: v2 bridge/tag, unowned: {grant, sig, proof, op_key} -> {status, gen, proof}
    REKEY = 0x0E  # h2d: v2 bridge/tag, owned: {grant, sig, op_key} -> {status, gen}
    MAINT_AUTH = 0x0F  # h2d: v2 bridge maintenance port: {proof} -> {status}
    SCAN_UNPROV = 0x10  # h2d: {duration_s, uuid_filter?} -> {status}; emits EVT_UNPROV_BEACON
    PROVISION = 0x11  # h2d: {op_id, uuid, name?, static_oob?} -> {status: ACCEPTED}; later EVT_PROVISIONED; static_oob (v2) is required by v2 gateways
    CONFIGURE_NODE = 0x12  # h2d: {op_id, addr, relay, ttl} -> ACCEPTED; later EVT_NODE_CONFIGURED (app key add/bind + relay + TTL)
    REMOVE_NODE = 0x13  # h2d: {op_id, addr} -> ACCEPTED; later EVT_NODE_REMOVED (node reset + CDB delete)
    LIST_NODES = 0x14  # h2d: {} -> {status, nodes:[{addr, uuid, elements, configured, name, last_seen_s}]}
    DISCOVER = 0x16  # h2d: v2: {op_id, bridge, duration_s, tag_id} -> ACCEPTED; bridge 0 = every bridge, tag_id 0 = any v2 tag in setup mode; EVT_DISCOVERED
    RECOMMISSION = 0x17  # h2d: v2 bridge maintenance port only: {grant?, sig?} -> {status, gen, data}; owned (after MAINT_AUTH, a MAINT grant) or released; data = a fresh setup payload; leaves the mesh
    ASSIGN_TAG = 0x20  # h2d: {op_id, bridge, tag_id, epoch, key} -> ACCEPTED; later EVT_ASSIGN_RESULT
    UNASSIGN_TAG = 0x21  # h2d: {op_id, bridge, tag_id, epoch} -> ACCEPTED; later EVT_ASSIGN_RESULT
    DELIVER_LAYOUT = 0x30  # h2d: {op_id, bridge, tag_id, epoch, revision, update_id, fontpack_id, layout} -> {status: ACCEPTED|BUSY|INVALID|DUPLICATE}; later EVT_STAGE*, EVT_RESULT
    CANCEL_DELIVERY = 0x31  # h2d: {op_id, update_id} -> {status}
    TAG_COMMAND = 0x32  # h2d: {op_id, bridge, tag_id, epoch, cmd} -> ACCEPTED; later EVT_RESULT (update_id = op_id)
    TUNNEL_OPEN = 0x33  # h2d: v2: {op_id, bridge, tag_id, duration_s} -> {status, tunnel}; tag_id 0 = the bridge own endpoint; later EVT_TUNNEL
    TUNNEL_SEND = 0x34  # h2d: v2: {tunnel, data <= TUNNEL_MSG_MAX} -> {status}
    TUNNEL_CLOSE = 0x35  # h2d: v2: {tunnel} -> {status}
    GET_INVENTORY = 0x40  # h2d: {} -> {status, items:[bridge info]}; also refreshes via mesh CAPS/HEALTH (EVT_BRIDGE_INFO)
    GET_COUNTERS = 0x41  # h2d: {} -> {status, counters}
    IDENTIFY_NODE = 0x42  # h2d: {op_id, addr} -> {status}; bridge blinks/beeps
    FONT_BEGIN = 0x60  # h2d: {size, digest(32), fontpack_id} -> {status, slot, flash_size}
    FONT_DATA = 0x61  # h2d: {offset, data} -> {status}; offsets strictly sequential
    FONT_COMMIT = 0x62  # h2d: {} -> {status, fontpack_id}; verifies SHA-256 then flips the slot directory
    FONT_STATUS = 0x63  # h2d: {} -> {status, fontpack_id, slot, size, flash_size}
    FONT_ABORT = 0x64  # h2d: {} -> {status}
    FLASH_TEST = 0x65  # h2d: {op_id} -> {status, flash_size, items:[{offset, status}]}; erase/write/read-back patterns at the first and last sectors of the inactive slot, the last sector of the device (the working space ends there) and, when neither lies in the active slot or the directory, the sectors either side of the 16 MiB boundary (else that item reports BUSY); never touches the active slot or the directory
    FACTORY_SETUP = 0x66  # h2d: v2 factory, unowned bridge without a setup secret: {data} -> {status}; data = the 10-byte setup secret; refused (LOCKED) once one is stored
    EVT_LOG = 0x80  # d2h: {text} diagnostic, not retained
    EVT_UNPROV_BEACON = 0x81  # d2h: {uuid, rssi, oob}
    EVT_PROVISIONED = 0x82  # d2h: {seq, op_id, uuid, addr, elements, status}
    EVT_NODE_CONFIGURED = 0x83  # d2h: {seq, op_id, addr, status}
    EVT_NODE_REMOVED = 0x84  # d2h: {seq, op_id, addr, status}
    EVT_ASSIGN_RESULT = 0x85  # d2h: {seq, op_id, bridge, tag_id, epoch, status}
    EVT_STAGE = 0x86  # d2h: {update_id, tag_id, revision, stage} best effort, not retained
    EVT_RESULT = 0x87  # d2h: {seq, update_id, bridge, tag_id, epoch, revision, status, digest(8), battery_mv, timing, flags, stored_epoch} (flags and stored_epoch as in mesh DELIVERY_RESULT)
    EVT_BRIDGE_INFO = 0x88  # d2h: {addr, fw, fontpack_id, caps:{board, flash_size, max_tags, assigned_count, flags, proto}, assigned, counters}
    EVT_TAG_SEEN = 0x89  # d2h: {bridge, tag_id, rssi, battery_mv, flags} rate-limited sighting
    EVT_TUNNEL = 0x8A  # d2h: v2: {tunnel, bridge, tag_id, state, data?, status?} not retained
    EVT_DISCOVERED = 0x8B  # d2h: v2: {bridge, tag_id, rssi, flags} not retained; a candidate, never inventory


class CborKey(IntEnum):
    """Integer keys of serial CBOR maps (field name = member name, lower case)."""

    STATUS = 0
    OP_ID = 1  # uint64 chosen by the companion; idempotency key for side-effecting requests
    ADDR = 2  # mesh unicast address (uint)
    UUID = 3  # 16-byte mesh device UUID (bstr)
    TAG_ID = 4  # uint32
    EPOCH = 5  # uint32 assignment epoch
    REVISION = 6  # uint32 display revision
    UPDATE_ID = 7  # uint64 Cremind delivery id
    FONTPACK_ID = 8  # bstr[8]
    LAYOUT = 9  # bstr (logical screen, <= LAYOUT_HARD_MAX)
    STAGE = 10  # uint delivery_stages
    DETAIL = 11  # uint status detail / sub-code
    RSSI = 12  # int
    OOB = 13  # uint OOB info bits
    DURATION_S = 14  # uint
    RELAY = 15  # bool
    TTL = 16  # uint
    KEY = 17  # bstr[16]
    FW = 18  # tstr "x.y.z"
    BUILD = 19  # tstr build id / git hash
    BOOT_ID = 20  # uint32 random per boot
    CAPS = 21  # map
    NODES = 22  # array of maps
    ELEMENTS = 23  # uint
    NAME = 24  # tstr
    COUNTERS = 25  # map tstr -> uint
    BATTERY_MV = 26  # uint
    TIMING = 27  # map {wake_ms, mesh_ms, transfer_ms, refresh_ms, suspend_ms}
    DIGEST = 28  # bstr
    PROTO = 29  # uint protocol version
    MAX_FRAME = 30  # uint
    CREDITS = 31  # uint initial credits
    FLAGS = 32  # uint
    BRIDGE = 33  # uint mesh unicast address of a bridge
    ITEMS = 34  # array
    CMD = 35  # uint tag_commands
    SEQ = 36  # uint event sequence number (EVENT_ACK)
    TIME_MS = 37  # uint
    TEXT = 38  # tstr human-readable error text
    SIZE = 39  # uint byte size
    OFFSET = 40  # uint byte offset
    DATA = 41  # bstr
    ROLE = 42  # uint node_roles
    CONFIGURED = 43  # bool
    LAST_SEEN_S = 44  # uint seconds since last contact
    BOARD = 45  # uint board id
    PANEL = 46  # uint panel id
    FLASH_SIZE = 47  # uint bytes
    SLOT = 48  # uint font slot
    ASSIGNED = 49  # array of {tag_id, epoch}
    UPTIME_S = 50  # uint
    WAKE_MS = 51
    MESH_MS = 52
    TRANSFER_MS = 53
    REFRESH_MS = 54
    SUSPEND_MS = 55
    QUEUE_DEPTH = 56
    MAX_BRIDGES = 57
    MAX_TAGS = 58
    UUID_FILTER = 59  # bstr prefix filter for SCAN_UNPROV
    NET_IDX = 60
    APP_IDX = 61
    STORED_EPOCH = 62  # uint32 the tag's stored epoch as last reported by the tag (0 = unknown)
    ASSIGNED_COUNT = 63  # uint in a bridge's caps map: the tags assigned on the bridge itself (CAPS_STATUS.assigned)
    DEVICE_ID = 64  # bstr[16] v2 canonical device identity
    IK = 65  # bstr[32] v2 X25519 identity public key
    OWNER_STATE = 66  # uint v2 owner_states
    GEN = 67  # uint32 v2 ownership generation
    AUTHORITY_ID = 68  # bstr[16] v2 pinned authority id (present when owned)
    CHALLENGE = 69  # bstr[16] v2 single-use device challenge
    GRANT = 70  # bstr v2 canonical CBOR grant
    SIG = 71  # bstr[64] v2 Ed25519 grant signature
    STATIC_OOB = 72  # bstr[32] v2 mesh static OOB value (PROVISION)
    TUNNEL = 73  # uint v2 tunnel id
    STATE = 74  # uint v2 tunnel_states (EVT_TUNNEL)
    PROOF = 75  # bstr[16] v2 setup / maintenance proof
    OWNER = 76  # bstr[16] v2 pinned owner (profile UUID)
    CONTROLLER_MATCH = 77  # bool v2 the session's controller is the pinned one
    ROOT_PROOF = 78  # bstr[16] v2 HMAC(root, label | h) from an owned tag
    RELEASE_STAGE = 79  # uint v2 RELEASE stage (0 prepare, 1 commit)
    OP_KEY = 80  # bstr[32] v2 operational root (tag) / maintenance key (bridge) in PAIR and REKEY


class TagCommand(IntEnum):
    """Tag commands."""

    CLEAR = 1  # Clear to white (full refresh) and persist revision 0 for the epoch
    IDENTIFY = 2  # Companion-level: delivered as a new revision showing the tag id; a tag receiving it answers UNSUPPORTED
    REFRESH = 3  # Companion-level: re-delivers the current screen as a new revision; a tag receiving it answers UNSUPPORTED
    SLEEP = 4  # Enter shipping mode (System OFF) — only if external wake is verified


class NodeRole(IntEnum):
    """Node roles."""

    GATEWAY = 1  # Mesh provisioner + serial bridge to the companion
    BRIDGE = 2  # Mesh relay + BLE central + renderer
    TAG = 3  # Battery e-paper BLE peripheral


class MeshModel(IntEnum):
    """Vendor model ids (company MESH_COMPANY_ID)."""

    LAYOUT_SRV = 0x0001  # on bridge: Receives layouts; sends stage/result
    LAYOUT_CLI = 0x0002  # on gateway: Sends layouts; receives stage/result
    MGMT_SRV = 0x0003  # on bridge: Capabilities, health, assignments, tag commands, counters
    MGMT_CLI = 0x0004  # on gateway: Management client


class MeshOp(IntEnum):
    """6-bit vendor opcode numbers."""

    LAYOUT_BEGIN = 0x01  # handled by LAYOUT_SRV
    LAYOUT_CHUNK = 0x02  # handled by LAYOUT_SRV
    LAYOUT_COMMIT = 0x03  # handled by LAYOUT_SRV
    LAYOUT_CANCEL = 0x04  # handled by LAYOUT_SRV
    LAYOUT_STATUS = 0x05  # handled by LAYOUT_CLI
    DELIVERY_STAGE = 0x06  # handled by LAYOUT_CLI
    DELIVERY_RESULT = 0x07  # handled by LAYOUT_CLI
    RESULT_ACK = 0x08  # handled by LAYOUT_SRV
    CAPS_GET = 0x10  # handled by MGMT_SRV
    CAPS_STATUS = 0x11  # handled by MGMT_CLI
    HEALTH_GET = 0x12  # handled by MGMT_SRV
    HEALTH_STATUS = 0x13  # handled by MGMT_CLI
    ASSIGN_SET = 0x14  # handled by MGMT_SRV
    ASSIGN_DEL = 0x15  # handled by MGMT_SRV
    ASSIGN_STATUS = 0x16  # handled by MGMT_CLI
    TAG_CMD = 0x17  # handled by MGMT_SRV
    IDENTIFY = 0x18  # handled by MGMT_SRV
    TAG_SEEN = 0x19  # handled by MGMT_CLI
    TUNNEL_OPEN = 0x1A  # handled by MGMT_SRV
    TUNNEL_DATA = 0x1B  # handled by MGMT_SRV
    TUNNEL_CLOSE = 0x1C  # handled by MGMT_SRV
    DISCOVER = 0x1D  # handled by MGMT_SRV
    DISCOVERED = 0x1E  # handled by MGMT_CLI
    CAPS2_STATUS = 0x1F  # handled by MGMT_CLI
    TUNNEL_UP = 0x20  # handled by MGMT_CLI


def mesh_vendor_opcode(op: int) -> int:
    """3-octet opcode value as Zephyr's BT_MESH_MODEL_OP_3(op, MESH_COMPANY_ID)."""
    return ((0xC0 | op) << 16) | MESH_COMPANY_ID


def mesh_opcode_bytes(op: int) -> bytes:
    """On-air opcode octets: 0xC0 | op, then the company id little-endian."""
    return bytes([0xC0 | op]) + MESH_COMPANY_ID.to_bytes(2, "little")


LAYOUT_MAGIC: Final = 0x4C43  # bytes 'C','L'


class Color(IntEnum):
    """Layout colours."""

    WHITE = 0
    BLACK = 1
    RED = 2


class QrEcc(IntEnum):
    """QR error-correction levels (= Nayuki QrCode.Ecc ordinal)."""

    LOW = 0
    MEDIUM = 1
    QUARTILE = 2
    HIGH = 3


class LayoutCmd(IntEnum):
    """Layout command ops."""

    CLEAR = 0x01
    GLYPHS = 0x02  # A run of positioned glyphs from one (face, size) strike. Each glyph origin is relative to the previous glyph origin (the first to origin_x/origin_y). Origin = pen position on the baseline.
    ICON = 0x03
    LINE = 0x04
    RECT = 0x05
    PROGRESS = 0x06
    QR = 0x07


class Icon(IntEnum):
    """Built-in icon ids (glyph ids of face 0)."""

    INFO = 1
    CHECK_CIRCLE = 2
    ERROR = 3
    WARNING = 4
    HELP = 5
    CHAT = 6
    TASK = 7
    SCHEDULE = 8
    EVENT = 9
    NOTIFICATIONS = 10
    SYNC = 11
    BATTERY_FULL = 12
    BATTERY_LOW = 13
    WIFI_OFF = 14
    LINK_OFF = 15
    DESCRIPTION = 16
    BOLT = 17
    PUSH_PIN = 18
    BAR_CHART = 19
    APPROVAL = 20
    HOURGLASS = 21
    BUG_REPORT = 22
    FOLDER = 23
    PERSON = 24


GATT_BASE_UUID: Final = uuid.UUID("6a7c0000-4c1e-4b9f-9d2a-43524d544147")
GATT_SERVICE_SHORT: Final = 0x0001
GATT_SERVICE_UUID: Final = uuid.UUID("6a7c0001-4c1e-4b9f-9d2a-43524d544147")

class GattChr(IntEnum):
    """Characteristic short ids."""

    CAPS = 0x0002  # read: tag_caps struct (long read allowed)
    CTRL = 0x0003  # write, indicate: Fragmented control messages: handshake + plaintext errors
    DATA = 0x0004  # write_without_response: Fragmented authenticated records (bridge -> tag)
    STATUS = 0x0005  # notify: Credit grants (plaintext) and fragmented authenticated records (tag -> bridge)
    IDENT = 0x0006  # read: v2: ident2 struct (long read); a fresh challenge per connection
    PAIR = 0x0007  # write, indicate: v2: fragmented secure-endpoint messages (kind u8 | body), <= PAIR_MSG_MAX

GATT_CHR_UUIDS: Final[dict[GattChr, uuid.UUID]] = {
    GattChr.CAPS: uuid.UUID("6a7c0002-4c1e-4b9f-9d2a-43524d544147"),
    GattChr.CTRL: uuid.UUID("6a7c0003-4c1e-4b9f-9d2a-43524d544147"),
    GattChr.DATA: uuid.UUID("6a7c0004-4c1e-4b9f-9d2a-43524d544147"),
    GattChr.STATUS: uuid.UUID("6a7c0005-4c1e-4b9f-9d2a-43524d544147"),
    GattChr.IDENT: uuid.UUID("6a7c0006-4c1e-4b9f-9d2a-43524d544147"),
    GattChr.PAIR: uuid.UUID("6a7c0007-4c1e-4b9f-9d2a-43524d544147"),
}

FRAG_START: Final = 0x80  # First fragment of a message/record
FRAG_END: Final = 0x40  # Last fragment
FRAG_SEQ_MASK: Final = 0x3F  # Fragment counter mod 64 per characteristic and direction, continuous across messages, reset to 0 on connect


class CtrlMsg(IntEnum):
    """CTRL message types."""

    HELLO = 0x01  # b2t
    CHALLENGE = 0x02  # t2b
    AUTH = 0x03  # b2t
    AUTH_OK = 0x04  # t2b
    ERROR = 0x05  # t2b


class RecordType(IntEnum):
    """Authenticated record types."""

    FRAME_BEGIN = 0x10  # b2t
    PLANE_DATA = 0x11  # b2t
    FRAME_END = 0x12  # b2t
    FRAME_ABORT = 0x13  # b2t
    CMD = 0x14  # b2t
    RESULT = 0x20  # t2b
    PROGRESS = 0x21  # t2b


class RecordDir(IntEnum):
    """Record nonce direction byte."""

    B2T = 0
    T2B = 1


class PlainMsg(IntEnum):
    """Plaintext STATUS message types."""

    CREDIT = 0xC0  # t2b


CRYPTO_HKDF_SALT_EPOCH: Final = b'cremind-tag/v1/epoch'
CRYPTO_HKDF_INFO_EPOCH_PREFIX: Final = b'K_epoch'
CRYPTO_MAC_LABEL_BRIDGE: Final = b'B'
CRYPTO_MAC_LABEL_TAG: Final = b'T'
CRYPTO_HKDF_INFO_SESSION: Final = b'cremind-tag/v1/session'


class GrantOp(IntEnum):
    """Grant operations (grant key 1)."""

    CLAIM = 1  # First owner of an unowned gateway (direct USB)
    RECOVER = 2  # Owned gateway: authorise a new controller (replacement computer)
    PAIR = 3  # First owner of an unowned/released bridge or tag (with the setup proof)
    REKEY = 4  # Owned bridge/tag: new controller + mk (bridge) or new root (tag)
    RELEASE = 5  # Owned device: remove the owner (tag: two stages)
    MAINT = 6  # Owned bridge: recommission (leave the mesh, fresh setup secret)


class OwnerState(IntEnum):
    """Device ownership states."""

    UNOWNED = 0  # Factory state (or after a physical factory reset)
    OWNED = 1  # Pinned authority, owner and generation
    RELEASED = 2  # Released tag: pairs only with the fresh setup secret it showed


class Link(IntEnum):
    """Noise prologue link byte."""

    SERIAL = 1  # Noise prologue link byte: USB serial (gateway, bridge maintenance port)
    TUNNEL = 2  # Noise prologue link byte: mesh tunnel (bridge endpoint or tag PAIR)


class TunnelState(IntEnum):
    """EVT_TUNNEL states."""

    OPEN = 1  # EVT_TUNNEL: the endpoint answered; data = its ident2
    DATA = 2  # EVT_TUNNEL: one reassembled message from the endpoint
    CLOSED = 3  # EVT_TUNNEL: closed (status says why)


class PairKind(IntEnum):
    """First byte of a PAIR / tunnel message."""

    HANDSHAKE = 1  # PAIR / tunnel message: a Noise handshake message
    TRANSPORT = 2  # PAIR / tunnel message: a Noise transport message
    CLOSE = 3  # PAIR / tunnel message: close {status u8}


class AdvFlag(IntFlag):
    """Tag advertising flags."""

    RESULT_PENDING = 0x01  # v1: a result is waiting
    LOW_BATTERY = 0x02  # v1: battery low
    STATE_UNKNOWN = 0x04  # v1: display state unknown
    SETUP = 0x08  # v2: unowned or released, pairing possible
    OWNED = 0x10  # v2: owned


V2_NOISE_PROTOCOL: Final = b'Noise_IK_25519_ChaChaPoly_SHA256'
V2_PROLOGUE: Final = b'cremind-tag/v2'
V2_DEVICE_ID: Final = b'cremind-tag/v2/device-id'
V2_GRANT: Final = b'cremind-tag/v2/grant'
V2_SETUP_SALT: Final = b'cremind-tag/v2/setup'
V2_MESH_OOB_SALT: Final = b'cremind-tag/v2/mesh-oob'
V2_EPOCH_SALT: Final = b'cremind-tag/v2/epoch'
V2_ROOT_PROOF: Final = b'cremind-tag/v2/root-proof'
V2_MAINT_PROOF: Final = b'cremind-tag/v2/maint'
V2_SETUP_LABEL_S: Final = b'S'
V2_SETUP_LABEL_D: Final = b'D'
V2_UICR_IDENTITY_OFFSET: Final = 32

ENROLLMENT_MAGIC: Final = 0x47415443  # bytes 'C','T','A','G'


class Board(IntEnum):
    """Board ids."""

    NRF52840DK_GATEWAY = 1  # nRF52840 DK / dongle gateway (USB CDC ACM)
    NRF52832_GATEWAY = 2  # nRF52832 + CH340 UART gateway
    NRF52840_BRIDGE = 3  # nRF52840 bridge with soldered external flash
    NRF52832_BRIDGE = 4  # nRF52832 bridge variant (resource qualification pending)
    LAOWU_BW_NRF51822 = 16  # Laowu 4.2in black/white, nRF51822 128K/16K
    LAOWU_BWR_NRF51802 = 17  # Laowu 4.2in black/white/red, nRF51802 256K/16K
    SIFEI_NRF52810 = 18  # Sifei 52810, 192K/24K
    HEMA_NRF52811 = 19  # Hema/Alibaba 52811, 192K/24K
    NRF52DK_TAG = 20  # nRF52 DK development tag (display optional)


class Panel(IntEnum):
    """Panel ids."""

    NONE = 0  # No panel (dev/test)
    UC8176_420_BW = 1  # 4.2in 400x300 UC8176 monochrome
    UC8176_420_BWR = 2  # 4.2in 400x300 UC8176 black/white/red
    UNVERIFIED = 255  # Panel not yet physically verified (Sifei/Hema)


FONTPACK_MAGIC: Final = 0x50465443
FONTPACK_VERSION: Final = 1
FONTPACK_HEADER_SIZE: Final = 128
FONTPACK_FACE_RECORD_SIZE: Final = 16
FONTPACK_STRIKE_RECORD_SIZE: Final = 24
FONTPACK_GLYPH_ENTRY_SIZE: Final = 12
FONTPACK_EMPTY_BITMAP: Final = 0xFFFFFFFF
FONTPACK_SLOT_DIR_MAGIC: Final = 0x4C535443
