"""Fixed-layout protocol messages (mirror of include/ctag/proto_msgs.h).

DO NOT EDIT: generated by tools/codegen.py from protocol/spec.yaml.
spec sha256: 729103a9c513c5cf7b1375863b9aa16dc9ab6358ecc6f294edd8c30edee628ce

Each dataclass packs its fields little-endian in spec order; the
type/opcode byte is framing and not part of the layout. ``unpack`` rejects
short input (TruncatedError) and input longer than the layout
(OversizeError); a trailing ``bytes`` field takes the rest up to its max;
messages followed by a variable part decode only their fixed part.
"""

from __future__ import annotations

import struct
from dataclasses import dataclass
from typing import ClassVar, Protocol, Self

from .ids import LAYOUT_CHUNK_DATA_MAX, TAG_PLANE_DATA_MAX, TUNNEL_DATA_MAX, CtrlMsg, LayoutCmd, MeshOp, PlainMsg, RecordType


class MessageError(ValueError):
    """A fixed-layout message could not be packed or unpacked."""


class TruncatedError(MessageError):
    """Input shorter than the message's fixed part (C: -EINVAL)."""


class OversizeError(MessageError):
    """Input or a trailing field longer than allowed (C: -EMSGSIZE)."""


class FixedMessage(Protocol):
    """Shape shared by every generated message class."""

    LEN: ClassVar[int]

    def pack(self) -> bytes: ...

    @classmethod
    def unpack(cls, buf: bytes) -> Self: ...


def _pack(layout: struct.Struct, *values: int | bytes) -> bytes:
    try:
        return layout.pack(*values)
    except struct.error as exc:
        raise MessageError(str(exc)) from None


def _check_bytes(value: bytes, size: int, name: str) -> None:
    if len(value) != size:
        raise MessageError(f"{name}: expected {size} bytes, got {len(value)}")


def _check_len(buf: bytes, fixed: int, longest: int | None) -> None:
    if len(buf) < fixed:
        raise TruncatedError(f"{len(buf)} bytes, need {fixed}")
    if longest is not None and len(buf) > longest:
        raise OversizeError(f"{len(buf)} bytes, at most {longest}")


@dataclass(frozen=True, slots=True)
class SerialHeader:
    """Serial frame header."""

    LEN: ClassVar[int] = 8
    _S: ClassVar[struct.Struct] = struct.Struct("<BBHHBB")

    version: int  # PROTO_VERSION
    type: int  # Message type
    request_id: int  # Echoed in responses; 0 for events
    length: int  # Payload length
    flags: int  # serial.flags bits
    credits: int  # Incremental credit grant: extra frames the SENDER of this frame can now receive

    def pack(self) -> bytes:
        return _pack(self._S, self.version, self.type, self.request_id, self.length, self.flags, self.credits)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshLayoutBegin:
    """Mesh LAYOUT_BEGIN parameters (opcode 0x01, handled by LAYOUT_SRV)."""

    TYPE: ClassVar[int] = MeshOp.LAYOUT_BEGIN
    LEN: ClassVar[int] = 49
    _S: ClassVar[struct.Struct] = struct.Struct("<HIIIQ8sHB16s")

    xfer_id: int
    tag_id: int
    epoch: int
    revision: int
    update_id: int
    fontpack_id: bytes
    total_len: int
    chunk_count: int
    digest: bytes

    def pack(self) -> bytes:
        _check_bytes(self.fontpack_id, 8, "fontpack_id")
        _check_bytes(self.digest, 16, "digest")
        return _pack(self._S, self.xfer_id, self.tag_id, self.epoch, self.revision, self.update_id, self.fontpack_id, self.total_len, self.chunk_count, self.digest)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshLayoutChunk:
    """Mesh LAYOUT_CHUNK parameters (opcode 0x02, handled by LAYOUT_SRV)."""

    TYPE: ClassVar[int] = MeshOp.LAYOUT_CHUNK
    LEN: ClassVar[int] = 3
    MAX_LEN: ClassVar[int] = 3 + LAYOUT_CHUNK_DATA_MAX
    _S: ClassVar[struct.Struct] = struct.Struct("<HB")

    xfer_id: int
    index: int
    data: bytes  # Every chunk but the last is exactly 150 bytes

    def pack(self) -> bytes:
        if len(self.data) > LAYOUT_CHUNK_DATA_MAX:
            raise OversizeError(f"data: {len(self.data)} bytes > LAYOUT_CHUNK_DATA_MAX")
        return _pack(self._S, self.xfer_id, self.index) + bytes(self.data)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.MAX_LEN)
        (xfer_id, index,) = cls._S.unpack_from(buf)
        return cls(xfer_id, index, bytes(buf[cls.LEN :]))


@dataclass(frozen=True, slots=True)
class MeshLayoutCommit:
    """Mesh LAYOUT_COMMIT parameters (opcode 0x03, handled by LAYOUT_SRV)."""

    TYPE: ClassVar[int] = MeshOp.LAYOUT_COMMIT
    LEN: ClassVar[int] = 2
    _S: ClassVar[struct.Struct] = struct.Struct("<H")

    xfer_id: int

    def pack(self) -> bytes:
        return _pack(self._S, self.xfer_id)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshLayoutCancel:
    """Mesh LAYOUT_CANCEL parameters (opcode 0x04, handled by LAYOUT_SRV)."""

    TYPE: ClassVar[int] = MeshOp.LAYOUT_CANCEL
    LEN: ClassVar[int] = 8
    _S: ClassVar[struct.Struct] = struct.Struct("<Q")

    update_id: int

    def pack(self) -> bytes:
        return _pack(self._S, self.update_id)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshLayoutStatus:
    """Mesh LAYOUT_STATUS parameters (opcode 0x05, handled by LAYOUT_CLI)."""

    TYPE: ClassVar[int] = MeshOp.LAYOUT_STATUS
    LEN: ClassVar[int] = 7
    _S: ClassVar[struct.Struct] = struct.Struct("<HBI")

    xfer_id: int
    status: int
    missing: int  # Bit i set = chunk i missing (valid with INCOMPLETE)

    def pack(self) -> bytes:
        return _pack(self._S, self.xfer_id, self.status, self.missing)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshDeliveryStage:
    """Mesh DELIVERY_STAGE parameters (opcode 0x06, handled by LAYOUT_CLI)."""

    TYPE: ClassVar[int] = MeshOp.DELIVERY_STAGE
    LEN: ClassVar[int] = 17
    _S: ClassVar[struct.Struct] = struct.Struct("<QIIB")

    update_id: int
    tag_id: int
    revision: int
    stage: int

    def pack(self) -> bytes:
        return _pack(self._S, self.update_id, self.tag_id, self.revision, self.stage)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshDeliveryResult:
    """Mesh DELIVERY_RESULT parameters (opcode 0x07, handled by LAYOUT_CLI)."""

    TYPE: ClassVar[int] = MeshOp.DELIVERY_RESULT
    LEN: ClassVar[int] = 46
    _S: ClassVar[struct.Struct] = struct.Struct("<HQIIIB8sHHHHHIB")

    result_seq: int  # Bridge-local sequence, echoed by RESULT_ACK
    update_id: int
    tag_id: int
    epoch: int
    revision: int
    status: int
    digest: bytes  # First 8 bytes of the frame digest (zeros if none)
    battery_mv: int
    wake_ms: int  # Layout validated -> tag connected
    suspend_ms: int  # Mesh suspended duration for the connection attempt
    transfer_ms: int
    refresh_ms: int
    stored_epoch: int = 0  # The tag's stored epoch as its ERROR or CHALLENGE reported it (after AUTH_OK at least the session's epoch); 0 = unknown (no session produced this result)
    flags: int = 0  # bit0 the tag re-sent its stored ACK (RESULT.flags.bit0, duplicate); bit1 an unauthenticated status escalated after 3 consecutive refusals (protocol.md 10)

    def pack(self) -> bytes:
        _check_bytes(self.digest, 8, "digest")
        return _pack(self._S, self.result_seq, self.update_id, self.tag_id, self.epoch, self.revision, self.status, self.digest, self.battery_mv, self.wake_ms, self.suspend_ms, self.transfer_ms, self.refresh_ms, self.stored_epoch, self.flags)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshResultAck:
    """Mesh RESULT_ACK parameters (opcode 0x08, handled by LAYOUT_SRV)."""

    TYPE: ClassVar[int] = MeshOp.RESULT_ACK
    LEN: ClassVar[int] = 2
    _S: ClassVar[struct.Struct] = struct.Struct("<H")

    result_seq: int

    def pack(self) -> bytes:
        return _pack(self._S, self.result_seq)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshCapsGet:
    """Mesh CAPS_GET parameters (opcode 0x10, handled by MGMT_SRV)."""

    TYPE: ClassVar[int] = MeshOp.CAPS_GET
    LEN: ClassVar[int] = 0
    _S: ClassVar[struct.Struct] = struct.Struct("<")

    def pack(self) -> bytes:
        return _pack(self._S)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshCapsStatus:
    """Mesh CAPS_STATUS parameters (opcode 0x11, handled by MGMT_CLI)."""

    TYPE: ClassVar[int] = MeshOp.CAPS_STATUS
    LEN: ClassVar[int] = 18
    _S: ClassVar[struct.Struct] = struct.Struct("<BBBBB8sHBBB")

    proto: int
    fw_major: int
    fw_minor: int
    fw_patch: int
    board: int
    fontpack_id: bytes
    flash_mib: int
    max_tags: int
    assigned: int
    flags: int  # bit0 font pack valid, bit1 busy with a tag session

    def pack(self) -> bytes:
        _check_bytes(self.fontpack_id, 8, "fontpack_id")
        return _pack(self._S, self.proto, self.fw_major, self.fw_minor, self.fw_patch, self.board, self.fontpack_id, self.flash_mib, self.max_tags, self.assigned, self.flags)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshHealthGet:
    """Mesh HEALTH_GET parameters (opcode 0x12, handled by MGMT_SRV)."""

    TYPE: ClassVar[int] = MeshOp.HEALTH_GET
    LEN: ClassVar[int] = 0
    _S: ClassVar[struct.Struct] = struct.Struct("<")

    def pack(self) -> bytes:
        return _pack(self._S)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshHealthStatus:
    """Mesh HEALTH_STATUS parameters (opcode 0x13, handled by MGMT_CLI)."""

    TYPE: ClassVar[int] = MeshOp.HEALTH_STATUS
    LEN: ClassVar[int] = 16
    _S: ClassVar[struct.Struct] = struct.Struct("<IHHHHHBB")

    uptime_s: int
    sessions_ok: int
    sessions_fail: int
    suspend_count: int
    suspend_max_ms: int
    resume_fail: int
    queue_depth: int
    last_status: int

    def pack(self) -> bytes:
        return _pack(self._S, self.uptime_s, self.sessions_ok, self.sessions_fail, self.suspend_count, self.suspend_max_ms, self.resume_fail, self.queue_depth, self.last_status)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshAssignSet:
    """Mesh ASSIGN_SET parameters (opcode 0x14, handled by MGMT_SRV)."""

    TYPE: ClassVar[int] = MeshOp.ASSIGN_SET
    LEN: ClassVar[int] = 25
    _S: ClassVar[struct.Struct] = struct.Struct("<II16sB")

    tag_id: int
    epoch: int
    key: bytes  # K_epoch for this (tag, epoch)
    flags: int  # bit0 primary bridge

    def pack(self) -> bytes:
        _check_bytes(self.key, 16, "key")
        return _pack(self._S, self.tag_id, self.epoch, self.key, self.flags)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshAssignDel:
    """Mesh ASSIGN_DEL parameters (opcode 0x15, handled by MGMT_SRV)."""

    TYPE: ClassVar[int] = MeshOp.ASSIGN_DEL
    LEN: ClassVar[int] = 8
    _S: ClassVar[struct.Struct] = struct.Struct("<II")

    tag_id: int
    epoch: int

    def pack(self) -> bytes:
        return _pack(self._S, self.tag_id, self.epoch)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshAssignStatus:
    """Mesh ASSIGN_STATUS parameters (opcode 0x16, handled by MGMT_CLI)."""

    TYPE: ClassVar[int] = MeshOp.ASSIGN_STATUS
    LEN: ClassVar[int] = 9
    _S: ClassVar[struct.Struct] = struct.Struct("<IIB")

    tag_id: int
    epoch: int
    status: int

    def pack(self) -> bytes:
        return _pack(self._S, self.tag_id, self.epoch, self.status)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshTagCmd:
    """Mesh TAG_CMD parameters (opcode 0x17, handled by MGMT_SRV)."""

    TYPE: ClassVar[int] = MeshOp.TAG_CMD
    LEN: ClassVar[int] = 17
    _S: ClassVar[struct.Struct] = struct.Struct("<QIIB")

    update_id: int  # Companion op id; results come back as DELIVERY_RESULT
    tag_id: int
    epoch: int
    cmd: int

    def pack(self) -> bytes:
        return _pack(self._S, self.update_id, self.tag_id, self.epoch, self.cmd)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshIdentify:
    """Mesh IDENTIFY parameters (opcode 0x18, handled by MGMT_SRV)."""

    TYPE: ClassVar[int] = MeshOp.IDENTIFY
    LEN: ClassVar[int] = 1
    _S: ClassVar[struct.Struct] = struct.Struct("<B")

    seconds: int

    def pack(self) -> bytes:
        return _pack(self._S, self.seconds)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshTagSeen:
    """Mesh TAG_SEEN parameters (opcode 0x19, handled by MGMT_CLI)."""

    TYPE: ClassVar[int] = MeshOp.TAG_SEEN
    LEN: ClassVar[int] = 8
    _S: ClassVar[struct.Struct] = struct.Struct("<IbHB")

    tag_id: int
    rssi: int
    battery_mv: int
    flags: int

    def pack(self) -> bytes:
        return _pack(self._S, self.tag_id, self.rssi, self.battery_mv, self.flags)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshTunnelOpen:
    """Mesh TUNNEL_OPEN parameters (opcode 0x1A, handled by MGMT_SRV)."""

    TYPE: ClassVar[int] = MeshOp.TUNNEL_OPEN
    LEN: ClassVar[int] = 7
    _S: ClassVar[struct.Struct] = struct.Struct("<HIB")

    tunnel: int
    tag_id: int  # 0 = the bridge's own secure endpoint
    timeout_s: int  # Idle timeout; the bridge closes the tunnel after this long without progress

    def pack(self) -> bytes:
        return _pack(self._S, self.tunnel, self.tag_id, self.timeout_s)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshTunnelData:
    """Mesh TUNNEL_DATA parameters (opcode 0x1B, handled by MGMT_SRV)."""

    TYPE: ClassVar[int] = MeshOp.TUNNEL_DATA
    LEN: ClassVar[int] = 4
    MAX_LEN: ClassVar[int] = 4 + TUNNEL_DATA_MAX
    _S: ClassVar[struct.Struct] = struct.Struct("<HBB")

    tunnel: int
    seq: int  # Fragment number within the message, from 0
    flags: int  # bit0 START, bit1 END
    data: bytes

    def pack(self) -> bytes:
        if len(self.data) > TUNNEL_DATA_MAX:
            raise OversizeError(f"data: {len(self.data)} bytes > TUNNEL_DATA_MAX")
        return _pack(self._S, self.tunnel, self.seq, self.flags) + bytes(self.data)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.MAX_LEN)
        (tunnel, seq, flags,) = cls._S.unpack_from(buf)
        return cls(tunnel, seq, flags, bytes(buf[cls.LEN :]))


@dataclass(frozen=True, slots=True)
class MeshTunnelClose:
    """Mesh TUNNEL_CLOSE parameters (opcode 0x1C, handled by MGMT_SRV)."""

    TYPE: ClassVar[int] = MeshOp.TUNNEL_CLOSE
    LEN: ClassVar[int] = 3
    _S: ClassVar[struct.Struct] = struct.Struct("<HB")

    tunnel: int
    status: int

    def pack(self) -> bytes:
        return _pack(self._S, self.tunnel, self.status)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshDiscover:
    """Mesh DISCOVER parameters (opcode 0x1D, handled by MGMT_SRV)."""

    TYPE: ClassVar[int] = MeshOp.DISCOVER
    LEN: ClassVar[int] = 5
    _S: ClassVar[struct.Struct] = struct.Struct("<BI")

    duration_s: int
    tag_id: int  # 0 = any v2 tag in setup mode

    def pack(self) -> bytes:
        return _pack(self._S, self.duration_s, self.tag_id)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshDiscovered:
    """Mesh DISCOVERED parameters (opcode 0x1E, handled by MGMT_CLI)."""

    TYPE: ClassVar[int] = MeshOp.DISCOVERED
    LEN: ClassVar[int] = 6
    _S: ClassVar[struct.Struct] = struct.Struct("<IbB")

    tag_id: int
    rssi: int
    flags: int  # The tag's advertising flags

    def pack(self) -> bytes:
        return _pack(self._S, self.tag_id, self.rssi, self.flags)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshCaps2Status:
    """Mesh CAPS2_STATUS parameters (opcode 0x1F, handled by MGMT_CLI)."""

    TYPE: ClassVar[int] = MeshOp.CAPS2_STATUS
    LEN: ClassVar[int] = 21
    _S: ClassVar[struct.Struct] = struct.Struct("<16sIB")

    device_id: bytes
    gen: int
    owner_state: int

    def pack(self) -> bytes:
        _check_bytes(self.device_id, 16, "device_id")
        return _pack(self._S, self.device_id, self.gen, self.owner_state)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class MeshTunnelUp:
    """Mesh TUNNEL_UP parameters (opcode 0x20, handled by MGMT_CLI)."""

    TYPE: ClassVar[int] = MeshOp.TUNNEL_UP
    LEN: ClassVar[int] = 4
    MAX_LEN: ClassVar[int] = 4 + TUNNEL_DATA_MAX
    _S: ClassVar[struct.Struct] = struct.Struct("<HBB")

    tunnel: int
    seq: int
    flags: int  # bit0 START, bit1 END, bit7 CLOSE (data = status u8)
    data: bytes

    def pack(self) -> bytes:
        if len(self.data) > TUNNEL_DATA_MAX:
            raise OversizeError(f"data: {len(self.data)} bytes > TUNNEL_DATA_MAX")
        return _pack(self._S, self.tunnel, self.seq, self.flags) + bytes(self.data)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.MAX_LEN)
        (tunnel, seq, flags,) = cls._S.unpack_from(buf)
        return cls(tunnel, seq, flags, bytes(buf[cls.LEN :]))


@dataclass(frozen=True, slots=True)
class LayoutHeader:
    """Layout header."""

    LEN: ClassVar[int] = 12
    _S: ClassVar[struct.Struct] = struct.Struct("<HBBHHBBH")

    magic: int
    version: int
    flags: int  # bit0 uses red
    width: int  # Logical (user-facing) width in px
    height: int  # Logical height in px
    rotation: int  # 0..3 = logical->native clockwise quarter turns
    background: int  # colors
    cmd_count: int

    def pack(self) -> bytes:
        return _pack(self._S, self.magic, self.version, self.flags, self.width, self.height, self.rotation, self.background, self.cmd_count)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class LayoutCmdClear:
    """Layout command CLEAR (op 0x01), after the op byte."""

    TYPE: ClassVar[int] = LayoutCmd.CLEAR
    LEN: ClassVar[int] = 1
    _S: ClassVar[struct.Struct] = struct.Struct("<B")

    color: int

    def pack(self) -> bytes:
        return _pack(self._S, self.color)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class LayoutCmdGlyphs:
    """Layout command GLYPHS (op 0x02), after the op byte; fixed part only (followed by glyph[count])."""

    TYPE: ClassVar[int] = LayoutCmd.GLYPHS
    LEN: ClassVar[int] = 9
    _S: ClassVar[struct.Struct] = struct.Struct("<HBBhhB")

    face: int
    size_px: int
    color: int
    origin_x: int
    origin_y: int
    count: int

    def pack(self) -> bytes:
        return _pack(self._S, self.face, self.size_px, self.color, self.origin_x, self.origin_y, self.count)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, None)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class LayoutCmdIcon:
    """Layout command ICON (op 0x03), after the op byte."""

    TYPE: ClassVar[int] = LayoutCmd.ICON
    LEN: ClassVar[int] = 8
    _S: ClassVar[struct.Struct] = struct.Struct("<HBBhh")

    icon: int  # icons[].id; drawn from face 0 (icon face)
    size_px: int
    color: int
    x: int  # top-left
    y: int

    def pack(self) -> bytes:
        return _pack(self._S, self.icon, self.size_px, self.color, self.x, self.y)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class LayoutCmdLine:
    """Layout command LINE (op 0x04), after the op byte."""

    TYPE: ClassVar[int] = LayoutCmd.LINE
    LEN: ClassVar[int] = 10
    _S: ClassVar[struct.Struct] = struct.Struct("<hhhhBB")

    x0: int
    y0: int
    x1: int
    y1: int
    width: int  # 1..8 px; square brush centred on the Bresenham path
    color: int

    def pack(self) -> bytes:
        return _pack(self._S, self.x0, self.y0, self.x1, self.y1, self.width, self.color)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class LayoutCmdRect:
    """Layout command RECT (op 0x05), after the op byte."""

    TYPE: ClassVar[int] = LayoutCmd.RECT
    LEN: ClassVar[int] = 10
    _S: ClassVar[struct.Struct] = struct.Struct("<hhHHBB")

    x: int
    y: int
    w: int
    h: int
    border: int  # 0 = filled, else outline thickness
    color: int

    def pack(self) -> bytes:
        return _pack(self._S, self.x, self.y, self.w, self.h, self.border, self.color)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class LayoutCmdProgress:
    """Layout command PROGRESS (op 0x06), after the op byte."""

    TYPE: ClassVar[int] = LayoutCmd.PROGRESS
    LEN: ClassVar[int] = 13
    _S: ClassVar[struct.Struct] = struct.Struct("<hhHHHHB")

    x: int
    y: int
    w: int
    h: int
    value: int
    max: int
    color: int

    def pack(self) -> bytes:
        return _pack(self._S, self.x, self.y, self.w, self.h, self.value, self.max, self.color)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class LayoutCmdQr:
    """Layout command QR (op 0x07), after the op byte; fixed part only (followed by str[len])."""

    TYPE: ClassVar[int] = LayoutCmd.QR
    LEN: ClassVar[int] = 8
    _S: ClassVar[struct.Struct] = struct.Struct("<hhBBBB")

    x: int
    y: int
    module_px: int  # 1..8
    ecc: int
    color: int
    len: int

    def pack(self) -> bytes:
        return _pack(self._S, self.x, self.y, self.module_px, self.ecc, self.color, self.len)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, None)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class LayoutGlyph:
    """One GLYPHS entry."""

    LEN: ClassVar[int] = 4
    _S: ClassVar[struct.Struct] = struct.Struct("<Hbb")

    glyph_id: int
    dx: int  # Pen offset from the previous glyph origin (the first: from origin_x)
    dy: int

    def pack(self) -> bytes:
        return _pack(self._S, self.glyph_id, self.dx, self.dy)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class TagCaps:
    """Tag CAPS characteristic value."""

    LEN: ClassVar[int] = 18
    _S: ClassVar[struct.Struct] = struct.Struct("<BIBBHHBBBBBBB")

    proto: int
    tag_id: int
    board: int
    panel: int
    width: int  # Native panel width
    height: int  # Native panel height
    planes: int  # 1 = BW, 2 = BW + red
    plane_flags: int  # bit0: plane0 bit 1 = white; bit1: plane1 bit 1 = red
    fw_major: int
    fw_minor: int
    fw_patch: int
    max_record: int  # TAG_RECORD_PAYLOAD_MAX
    credits: int  # Initial record credits after AUTH_OK

    def pack(self) -> bytes:
        return _pack(self._S, self.proto, self.tag_id, self.board, self.panel, self.width, self.height, self.planes, self.plane_flags, self.fw_major, self.fw_minor, self.fw_patch, self.max_record, self.credits)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class CtrlHello:
    """CTRL HELLO (type 0x01, b2t), after the type byte."""

    TYPE: ClassVar[int] = CtrlMsg.HELLO
    LEN: ClassVar[int] = 25
    _S: ClassVar[struct.Struct] = struct.Struct("<BII16s")

    proto: int
    tag_id: int
    epoch: int
    nonce_b: bytes

    def pack(self) -> bytes:
        _check_bytes(self.nonce_b, 16, "nonce_b")
        return _pack(self._S, self.proto, self.tag_id, self.epoch, self.nonce_b)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class CtrlChallenge:
    """CTRL CHALLENGE (type 0x02, t2b), after the type byte."""

    TYPE: ClassVar[int] = CtrlMsg.CHALLENGE
    LEN: ClassVar[int] = 29
    _S: ClassVar[struct.Struct] = struct.Struct("<B16sIIBHB")

    proto: int
    nonce_t: bytes
    stored_epoch: int
    displayed_rev: int
    last_status: int
    battery_mv: int
    flags: int  # bit0 DISPLAY_STATE_UNKNOWN pending, bit1 low battery

    def pack(self) -> bytes:
        _check_bytes(self.nonce_t, 16, "nonce_t")
        return _pack(self._S, self.proto, self.nonce_t, self.stored_epoch, self.displayed_rev, self.last_status, self.battery_mv, self.flags)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class CtrlAuth:
    """CTRL AUTH (type 0x03, b2t), after the type byte."""

    TYPE: ClassVar[int] = CtrlMsg.AUTH
    LEN: ClassVar[int] = 16
    _S: ClassVar[struct.Struct] = struct.Struct("<16s")

    mac_b: bytes

    def pack(self) -> bytes:
        _check_bytes(self.mac_b, 16, "mac_b")
        return _pack(self._S, self.mac_b)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class CtrlAuthOk:
    """CTRL AUTH_OK (type 0x04, t2b), after the type byte."""

    TYPE: ClassVar[int] = CtrlMsg.AUTH_OK
    LEN: ClassVar[int] = 16
    _S: ClassVar[struct.Struct] = struct.Struct("<16s")

    mac_t: bytes

    def pack(self) -> bytes:
        _check_bytes(self.mac_t, 16, "mac_t")
        return _pack(self._S, self.mac_t)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class CtrlError:
    """CTRL ERROR (type 0x05, t2b), after the type byte."""

    TYPE: ClassVar[int] = CtrlMsg.ERROR
    LEN: ClassVar[int] = 5
    _S: ClassVar[struct.Struct] = struct.Struct("<BI")

    status: int
    stored_epoch: int  # The tag's stored epoch, always filled (epochs are not secret); lets a bridge report how far a STALE_EPOCH refusal is behind

    def pack(self) -> bytes:
        return _pack(self._S, self.status, self.stored_epoch)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class RecFrameBegin:
    """Record FRAME_BEGIN plaintext (type 0x10, b2t)."""

    TYPE: ClassVar[int] = RecordType.FRAME_BEGIN
    LEN: ClassVar[int] = 47
    _S: ClassVar[struct.Struct] = struct.Struct("<IQ32sBH")

    revision: int
    update_id: int
    digest: bytes  # Frame digest the tag must reproduce
    planes: int
    plane_len: int  # Bytes per plane = ceil(width/8) * height

    def pack(self) -> bytes:
        _check_bytes(self.digest, 32, "digest")
        return _pack(self._S, self.revision, self.update_id, self.digest, self.planes, self.plane_len)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class RecPlaneData:
    """Record PLANE_DATA plaintext (type 0x11, b2t)."""

    TYPE: ClassVar[int] = RecordType.PLANE_DATA
    LEN: ClassVar[int] = 3
    MAX_LEN: ClassVar[int] = 3 + TAG_PLANE_DATA_MAX
    _S: ClassVar[struct.Struct] = struct.Struct("<BH")

    plane: int
    offset: int  # Must equal bytes already received for this plane
    data: bytes

    def pack(self) -> bytes:
        if len(self.data) > TAG_PLANE_DATA_MAX:
            raise OversizeError(f"data: {len(self.data)} bytes > TAG_PLANE_DATA_MAX")
        return _pack(self._S, self.plane, self.offset) + bytes(self.data)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.MAX_LEN)
        (plane, offset,) = cls._S.unpack_from(buf)
        return cls(plane, offset, bytes(buf[cls.LEN :]))


@dataclass(frozen=True, slots=True)
class RecFrameEnd:
    """Record FRAME_END plaintext (type 0x12, b2t)."""

    TYPE: ClassVar[int] = RecordType.FRAME_END
    LEN: ClassVar[int] = 0
    _S: ClassVar[struct.Struct] = struct.Struct("<")

    def pack(self) -> bytes:
        return _pack(self._S)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class RecFrameAbort:
    """Record FRAME_ABORT plaintext (type 0x13, b2t)."""

    TYPE: ClassVar[int] = RecordType.FRAME_ABORT
    LEN: ClassVar[int] = 1
    _S: ClassVar[struct.Struct] = struct.Struct("<B")

    status: int

    def pack(self) -> bytes:
        return _pack(self._S, self.status)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class RecCmd:
    """Record CMD plaintext (type 0x14, b2t)."""

    TYPE: ClassVar[int] = RecordType.CMD
    LEN: ClassVar[int] = 9
    _S: ClassVar[struct.Struct] = struct.Struct("<BQ")

    cmd: int
    update_id: int

    def pack(self) -> bytes:
        return _pack(self._S, self.cmd, self.update_id)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class RecResult:
    """Record RESULT plaintext (type 0x20, t2b)."""

    TYPE: ClassVar[int] = RecordType.RESULT
    LEN: ClassVar[int] = 30
    _S: ClassVar[struct.Struct] = struct.Struct("<QIIB8sHHB")

    update_id: int
    epoch: int
    revision: int
    status: int
    digest: bytes
    battery_mv: int
    refresh_ms: int
    flags: int  # bit0 duplicate (stored ACK re-sent)

    def pack(self) -> bytes:
        _check_bytes(self.digest, 8, "digest")
        return _pack(self._S, self.update_id, self.epoch, self.revision, self.status, self.digest, self.battery_mv, self.refresh_ms, self.flags)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class RecProgress:
    """Record PROGRESS plaintext (type 0x21, t2b)."""

    TYPE: ClassVar[int] = RecordType.PROGRESS
    LEN: ClassVar[int] = 1
    _S: ClassVar[struct.Struct] = struct.Struct("<B")

    stage: int  # delivery_stages.REFRESHING when validated and refresh starts

    def pack(self) -> bytes:
        return _pack(self._S, self.stage)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class PlainCredit:
    """STATUS plain CREDIT (type 0xC0, t2b), after the type byte."""

    TYPE: ClassVar[int] = PlainMsg.CREDIT
    LEN: ClassVar[int] = 1
    _S: ClassVar[struct.Struct] = struct.Struct("<B")

    credits: int  # Incremental grant of DATA records the bridge may send

    def pack(self) -> bytes:
        return _pack(self._S, self.credits)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class Enrollment:
    """Enrollment blob (UICR.CUSTOMER)."""

    LEN: ClassVar[int] = 48
    _S: ClassVar[struct.Struct] = struct.Struct("<IBBBBI32sI")

    magic: int
    version: int
    board: int
    panel: int
    flags: int
    tag_id: int
    secret: bytes
    crc32: int  # CRC-32/IEEE over all previous bytes

    def pack(self) -> bytes:
        _check_bytes(self.secret, 32, "secret")
        return _pack(self._S, self.magic, self.version, self.board, self.panel, self.flags, self.tag_id, self.secret, self.crc32)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class Ident2:
    """v2 IDENT characteristic value / tunnel OPEN data."""

    LEN: ClassVar[int] = 91
    _S: ClassVar[struct.Struct] = struct.Struct("<BB16s32sBI16s16sBBBB")

    proto: int  # SECURE_PROTO_VERSION
    role: int
    device_id: bytes
    ik: bytes
    owner_state: int
    gen: int
    authority_id: bytes  # Zeros when unowned
    challenge: bytes
    board: int
    fw_major: int
    fw_minor: int
    fw_patch: int

    def pack(self) -> bytes:
        _check_bytes(self.device_id, 16, "device_id")
        _check_bytes(self.ik, 32, "ik")
        _check_bytes(self.authority_id, 16, "authority_id")
        _check_bytes(self.challenge, 16, "challenge")
        return _pack(self._S, self.proto, self.role, self.device_id, self.ik, self.owner_state, self.gen, self.authority_id, self.challenge, self.board, self.fw_major, self.fw_minor, self.fw_patch)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class Enrollment2:
    """v2 enrollment blob (UICR.CUSTOMER[0..5])."""

    LEN: ClassVar[int] = 24
    _S: ClassVar[struct.Struct] = struct.Struct("<IBBBB10sHI")

    magic: int  # 'C','T','A','G' (as v1)
    version: int  # 2
    board: int
    panel: int
    flags: int
    setup_secret: bytes
    reserved: int
    crc32: int  # CRC-32/IEEE over all previous bytes

    def pack(self) -> bytes:
        _check_bytes(self.setup_secret, 10, "setup_secret")
        return _pack(self._S, self.magic, self.version, self.board, self.panel, self.flags, self.setup_secret, self.reserved, self.crc32)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


@dataclass(frozen=True, slots=True)
class UicrIdentity:
    """v2 identity copy (UICR.CUSTOMER at uicr_identity_offset)."""

    LEN: ClassVar[int] = 36
    _S: ClassVar[struct.Struct] = struct.Struct("<32sI")

    ik: bytes
    crc32: int  # CRC-32/IEEE over ik

    def pack(self) -> bytes:
        _check_bytes(self.ik, 32, "ik")
        return _pack(self._S, self.ik, self.crc32)

    @classmethod
    def unpack(cls, buf: bytes) -> Self:
        _check_len(buf, cls.LEN, cls.LEN)
        return cls(*cls._S.unpack_from(buf))


MESH_MESSAGES: dict[MeshOp, type[FixedMessage]] = {
    MeshOp.LAYOUT_BEGIN: MeshLayoutBegin,
    MeshOp.LAYOUT_CHUNK: MeshLayoutChunk,
    MeshOp.LAYOUT_COMMIT: MeshLayoutCommit,
    MeshOp.LAYOUT_CANCEL: MeshLayoutCancel,
    MeshOp.LAYOUT_STATUS: MeshLayoutStatus,
    MeshOp.DELIVERY_STAGE: MeshDeliveryStage,
    MeshOp.DELIVERY_RESULT: MeshDeliveryResult,
    MeshOp.RESULT_ACK: MeshResultAck,
    MeshOp.CAPS_GET: MeshCapsGet,
    MeshOp.CAPS_STATUS: MeshCapsStatus,
    MeshOp.HEALTH_GET: MeshHealthGet,
    MeshOp.HEALTH_STATUS: MeshHealthStatus,
    MeshOp.ASSIGN_SET: MeshAssignSet,
    MeshOp.ASSIGN_DEL: MeshAssignDel,
    MeshOp.ASSIGN_STATUS: MeshAssignStatus,
    MeshOp.TAG_CMD: MeshTagCmd,
    MeshOp.IDENTIFY: MeshIdentify,
    MeshOp.TAG_SEEN: MeshTagSeen,
    MeshOp.TUNNEL_OPEN: MeshTunnelOpen,
    MeshOp.TUNNEL_DATA: MeshTunnelData,
    MeshOp.TUNNEL_CLOSE: MeshTunnelClose,
    MeshOp.DISCOVER: MeshDiscover,
    MeshOp.DISCOVERED: MeshDiscovered,
    MeshOp.CAPS2_STATUS: MeshCaps2Status,
    MeshOp.TUNNEL_UP: MeshTunnelUp,
}
LAYOUT_COMMANDS: dict[LayoutCmd, type[FixedMessage]] = {
    LayoutCmd.CLEAR: LayoutCmdClear,
    LayoutCmd.GLYPHS: LayoutCmdGlyphs,
    LayoutCmd.ICON: LayoutCmdIcon,
    LayoutCmd.LINE: LayoutCmdLine,
    LayoutCmd.RECT: LayoutCmdRect,
    LayoutCmd.PROGRESS: LayoutCmdProgress,
    LayoutCmd.QR: LayoutCmdQr,
}
CTRL_MESSAGES: dict[CtrlMsg, type[FixedMessage]] = {
    CtrlMsg.HELLO: CtrlHello,
    CtrlMsg.CHALLENGE: CtrlChallenge,
    CtrlMsg.AUTH: CtrlAuth,
    CtrlMsg.AUTH_OK: CtrlAuthOk,
    CtrlMsg.ERROR: CtrlError,
}
RECORD_MESSAGES: dict[RecordType, type[FixedMessage]] = {
    RecordType.FRAME_BEGIN: RecFrameBegin,
    RecordType.PLANE_DATA: RecPlaneData,
    RecordType.FRAME_END: RecFrameEnd,
    RecordType.FRAME_ABORT: RecFrameAbort,
    RecordType.CMD: RecCmd,
    RecordType.RESULT: RecResult,
    RecordType.PROGRESS: RecProgress,
}
PLAIN_MESSAGES: dict[PlainMsg, type[FixedMessage]] = {
    PlainMsg.CREDIT: PlainCredit,
}
