#!/usr/bin/env python3
"""Generate the hardware matrix page and the qualification report scaffolding.

- docs/hardware/matrix.md is regenerated from hardware/matrix.yaml,
  tools/targets.yaml and, when present, build/memory-report.json.
- docs/qualification/<board>.md is created from a template when missing and is
  never overwritten; only the block between the ``build-facts`` markers is
  refreshed from the memory report.

Usage::

    python tools/gen_hardware_docs.py [--report build/memory-report.json]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
MATRIX_YAML = REPO_ROOT / "hardware" / "matrix.yaml"
TARGETS_YAML = REPO_ROOT / "tools" / "targets.yaml"
REPORT_JSON = REPO_ROOT / "build" / "memory-report.json"
MATRIX_MD = REPO_ROOT / "docs" / "hardware" / "matrix.md"
QUALIFICATION_DIR = REPO_ROOT / "docs" / "qualification"

GROUPS = {"gateways": "gateway", "bridges": "bridge", "tags": "tag"}
BEGIN, END = "<!-- build-facts:begin (generated by tools/gen_hardware_docs.py) -->", "<!-- build-facts:end -->"
STATUS_DEFS = [
    ("documented", "hardware facts recorded, nothing built yet"),
    ("buildable", "secure firmware links within the exact memory geometry and meets the resource targets"),
    ("functional", "flashed and exercised on a physical sample"),
    ("qualified", "qualification report complete (power, endurance, faults)"),
    ("blocked", "cannot be supported; `blocked_reason` records the measured cause"),
]
# 0-based indexes into verification_items that only apply to battery e-paper tags
# (display, panel, battery, sleep current).
TAG_ONLY_ITEMS = {1, 2, 4, 6}


def _fmt(n: int | None) -> str:
    return "-" if n is None else f"{n:,}"


def load_inputs(report_path: Path) -> tuple[dict[str, Any], dict[str, Any], dict[str, Any] | None]:
    matrix = yaml.safe_load(MATRIX_YAML.read_text(encoding="utf-8"))
    targets = yaml.safe_load(TARGETS_YAML.read_text(encoding="utf-8"))
    report = json.loads(report_path.read_text(encoding="utf-8")) if report_path.is_file() else None
    return matrix, targets, report


def targets_for(board_id: str, targets: dict[str, Any]) -> list[tuple[str, dict[str, Any]]]:
    return [(name, t) for name, t in targets["targets"].items() if t.get("hardware") == board_id]


def panel_text(panel: dict[str, Any]) -> str:
    if panel.get("controller") in (None, "unverified"):
        return f"unverified (panel id {panel['id']})"
    res = "×".join(str(v) for v in panel.get("resolution", []))
    planes = "black/white" if panel.get("planes") == 1 else "black/white/red"
    checked = "verified" if panel.get("verified") else "not verified"
    return f"{panel['controller']} {panel.get('size_in', '?')} in {res} {planes} (id {panel['id']}, {checked})"


def build_rows(names: list[str], targets: dict[str, Any], report: dict[str, Any] | None) -> list[str]:
    rows = [
        "| Target | Built from | Flash used / region (B) | Headroom (min) | RAM used / region (B) | RAM free (min) | Stack check | Result | Built |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for name in names:
        t = targets["targets"][name]
        e = (report or {}).get("targets", {}).get(name)
        if e is None:
            rows.append(f"| {name} | not built yet | - | - | - | - | - | - | - |")
            continue
        mem, res, ver = e.get("memory") or {}, e.get("resources") or {}, e.get("verify") or {}
        app = f"`{e.get('app')}`" + ("" if e.get("app") == t["app"] else " (board-check app, not the product firmware)")
        headroom = f"{res['flash_headroom_pct']:.1f} % ({res['flash_headroom_pct_min']:g} %)" if res else "-"
        ram_min = res.get("ram_free_min")
        ram = f"{_fmt(res.get('ram_free'))} ({_fmt(ram_min) if ram_min is not None else 'none'})" if res else "-"
        stack = "-" if not ver else (f"pass ({ver['dt_method']})" if ver["ok"] else "FAIL: " + ", ".join(ver["failed"]))
        rows.append(
            f"| {name} | {app} | {_fmt(mem.get('flash_used'))} / {_fmt(mem.get('flash_region'))} | {headroom} "
            f"| {_fmt(mem.get('ram_used'))} / {_fmt(mem.get('ram_region'))} | {ram} | {stack} "
            f"| {e.get('status', '-')} | {str(e.get('built_at', '-'))[:10]} |"
        )
    return rows


def render_matrix(matrix: dict[str, Any], targets: dict[str, Any], report: dict[str, Any] | None) -> str:
    out = [
        "# Hardware support matrix",
        "",
        "<!-- Generated by tools/gen_hardware_docs.py from hardware/matrix.yaml; edit the YAML, not this file. -->",
        "",
        "Every board moves through these states; qualification reports in",
        "[`docs/qualification/`](../qualification/) hold the evidence.",
        "",
        "| Status | Meaning |",
        "|---|---|",
        *[f"| {s} | {d} |" for s, d in STATUS_DEFS],
        "",
        "## Gateways",
        "",
        "| Board | Board id | Zephyr board | MCU | Flash / RAM | Host link | Status | Notes |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for g in matrix["gateways"]:
        out.append(
            f"| [{g['id']}](../qualification/{g['id']}.md) | {g['board_id']} | `{g['zephyr_board']}` | {g['mcu']} "
            f"| {g['flash_kib']} / {g['ram_kib']} KiB | {g['host_link']} | {g['status']} | {g.get('notes', '')} |"
        )
    out += [
        "",
        "## Bridges",
        "",
        "| Board | Board id | Zephyr board | MCU | Flash / RAM | External flash | Maintenance link | Status | Notes |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for b in matrix["bridges"]:
        out.append(
            f"| [{b['id']}](../qualification/{b['id']}.md) | {b['board_id']} | `{b['zephyr_board']}` | {b['mcu']} "
            f"| {b['flash_kib']} / {b['ram_kib']} KiB | {b['external_flash']} | {b['maintenance_link']} "
            f"| {b['status']} | {b.get('notes', '')} |"
        )
    out += [
        "",
        "## Tags",
        "",
        "| Board | Board id | Name | Zephyr board | MCU | Flash / RAM | Panel | Status | Notes |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for t in matrix["tags"]:
        out.append(
            f"| [{t['id']}](../qualification/{t['id']}.md) | {t['board_id']} | {t['name']} | `{t['zephyr_board']}` "
            f"| {t['mcu']} {t['soc_variant']} | {t['flash_kib']} / {t['ram_kib']} KiB | {panel_text(t['panel'])} "
            f"| {t['status']} | {t.get('notes', '')} |"
        )
    # en (panel supply switch) is optional: boards without one show "-".
    pin_names = ["mosi", "sck", "cs", "dc", "reset", "busy", "bs", "wake", "debug_tx", "en"]
    out += [
        "",
        "### Tag pins (port 0, decimal)",
        "",
        "Board files: [`boards/cremind/`](../../boards/cremind/). Unverified boards use placeholder",
        "pins in their devicetree and panel id 255, which firmware refuses to drive.",
        "",
        "| Board | " + " | ".join(p.upper().replace("_", " ") for p in pin_names) + " | LEDs | 32.768 kHz |",
        "|---|" + "---|" * (len(pin_names) + 2),
    ]
    for t in matrix["tags"]:
        pins = t["pins"]
        cells = ([str(pins[p]) if p != "en" else str(pins.get(p, "-")) for p in pin_names]
                 if isinstance(pins, dict) else ["unverified"] * len(pin_names))
        leds = ", ".join(str(n) for n in t["leds"]) if isinstance(t.get("leds"), list) else str(t.get("leds", "-"))
        out.append(f"| {t['id']} | " + " | ".join(cells) + f" | {leds} | {t.get('oscillator_32k', 'unverified')} |")

    rt = matrix["resource_targets"]
    out += [
        "",
        "## Build targets",
        "",
        "From [`tools/targets.yaml`](../../tools/targets.yaml); build with `python tools/build.py <target>`",
        f"([building](../building.md)). Every target must keep {rt['flash_headroom_pct']} % of its FLASH region free.",
        "",
        "| Target | App | Zephyr board | SoC | Snippets | RAM free min (B) | Hardware |",
        "|---|---|---|---|---|---|---|",
    ]
    for name, t in targets["targets"].items():
        ram = (t.get("resources") or {}).get("ram_free_min")
        out.append(
            f"| {name} | `{t['app']}` | `{t['board']}` | {t['soc']} | {', '.join(t['snippets']) or '-'} "
            f"| {_fmt(ram) if ram is not None else 'none yet'} | {t.get('hardware') or 'development only'} |"
        )
    out += ["", "## Latest build facts", ""]
    if report is None:
        out.append("No `build/memory-report.json` yet: run `python tools/build.py --all`.")
    else:
        out += [f"From `build/memory-report.json` generated {report['generated']} (NCS {report['ncs']}).", ""]
        out += build_rows(list(targets["targets"]), targets, report)
    out += [
        "",
        "## Verification checklist",
        "",
        "Every physical sample is checked against these items before it can become",
        "*functional*; [verification.md](verification.md) explains how.",
        "",
        *[f"{i}. {item}" for i, item in enumerate(matrix["verification_items"], 1)],
        "",
    ]
    return "\n".join(out)


def build_facts_block(board: dict[str, Any], targets: dict[str, Any], report: dict[str, Any] | None) -> str:
    names = [n for n, _ in targets_for(board["id"], targets)]
    lines = [BEGIN, ""]
    if not names:
        lines.append("No build target maps to this board in `tools/targets.yaml`.")
    else:
        lines += build_rows(names, targets, report)
    lines += ["", END]
    return "\n".join(lines)


def render_qualification(
    group: str, board: dict[str, Any], matrix: dict[str, Any], targets: dict[str, Any], block: str
) -> str:
    role = GROUPS[group]
    app = {"gateway": "apps/gateway", "bridge": "apps/bridge", "tag": "apps/tag"}[role]
    names = [n for n, _ in targets_for(board["id"], targets)]
    title = board.get("name") or f"{board['mcu']} {role}"
    identity = [
        ("Board id (protocol/spec.yaml `boards`)", str(board["board_id"])),
        ("Zephyr board", f"`{board['zephyr_board']}`"),
        ("Build target(s)", ", ".join(f"`{n}`" for n in names) or "-"),
        (
            "MCU",
            f"{board['mcu']} {board.get('soc_variant', '')}".strip()
            + f" ({board['flash_kib']} KiB flash / {board['ram_kib']} KiB RAM)",
        ),
    ]
    if role == "tag":
        identity.append(("Panel", panel_text(board["panel"])))
        identity.append(("32.768 kHz source", board.get("oscillator_32k", "unverified")))
    else:
        key = "host_link" if role == "gateway" else "maintenance_link"
        identity.append(("Serial link", board[key]))
        if role == "bridge":
            identity.append(("External flash", board["external_flash"]))
    identity += [
        ("Sample(s)", "_serial number / marking / source / date received_"),
        ("Firmware under test", "_`git describe` of the qualified build_"),
        ("PSA crypto provider", "_Oberon or TF-PSA-Crypto (firmware-notes correction 7)_"),
    ]
    checklist = ["| # | Item | Applies | Result | Evidence | Date |", "|---|---|---|---|---|---|"]
    for i, item in enumerate(matrix["verification_items"]):
        applies = role == "tag" or i not in TAG_ONLY_ITEMS
        checklist.append(
            f"| {i + 1} | {item} | {'yes' if applies else 'n/a'} | {'_pending_' if applies else '-'} | | |"
        )

    if role == "tag":
        functional = [
            (
                "Enrollment",
                "Write the enrollment blob (`cremind tags tools tag enroll`); read back UICR",
                "Tag advertises; missing/bad CRC → no advertising, SECURITY_CONFIG",
            ),
            (
                "Advertising cadence",
                "Sniff for 10 min",
                "Window every 30 s ± 3 s, 2 s long, 250 ms interval, legacy 1M",
            ),
            (
                "Handshake",
                "Bridge session with the current epoch; then a wrong key",
                "AUTH_OK; wrong key → AUTH_FAILED, 3 failures skip a window",
            ),
            (
                "Frame transfer + refresh",
                "Deliver a test layout per plane count",
                "RESULT OK; image correct in every plane; refresh_ms recorded",
            ),
            ("Duplicate revision", "Re-deliver the displayed revision", "Stored ACK with duplicate flag, no refresh"),
            (
                "Reset during refresh",
                "Reset while BUSY is active",
                "DISPLAY_STATE_UNKNOWN reported, re-delivery recovers",
            ),
            (
                "CMD CLEAR / SLEEP",
                "Send both commands",
                "White screen persisted; SLEEP only if wake verified, else UNSUPPORTED",
            ),
            ("Low battery", "Lower the supply to the threshold", "Low-battery flag in advertising and CHALLENGE"),
        ]
        power = [
            "Idle between windows (System ON, RTC, LFRC calibration)",
            "Advertising window",
            "Connected transfer",
            "Panel refresh (peak and duration)",
            "System OFF (only with verified wake)",
            "Estimated battery life",
        ]
        endurance = [
            "≥ 1000 refresh cycles",
            "≥ 10 000 sessions incl. failed authentications",
            "NVS wear: two writes per update",
            "Temperature range of the deployment",
        ]
        faults = [
            "Power loss during transfer",
            "Power loss during refresh (REFRESH_INTENT recovery)",
            "Power loss during NVS write",
            "BUSY stuck (REFRESH_TIMEOUT)",
            "Corrupted storage partition",
            "Brown-out at end of battery life",
        ]
    else:
        functional = [
            (
                "Serial link",
                "Companion connects over the documented link",
                "Framing, credits and idempotency per docs/protocol.md section 1",
            ),
            ("Mesh", "Provision and configure; power-cycle", "Network restored from settings"),
            (
                "Layout delivery",
                "Deliver layouts to a tag through the mesh",
                "Stages reported in order; RESULT returned",
            ),
        ]
        if role == "bridge":
            functional += [
                (
                    "Suspend window",
                    "Connect to a tag while relaying mesh traffic",
                    "suspend_ms recorded; mesh resumes; no resume failure",
                ),
                (
                    "Font pack",
                    "Install and switch slots over the maintenance port",
                    "Slot switch atomic; capacity rule met",
                ),
            ]
        power = ["Idle (scanning)", "Peak during transfer / provisioning"]
        endurance = ["72 h continuous operation", "≥ 1000 deliveries", "Settings/flash wear over the test"]
        faults = [
            "Power loss during provisioning / settings write",
            "Serial link unplug and replug",
            "Mesh resume failure recovery (bridge)",
        ]

    status_line = board["status"]
    today = datetime.now(timezone.utc).date().isoformat()
    lines = [
        f"# Qualification report: {title} (`{board['id']}`)",
        "",
        f"Status: **{status_line}** ([status definitions](../hardware/matrix.md))",
        "",
        f"> **TODO:** the {role} application (`{app}`) is not built yet. The board stays",
        "> *documented* until the secure application links within this board's exact",
        "> memory geometry and meets the resource targets (*buildable*).",
        "",
        "## 1. Identity",
        "",
        "| Field | Value |",
        "|---|---|",
        *[f"| {k} | {v} |" for k, v in identity],
        "",
        "## 2. Hardware verification checklist",
        "",
        "How to check each item: [verification.md](../hardware/verification.md).",
        "",
        *checklist,
        "",
        "## 3. Build facts",
        "",
        "Refreshed from `build/memory-report.json` by `tools/gen_hardware_docs.py`.",
        "",
        block,
        "",
        "## 4. Functional tests",
        "",
        "| Test | Procedure | Expected | Result |",
        "|---|---|---|---|",
        *[f"| {a} | {b} | {c} | _pending_ |" for a, b, c in functional],
        "",
        "## 5. Power",
        "",
        "Measure with development equipment disconnected, after a power-on reset.",
        "",
        "| State | Condition | Measured | Equipment | Notes |",
        "|---|---|---|---|---|",
        *[f"| {s} | | _pending_ | | |" for s in power],
        "",
        "## 6. Endurance",
        "",
        "| Test | Result |",
        "|---|---|",
        *[f"| {e} | _pending_ |" for e in endurance],
        "",
        "## 7. Faults",
        "",
        "| Injected fault | Expected behaviour | Result |",
        "|---|---|---|",
        *[f"| {f} | | _pending_ |" for f in faults],
        "",
        "## 8. Status history",
        "",
        "| Date | Status | Evidence / change |",
        "|---|---|---|",
        f"| {today} | {status_line} | Hardware facts recorded in `hardware/matrix.yaml`. |",
    ]
    if role == "tag":
        lines.append(
            f"| {today} | {status_line} | Board definition `boards/cremind/{board['id']}` configures, "
            "links and passes `verify_stack.py` with a board-check app (not the tag app). |"
        )
    return "\n".join(lines) + "\n"


def refresh_block(text: str, block: str) -> str:
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    if not pattern.search(text):
        return text
    return pattern.sub(lambda _: block, text)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--report", type=Path, default=REPORT_JSON, help="memory report written by tools/build.py")
    args = parser.parse_args(argv)
    matrix, targets, report = load_inputs(args.report)

    MATRIX_MD.parent.mkdir(parents=True, exist_ok=True)
    MATRIX_MD.write_text(render_matrix(matrix, targets, report), encoding="utf-8", newline="\n")
    print(f"wrote {MATRIX_MD.relative_to(REPO_ROOT).as_posix()}")

    QUALIFICATION_DIR.mkdir(parents=True, exist_ok=True)
    for group in GROUPS:
        for board in matrix[group]:
            path = QUALIFICATION_DIR / f"{board['id']}.md"
            block = build_facts_block(board, targets, report)
            if path.is_file():
                old = path.read_text(encoding="utf-8")
                new = refresh_block(old, block)
                if new != old:
                    path.write_text(new, encoding="utf-8", newline="\n")
                    print(f"refreshed build facts in {path.relative_to(REPO_ROOT).as_posix()}")
            else:
                path.write_text(
                    render_qualification(group, board, matrix, targets, block), encoding="utf-8", newline="\n"
                )
                print(f"created {path.relative_to(REPO_ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
