/*
 * DO NOT EDIT: generated by tools/codegen.py from protocol/spec.yaml.
 * spec sha256: c3147b872e74569886bb287261515d5d4a9d9b431f8f86f347113d90cc97c7b8
 *
 * Fixed-layout protocol messages: one plain struct (natural alignment, not packed)
 * per message plus static inline little-endian codecs.
 *
 * - Layouts exclude the type/opcode byte (mesh opcode, GATT message type,
 *   layout op); the caller frames it.
 * - ctag_<msg>_pack(m, buf, size) returns the bytes written, -EMSGSIZE when buf
 *   is too small or a trailing field exceeds its max, -EINVAL for a NULL
 *   trailing pointer with a non-zero length.
 * - ctag_<msg>_unpack(m, buf, len) returns 0, -EINVAL when len is short, or
 *   -EMSGSIZE when len is long (fixed messages must match exactly). A trailing
 *   bytes field points into buf (zero copy). Messages followed by a variable
 *   part (GLYPHS glyphs, QR text) decode the fixed part and accept any longer
 *   len.
 * - Messages without fields have only a _LEN macro (0).
 */
#ifndef CTAG_PROTO_MSGS_H_
#define CTAG_PROTO_MSGS_H_

#include <errno.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

#include "proto_ids.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Little-endian accessors: byte by byte, no unaligned access, no host-endian
 * assumption, no implementation-defined signed conversions. */
static inline void ctag_put_le16(uint8_t *p, uint16_t v)
{
	p[0] = (uint8_t)v;
	p[1] = (uint8_t)(v >> 8);
}

static inline void ctag_put_le32(uint8_t *p, uint32_t v)
{
	p[0] = (uint8_t)v;
	p[1] = (uint8_t)(v >> 8);
	p[2] = (uint8_t)(v >> 16);
	p[3] = (uint8_t)(v >> 24);
}

static inline void ctag_put_le64(uint8_t *p, uint64_t v)
{
	ctag_put_le32(p, (uint32_t)v);
	ctag_put_le32(p + 4, (uint32_t)(v >> 32));
}

static inline uint16_t ctag_get_le16(const uint8_t *p)
{
	return (uint16_t)((uint16_t)p[0] | (uint16_t)((uint16_t)p[1] << 8));
}

static inline uint32_t ctag_get_le32(const uint8_t *p)
{
	return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) |
	       ((uint32_t)p[3] << 24);
}

static inline uint64_t ctag_get_le64(const uint8_t *p)
{
	return (uint64_t)ctag_get_le32(p) | ((uint64_t)ctag_get_le32(p + 4) << 32);
}

static inline int8_t ctag_get_i8(const uint8_t *p)
{
	return p[0] < 0x80u ? (int8_t)p[0] : (int8_t)((int)p[0] - 256);
}

static inline int16_t ctag_get_le16s(const uint8_t *p)
{
	uint16_t u = ctag_get_le16(p);

	return u < 0x8000u ? (int16_t)u : (int16_t)((int32_t)u - 65536);
}

static inline int32_t ctag_get_le32s(const uint8_t *p)
{
	uint32_t u = ctag_get_le32(p);

	return u < 0x80000000u ? (int32_t)u : -(int32_t)(~u) - 1;
}

/* Serial frame header: 8 bytes. */
struct ctag_serial_header {
	uint8_t version; /* PROTO_VERSION */
	uint8_t type; /* Message type */
	uint16_t request_id; /* Echoed in responses; 0 for events */
	uint16_t length; /* Payload length */
	uint8_t flags; /* serial.flags bits */
	uint8_t credits; /* Incremental credit grant: extra frames the SENDER of this frame can now receive */
};

static inline int ctag_serial_header_pack(const struct ctag_serial_header *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_SERIAL_HEADER_LEN) {
		return -EMSGSIZE;
	}
	buf[0] = m->version;
	buf[1] = m->type;
	ctag_put_le16(&buf[2], m->request_id);
	ctag_put_le16(&buf[4], m->length);
	buf[6] = m->flags;
	buf[7] = m->credits;
	return CTAG_SERIAL_HEADER_LEN;
}

static inline int ctag_serial_header_unpack(struct ctag_serial_header *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_SERIAL_HEADER_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_SERIAL_HEADER_LEN) {
		return -EMSGSIZE;
	}
	m->version = buf[0];
	m->type = buf[1];
	m->request_id = ctag_get_le16(&buf[2]);
	m->length = ctag_get_le16(&buf[4]);
	m->flags = buf[6];
	m->credits = buf[7];
	return 0;
}

/* Mesh LAYOUT_BEGIN parameters (opcode 0x01, handled by LAYOUT_SRV): 49 bytes. */
#define CTAG_MESH_LAYOUT_BEGIN_LEN 49
struct ctag_mesh_layout_begin {
	uint16_t xfer_id;
	uint32_t tag_id;
	uint32_t epoch;
	uint32_t revision;
	uint64_t update_id;
	uint8_t fontpack_id[8];
	uint16_t total_len;
	uint8_t chunk_count;
	uint8_t digest[16];
};

static inline int ctag_mesh_layout_begin_pack(const struct ctag_mesh_layout_begin *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_MESH_LAYOUT_BEGIN_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le16(&buf[0], m->xfer_id);
	ctag_put_le32(&buf[2], m->tag_id);
	ctag_put_le32(&buf[6], m->epoch);
	ctag_put_le32(&buf[10], m->revision);
	ctag_put_le64(&buf[14], m->update_id);
	memcpy(&buf[22], m->fontpack_id, 8);
	ctag_put_le16(&buf[30], m->total_len);
	buf[32] = m->chunk_count;
	memcpy(&buf[33], m->digest, 16);
	return CTAG_MESH_LAYOUT_BEGIN_LEN;
}

static inline int ctag_mesh_layout_begin_unpack(struct ctag_mesh_layout_begin *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_MESH_LAYOUT_BEGIN_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_MESH_LAYOUT_BEGIN_LEN) {
		return -EMSGSIZE;
	}
	m->xfer_id = ctag_get_le16(&buf[0]);
	m->tag_id = ctag_get_le32(&buf[2]);
	m->epoch = ctag_get_le32(&buf[6]);
	m->revision = ctag_get_le32(&buf[10]);
	m->update_id = ctag_get_le64(&buf[14]);
	memcpy(m->fontpack_id, &buf[22], 8);
	m->total_len = ctag_get_le16(&buf[30]);
	m->chunk_count = buf[32];
	memcpy(m->digest, &buf[33], 16);
	return 0;
}

/* Mesh LAYOUT_CHUNK parameters (opcode 0x02, handled by LAYOUT_SRV): 3 bytes + data (<= CTAG_LAYOUT_CHUNK_DATA_MAX). */
#define CTAG_MESH_LAYOUT_CHUNK_LEN 3
#define CTAG_MESH_LAYOUT_CHUNK_MAX_LEN (CTAG_MESH_LAYOUT_CHUNK_LEN + CTAG_LAYOUT_CHUNK_DATA_MAX)
struct ctag_mesh_layout_chunk {
	uint16_t xfer_id;
	uint8_t index;
	const uint8_t *data; /* Every chunk but the last is exactly 150 bytes */
	size_t data_len;
};

static inline int ctag_mesh_layout_chunk_pack(const struct ctag_mesh_layout_chunk *m, uint8_t *buf, size_t size)
{
	if (m->data_len > CTAG_LAYOUT_CHUNK_DATA_MAX) {
		return -EMSGSIZE;
	}
	if (m->data_len > 0u && m->data == NULL) {
		return -EINVAL;
	}
	if (size < CTAG_MESH_LAYOUT_CHUNK_LEN + m->data_len) {
		return -EMSGSIZE;
	}
	ctag_put_le16(&buf[0], m->xfer_id);
	buf[2] = m->index;
	if (m->data_len > 0u) {
		memcpy(&buf[3], m->data, m->data_len);
	}
	return (int)(CTAG_MESH_LAYOUT_CHUNK_LEN + m->data_len);
}

static inline int ctag_mesh_layout_chunk_unpack(struct ctag_mesh_layout_chunk *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_MESH_LAYOUT_CHUNK_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_MESH_LAYOUT_CHUNK_MAX_LEN) {
		return -EMSGSIZE;
	}
	m->xfer_id = ctag_get_le16(&buf[0]);
	m->index = buf[2];
	m->data = &buf[3];
	m->data_len = len - CTAG_MESH_LAYOUT_CHUNK_LEN;
	return 0;
}

/* Mesh LAYOUT_COMMIT parameters (opcode 0x03, handled by LAYOUT_SRV): 2 bytes. */
#define CTAG_MESH_LAYOUT_COMMIT_LEN 2
struct ctag_mesh_layout_commit {
	uint16_t xfer_id;
};

static inline int ctag_mesh_layout_commit_pack(const struct ctag_mesh_layout_commit *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_MESH_LAYOUT_COMMIT_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le16(&buf[0], m->xfer_id);
	return CTAG_MESH_LAYOUT_COMMIT_LEN;
}

static inline int ctag_mesh_layout_commit_unpack(struct ctag_mesh_layout_commit *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_MESH_LAYOUT_COMMIT_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_MESH_LAYOUT_COMMIT_LEN) {
		return -EMSGSIZE;
	}
	m->xfer_id = ctag_get_le16(&buf[0]);
	return 0;
}

/* Mesh LAYOUT_CANCEL parameters (opcode 0x04, handled by LAYOUT_SRV): 8 bytes. */
#define CTAG_MESH_LAYOUT_CANCEL_LEN 8
struct ctag_mesh_layout_cancel {
	uint64_t update_id;
};

static inline int ctag_mesh_layout_cancel_pack(const struct ctag_mesh_layout_cancel *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_MESH_LAYOUT_CANCEL_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le64(&buf[0], m->update_id);
	return CTAG_MESH_LAYOUT_CANCEL_LEN;
}

static inline int ctag_mesh_layout_cancel_unpack(struct ctag_mesh_layout_cancel *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_MESH_LAYOUT_CANCEL_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_MESH_LAYOUT_CANCEL_LEN) {
		return -EMSGSIZE;
	}
	m->update_id = ctag_get_le64(&buf[0]);
	return 0;
}

/* Mesh LAYOUT_STATUS parameters (opcode 0x05, handled by LAYOUT_CLI): 7 bytes. */
#define CTAG_MESH_LAYOUT_STATUS_LEN 7
struct ctag_mesh_layout_status {
	uint16_t xfer_id;
	uint8_t status;
	uint32_t missing; /* Bit i set = chunk i missing (valid with INCOMPLETE) */
};

static inline int ctag_mesh_layout_status_pack(const struct ctag_mesh_layout_status *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_MESH_LAYOUT_STATUS_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le16(&buf[0], m->xfer_id);
	buf[2] = m->status;
	ctag_put_le32(&buf[3], m->missing);
	return CTAG_MESH_LAYOUT_STATUS_LEN;
}

static inline int ctag_mesh_layout_status_unpack(struct ctag_mesh_layout_status *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_MESH_LAYOUT_STATUS_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_MESH_LAYOUT_STATUS_LEN) {
		return -EMSGSIZE;
	}
	m->xfer_id = ctag_get_le16(&buf[0]);
	m->status = buf[2];
	m->missing = ctag_get_le32(&buf[3]);
	return 0;
}

/* Mesh DELIVERY_STAGE parameters (opcode 0x06, handled by LAYOUT_CLI): 17 bytes. */
#define CTAG_MESH_DELIVERY_STAGE_LEN 17
struct ctag_mesh_delivery_stage {
	uint64_t update_id;
	uint32_t tag_id;
	uint32_t revision;
	uint8_t stage;
};

static inline int ctag_mesh_delivery_stage_pack(const struct ctag_mesh_delivery_stage *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_MESH_DELIVERY_STAGE_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le64(&buf[0], m->update_id);
	ctag_put_le32(&buf[8], m->tag_id);
	ctag_put_le32(&buf[12], m->revision);
	buf[16] = m->stage;
	return CTAG_MESH_DELIVERY_STAGE_LEN;
}

static inline int ctag_mesh_delivery_stage_unpack(struct ctag_mesh_delivery_stage *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_MESH_DELIVERY_STAGE_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_MESH_DELIVERY_STAGE_LEN) {
		return -EMSGSIZE;
	}
	m->update_id = ctag_get_le64(&buf[0]);
	m->tag_id = ctag_get_le32(&buf[8]);
	m->revision = ctag_get_le32(&buf[12]);
	m->stage = buf[16];
	return 0;
}

/* Mesh DELIVERY_RESULT parameters (opcode 0x07, handled by LAYOUT_CLI): 46 bytes. */
#define CTAG_MESH_DELIVERY_RESULT_LEN 46
struct ctag_mesh_delivery_result {
	uint16_t result_seq; /* Bridge-local sequence, echoed by RESULT_ACK */
	uint64_t update_id;
	uint32_t tag_id;
	uint32_t epoch;
	uint32_t revision;
	uint8_t status;
	uint8_t digest[8]; /* First 8 bytes of the frame digest (zeros if none) */
	uint16_t battery_mv;
	uint16_t wake_ms; /* Layout validated -> tag connected */
	uint16_t suspend_ms; /* Mesh suspended duration for the connection attempt */
	uint16_t transfer_ms;
	uint16_t refresh_ms;
	uint32_t stored_epoch; /* The tag's stored epoch as its ERROR or CHALLENGE reported it (after AUTH_OK at least the session's epoch); 0 = unknown (no session produced this result) */
	uint8_t flags; /* bit0 the tag re-sent its stored ACK (RESULT.flags.bit0, duplicate); bit1 an unauthenticated status escalated after 3 consecutive refusals (protocol.md 10) */
};

static inline int ctag_mesh_delivery_result_pack(const struct ctag_mesh_delivery_result *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_MESH_DELIVERY_RESULT_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le16(&buf[0], m->result_seq);
	ctag_put_le64(&buf[2], m->update_id);
	ctag_put_le32(&buf[10], m->tag_id);
	ctag_put_le32(&buf[14], m->epoch);
	ctag_put_le32(&buf[18], m->revision);
	buf[22] = m->status;
	memcpy(&buf[23], m->digest, 8);
	ctag_put_le16(&buf[31], m->battery_mv);
	ctag_put_le16(&buf[33], m->wake_ms);
	ctag_put_le16(&buf[35], m->suspend_ms);
	ctag_put_le16(&buf[37], m->transfer_ms);
	ctag_put_le16(&buf[39], m->refresh_ms);
	ctag_put_le32(&buf[41], m->stored_epoch);
	buf[45] = m->flags;
	return CTAG_MESH_DELIVERY_RESULT_LEN;
}

static inline int ctag_mesh_delivery_result_unpack(struct ctag_mesh_delivery_result *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_MESH_DELIVERY_RESULT_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_MESH_DELIVERY_RESULT_LEN) {
		return -EMSGSIZE;
	}
	m->result_seq = ctag_get_le16(&buf[0]);
	m->update_id = ctag_get_le64(&buf[2]);
	m->tag_id = ctag_get_le32(&buf[10]);
	m->epoch = ctag_get_le32(&buf[14]);
	m->revision = ctag_get_le32(&buf[18]);
	m->status = buf[22];
	memcpy(m->digest, &buf[23], 8);
	m->battery_mv = ctag_get_le16(&buf[31]);
	m->wake_ms = ctag_get_le16(&buf[33]);
	m->suspend_ms = ctag_get_le16(&buf[35]);
	m->transfer_ms = ctag_get_le16(&buf[37]);
	m->refresh_ms = ctag_get_le16(&buf[39]);
	m->stored_epoch = ctag_get_le32(&buf[41]);
	m->flags = buf[45];
	return 0;
}

/* Mesh RESULT_ACK parameters (opcode 0x08, handled by LAYOUT_SRV): 2 bytes. */
#define CTAG_MESH_RESULT_ACK_LEN 2
struct ctag_mesh_result_ack {
	uint16_t result_seq;
};

static inline int ctag_mesh_result_ack_pack(const struct ctag_mesh_result_ack *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_MESH_RESULT_ACK_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le16(&buf[0], m->result_seq);
	return CTAG_MESH_RESULT_ACK_LEN;
}

static inline int ctag_mesh_result_ack_unpack(struct ctag_mesh_result_ack *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_MESH_RESULT_ACK_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_MESH_RESULT_ACK_LEN) {
		return -EMSGSIZE;
	}
	m->result_seq = ctag_get_le16(&buf[0]);
	return 0;
}

/* Mesh CAPS_GET parameters (opcode 0x10, handled by MGMT_SRV): 0 bytes. */
#define CTAG_MESH_CAPS_GET_LEN 0

/* Mesh CAPS_STATUS parameters (opcode 0x11, handled by MGMT_CLI): 18 bytes. */
#define CTAG_MESH_CAPS_STATUS_LEN 18
struct ctag_mesh_caps_status {
	uint8_t proto;
	uint8_t fw_major;
	uint8_t fw_minor;
	uint8_t fw_patch;
	uint8_t board;
	uint8_t fontpack_id[8];
	uint16_t flash_mib;
	uint8_t max_tags;
	uint8_t assigned;
	uint8_t flags; /* bit0 font pack valid, bit1 busy with a tag session */
};

static inline int ctag_mesh_caps_status_pack(const struct ctag_mesh_caps_status *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_MESH_CAPS_STATUS_LEN) {
		return -EMSGSIZE;
	}
	buf[0] = m->proto;
	buf[1] = m->fw_major;
	buf[2] = m->fw_minor;
	buf[3] = m->fw_patch;
	buf[4] = m->board;
	memcpy(&buf[5], m->fontpack_id, 8);
	ctag_put_le16(&buf[13], m->flash_mib);
	buf[15] = m->max_tags;
	buf[16] = m->assigned;
	buf[17] = m->flags;
	return CTAG_MESH_CAPS_STATUS_LEN;
}

static inline int ctag_mesh_caps_status_unpack(struct ctag_mesh_caps_status *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_MESH_CAPS_STATUS_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_MESH_CAPS_STATUS_LEN) {
		return -EMSGSIZE;
	}
	m->proto = buf[0];
	m->fw_major = buf[1];
	m->fw_minor = buf[2];
	m->fw_patch = buf[3];
	m->board = buf[4];
	memcpy(m->fontpack_id, &buf[5], 8);
	m->flash_mib = ctag_get_le16(&buf[13]);
	m->max_tags = buf[15];
	m->assigned = buf[16];
	m->flags = buf[17];
	return 0;
}

/* Mesh HEALTH_GET parameters (opcode 0x12, handled by MGMT_SRV): 0 bytes. */
#define CTAG_MESH_HEALTH_GET_LEN 0

/* Mesh HEALTH_STATUS parameters (opcode 0x13, handled by MGMT_CLI): 16 bytes. */
#define CTAG_MESH_HEALTH_STATUS_LEN 16
struct ctag_mesh_health_status {
	uint32_t uptime_s;
	uint16_t sessions_ok;
	uint16_t sessions_fail;
	uint16_t suspend_count;
	uint16_t suspend_max_ms;
	uint16_t resume_fail;
	uint8_t queue_depth;
	uint8_t last_status;
};

static inline int ctag_mesh_health_status_pack(const struct ctag_mesh_health_status *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_MESH_HEALTH_STATUS_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le32(&buf[0], m->uptime_s);
	ctag_put_le16(&buf[4], m->sessions_ok);
	ctag_put_le16(&buf[6], m->sessions_fail);
	ctag_put_le16(&buf[8], m->suspend_count);
	ctag_put_le16(&buf[10], m->suspend_max_ms);
	ctag_put_le16(&buf[12], m->resume_fail);
	buf[14] = m->queue_depth;
	buf[15] = m->last_status;
	return CTAG_MESH_HEALTH_STATUS_LEN;
}

static inline int ctag_mesh_health_status_unpack(struct ctag_mesh_health_status *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_MESH_HEALTH_STATUS_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_MESH_HEALTH_STATUS_LEN) {
		return -EMSGSIZE;
	}
	m->uptime_s = ctag_get_le32(&buf[0]);
	m->sessions_ok = ctag_get_le16(&buf[4]);
	m->sessions_fail = ctag_get_le16(&buf[6]);
	m->suspend_count = ctag_get_le16(&buf[8]);
	m->suspend_max_ms = ctag_get_le16(&buf[10]);
	m->resume_fail = ctag_get_le16(&buf[12]);
	m->queue_depth = buf[14];
	m->last_status = buf[15];
	return 0;
}

/* Mesh ASSIGN_SET parameters (opcode 0x14, handled by MGMT_SRV): 25 bytes. */
#define CTAG_MESH_ASSIGN_SET_LEN 25
struct ctag_mesh_assign_set {
	uint32_t tag_id;
	uint32_t epoch;
	uint8_t key[16]; /* K_epoch for this (tag, epoch) */
	uint8_t flags; /* bit0 primary bridge */
};

static inline int ctag_mesh_assign_set_pack(const struct ctag_mesh_assign_set *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_MESH_ASSIGN_SET_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le32(&buf[0], m->tag_id);
	ctag_put_le32(&buf[4], m->epoch);
	memcpy(&buf[8], m->key, 16);
	buf[24] = m->flags;
	return CTAG_MESH_ASSIGN_SET_LEN;
}

static inline int ctag_mesh_assign_set_unpack(struct ctag_mesh_assign_set *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_MESH_ASSIGN_SET_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_MESH_ASSIGN_SET_LEN) {
		return -EMSGSIZE;
	}
	m->tag_id = ctag_get_le32(&buf[0]);
	m->epoch = ctag_get_le32(&buf[4]);
	memcpy(m->key, &buf[8], 16);
	m->flags = buf[24];
	return 0;
}

/* Mesh ASSIGN_DEL parameters (opcode 0x15, handled by MGMT_SRV): 8 bytes. */
#define CTAG_MESH_ASSIGN_DEL_LEN 8
struct ctag_mesh_assign_del {
	uint32_t tag_id;
	uint32_t epoch;
};

static inline int ctag_mesh_assign_del_pack(const struct ctag_mesh_assign_del *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_MESH_ASSIGN_DEL_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le32(&buf[0], m->tag_id);
	ctag_put_le32(&buf[4], m->epoch);
	return CTAG_MESH_ASSIGN_DEL_LEN;
}

static inline int ctag_mesh_assign_del_unpack(struct ctag_mesh_assign_del *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_MESH_ASSIGN_DEL_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_MESH_ASSIGN_DEL_LEN) {
		return -EMSGSIZE;
	}
	m->tag_id = ctag_get_le32(&buf[0]);
	m->epoch = ctag_get_le32(&buf[4]);
	return 0;
}

/* Mesh ASSIGN_STATUS parameters (opcode 0x16, handled by MGMT_CLI): 9 bytes. */
#define CTAG_MESH_ASSIGN_STATUS_LEN 9
struct ctag_mesh_assign_status {
	uint32_t tag_id;
	uint32_t epoch;
	uint8_t status;
};

static inline int ctag_mesh_assign_status_pack(const struct ctag_mesh_assign_status *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_MESH_ASSIGN_STATUS_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le32(&buf[0], m->tag_id);
	ctag_put_le32(&buf[4], m->epoch);
	buf[8] = m->status;
	return CTAG_MESH_ASSIGN_STATUS_LEN;
}

static inline int ctag_mesh_assign_status_unpack(struct ctag_mesh_assign_status *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_MESH_ASSIGN_STATUS_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_MESH_ASSIGN_STATUS_LEN) {
		return -EMSGSIZE;
	}
	m->tag_id = ctag_get_le32(&buf[0]);
	m->epoch = ctag_get_le32(&buf[4]);
	m->status = buf[8];
	return 0;
}

/* Mesh TAG_CMD parameters (opcode 0x17, handled by MGMT_SRV): 17 bytes. */
#define CTAG_MESH_TAG_CMD_LEN 17
struct ctag_mesh_tag_cmd {
	uint64_t update_id; /* Companion op id; results come back as DELIVERY_RESULT */
	uint32_t tag_id;
	uint32_t epoch;
	uint8_t cmd;
};

static inline int ctag_mesh_tag_cmd_pack(const struct ctag_mesh_tag_cmd *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_MESH_TAG_CMD_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le64(&buf[0], m->update_id);
	ctag_put_le32(&buf[8], m->tag_id);
	ctag_put_le32(&buf[12], m->epoch);
	buf[16] = m->cmd;
	return CTAG_MESH_TAG_CMD_LEN;
}

static inline int ctag_mesh_tag_cmd_unpack(struct ctag_mesh_tag_cmd *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_MESH_TAG_CMD_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_MESH_TAG_CMD_LEN) {
		return -EMSGSIZE;
	}
	m->update_id = ctag_get_le64(&buf[0]);
	m->tag_id = ctag_get_le32(&buf[8]);
	m->epoch = ctag_get_le32(&buf[12]);
	m->cmd = buf[16];
	return 0;
}

/* Mesh IDENTIFY parameters (opcode 0x18, handled by MGMT_SRV): 1 bytes. */
#define CTAG_MESH_IDENTIFY_LEN 1
struct ctag_mesh_identify {
	uint8_t seconds;
};

static inline int ctag_mesh_identify_pack(const struct ctag_mesh_identify *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_MESH_IDENTIFY_LEN) {
		return -EMSGSIZE;
	}
	buf[0] = m->seconds;
	return CTAG_MESH_IDENTIFY_LEN;
}

static inline int ctag_mesh_identify_unpack(struct ctag_mesh_identify *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_MESH_IDENTIFY_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_MESH_IDENTIFY_LEN) {
		return -EMSGSIZE;
	}
	m->seconds = buf[0];
	return 0;
}

/* Mesh TAG_SEEN parameters (opcode 0x19, handled by MGMT_CLI): 8 bytes. */
#define CTAG_MESH_TAG_SEEN_LEN 8
struct ctag_mesh_tag_seen {
	uint32_t tag_id;
	int8_t rssi;
	uint16_t battery_mv;
	uint8_t flags;
};

static inline int ctag_mesh_tag_seen_pack(const struct ctag_mesh_tag_seen *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_MESH_TAG_SEEN_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le32(&buf[0], m->tag_id);
	buf[4] = (uint8_t)m->rssi;
	ctag_put_le16(&buf[5], m->battery_mv);
	buf[7] = m->flags;
	return CTAG_MESH_TAG_SEEN_LEN;
}

static inline int ctag_mesh_tag_seen_unpack(struct ctag_mesh_tag_seen *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_MESH_TAG_SEEN_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_MESH_TAG_SEEN_LEN) {
		return -EMSGSIZE;
	}
	m->tag_id = ctag_get_le32(&buf[0]);
	m->rssi = ctag_get_i8(&buf[4]);
	m->battery_mv = ctag_get_le16(&buf[5]);
	m->flags = buf[7];
	return 0;
}

/* Layout header: 12 bytes. */
#define CTAG_LAYOUT_HEADER_LEN 12
struct ctag_layout_header {
	uint16_t magic;
	uint8_t version;
	uint8_t flags; /* bit0 uses red */
	uint16_t width; /* Logical (user-facing) width in px */
	uint16_t height; /* Logical height in px */
	uint8_t rotation; /* 0..3 = logical->native clockwise quarter turns */
	uint8_t background; /* colors */
	uint16_t cmd_count;
};

static inline int ctag_layout_header_pack(const struct ctag_layout_header *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_LAYOUT_HEADER_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le16(&buf[0], m->magic);
	buf[2] = m->version;
	buf[3] = m->flags;
	ctag_put_le16(&buf[4], m->width);
	ctag_put_le16(&buf[6], m->height);
	buf[8] = m->rotation;
	buf[9] = m->background;
	ctag_put_le16(&buf[10], m->cmd_count);
	return CTAG_LAYOUT_HEADER_LEN;
}

static inline int ctag_layout_header_unpack(struct ctag_layout_header *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_LAYOUT_HEADER_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_LAYOUT_HEADER_LEN) {
		return -EMSGSIZE;
	}
	m->magic = ctag_get_le16(&buf[0]);
	m->version = buf[2];
	m->flags = buf[3];
	m->width = ctag_get_le16(&buf[4]);
	m->height = ctag_get_le16(&buf[6]);
	m->rotation = buf[8];
	m->background = buf[9];
	m->cmd_count = ctag_get_le16(&buf[10]);
	return 0;
}

/* Layout command CLEAR (op 0x01), after the op byte: 1 bytes. */
#define CTAG_LAYOUT_CMD_CLEAR_LEN 1
struct ctag_layout_cmd_clear {
	uint8_t color;
};

static inline int ctag_layout_cmd_clear_pack(const struct ctag_layout_cmd_clear *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_LAYOUT_CMD_CLEAR_LEN) {
		return -EMSGSIZE;
	}
	buf[0] = m->color;
	return CTAG_LAYOUT_CMD_CLEAR_LEN;
}

static inline int ctag_layout_cmd_clear_unpack(struct ctag_layout_cmd_clear *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_LAYOUT_CMD_CLEAR_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_LAYOUT_CMD_CLEAR_LEN) {
		return -EMSGSIZE;
	}
	m->color = buf[0];
	return 0;
}

/* Layout command GLYPHS (op 0x02), after the op byte: 9 bytes; fixed part only, followed by glyph[count] (hand-written codec). */
#define CTAG_LAYOUT_CMD_GLYPHS_LEN 9
struct ctag_layout_cmd_glyphs {
	uint16_t face;
	uint8_t size_px;
	uint8_t color;
	int16_t origin_x;
	int16_t origin_y;
	uint8_t count;
};

static inline int ctag_layout_cmd_glyphs_pack(const struct ctag_layout_cmd_glyphs *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_LAYOUT_CMD_GLYPHS_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le16(&buf[0], m->face);
	buf[2] = m->size_px;
	buf[3] = m->color;
	ctag_put_le16(&buf[4], (uint16_t)m->origin_x);
	ctag_put_le16(&buf[6], (uint16_t)m->origin_y);
	buf[8] = m->count;
	return CTAG_LAYOUT_CMD_GLYPHS_LEN;
}

static inline int ctag_layout_cmd_glyphs_unpack(struct ctag_layout_cmd_glyphs *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_LAYOUT_CMD_GLYPHS_LEN) {
		return -EINVAL;
	}
	m->face = ctag_get_le16(&buf[0]);
	m->size_px = buf[2];
	m->color = buf[3];
	m->origin_x = ctag_get_le16s(&buf[4]);
	m->origin_y = ctag_get_le16s(&buf[6]);
	m->count = buf[8];
	return 0;
}

/* Layout command ICON (op 0x03), after the op byte: 8 bytes. */
#define CTAG_LAYOUT_CMD_ICON_LEN 8
struct ctag_layout_cmd_icon {
	uint16_t icon; /* icons[].id; drawn from face 0 (icon face) */
	uint8_t size_px;
	uint8_t color;
	int16_t x; /* top-left */
	int16_t y;
};

static inline int ctag_layout_cmd_icon_pack(const struct ctag_layout_cmd_icon *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_LAYOUT_CMD_ICON_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le16(&buf[0], m->icon);
	buf[2] = m->size_px;
	buf[3] = m->color;
	ctag_put_le16(&buf[4], (uint16_t)m->x);
	ctag_put_le16(&buf[6], (uint16_t)m->y);
	return CTAG_LAYOUT_CMD_ICON_LEN;
}

static inline int ctag_layout_cmd_icon_unpack(struct ctag_layout_cmd_icon *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_LAYOUT_CMD_ICON_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_LAYOUT_CMD_ICON_LEN) {
		return -EMSGSIZE;
	}
	m->icon = ctag_get_le16(&buf[0]);
	m->size_px = buf[2];
	m->color = buf[3];
	m->x = ctag_get_le16s(&buf[4]);
	m->y = ctag_get_le16s(&buf[6]);
	return 0;
}

/* Layout command LINE (op 0x04), after the op byte: 10 bytes. */
#define CTAG_LAYOUT_CMD_LINE_LEN 10
struct ctag_layout_cmd_line {
	int16_t x0;
	int16_t y0;
	int16_t x1;
	int16_t y1;
	uint8_t width; /* 1..8 px; square brush centred on the Bresenham path */
	uint8_t color;
};

static inline int ctag_layout_cmd_line_pack(const struct ctag_layout_cmd_line *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_LAYOUT_CMD_LINE_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le16(&buf[0], (uint16_t)m->x0);
	ctag_put_le16(&buf[2], (uint16_t)m->y0);
	ctag_put_le16(&buf[4], (uint16_t)m->x1);
	ctag_put_le16(&buf[6], (uint16_t)m->y1);
	buf[8] = m->width;
	buf[9] = m->color;
	return CTAG_LAYOUT_CMD_LINE_LEN;
}

static inline int ctag_layout_cmd_line_unpack(struct ctag_layout_cmd_line *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_LAYOUT_CMD_LINE_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_LAYOUT_CMD_LINE_LEN) {
		return -EMSGSIZE;
	}
	m->x0 = ctag_get_le16s(&buf[0]);
	m->y0 = ctag_get_le16s(&buf[2]);
	m->x1 = ctag_get_le16s(&buf[4]);
	m->y1 = ctag_get_le16s(&buf[6]);
	m->width = buf[8];
	m->color = buf[9];
	return 0;
}

/* Layout command RECT (op 0x05), after the op byte: 10 bytes. */
#define CTAG_LAYOUT_CMD_RECT_LEN 10
struct ctag_layout_cmd_rect {
	int16_t x;
	int16_t y;
	uint16_t w;
	uint16_t h;
	uint8_t border; /* 0 = filled, else outline thickness */
	uint8_t color;
};

static inline int ctag_layout_cmd_rect_pack(const struct ctag_layout_cmd_rect *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_LAYOUT_CMD_RECT_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le16(&buf[0], (uint16_t)m->x);
	ctag_put_le16(&buf[2], (uint16_t)m->y);
	ctag_put_le16(&buf[4], m->w);
	ctag_put_le16(&buf[6], m->h);
	buf[8] = m->border;
	buf[9] = m->color;
	return CTAG_LAYOUT_CMD_RECT_LEN;
}

static inline int ctag_layout_cmd_rect_unpack(struct ctag_layout_cmd_rect *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_LAYOUT_CMD_RECT_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_LAYOUT_CMD_RECT_LEN) {
		return -EMSGSIZE;
	}
	m->x = ctag_get_le16s(&buf[0]);
	m->y = ctag_get_le16s(&buf[2]);
	m->w = ctag_get_le16(&buf[4]);
	m->h = ctag_get_le16(&buf[6]);
	m->border = buf[8];
	m->color = buf[9];
	return 0;
}

/* Layout command PROGRESS (op 0x06), after the op byte: 13 bytes. */
#define CTAG_LAYOUT_CMD_PROGRESS_LEN 13
struct ctag_layout_cmd_progress {
	int16_t x;
	int16_t y;
	uint16_t w;
	uint16_t h;
	uint16_t value;
	uint16_t max;
	uint8_t color;
};

static inline int ctag_layout_cmd_progress_pack(const struct ctag_layout_cmd_progress *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_LAYOUT_CMD_PROGRESS_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le16(&buf[0], (uint16_t)m->x);
	ctag_put_le16(&buf[2], (uint16_t)m->y);
	ctag_put_le16(&buf[4], m->w);
	ctag_put_le16(&buf[6], m->h);
	ctag_put_le16(&buf[8], m->value);
	ctag_put_le16(&buf[10], m->max);
	buf[12] = m->color;
	return CTAG_LAYOUT_CMD_PROGRESS_LEN;
}

static inline int ctag_layout_cmd_progress_unpack(struct ctag_layout_cmd_progress *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_LAYOUT_CMD_PROGRESS_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_LAYOUT_CMD_PROGRESS_LEN) {
		return -EMSGSIZE;
	}
	m->x = ctag_get_le16s(&buf[0]);
	m->y = ctag_get_le16s(&buf[2]);
	m->w = ctag_get_le16(&buf[4]);
	m->h = ctag_get_le16(&buf[6]);
	m->value = ctag_get_le16(&buf[8]);
	m->max = ctag_get_le16(&buf[10]);
	m->color = buf[12];
	return 0;
}

/* Layout command QR (op 0x07), after the op byte: 8 bytes; fixed part only, followed by str[len] (hand-written codec). */
#define CTAG_LAYOUT_CMD_QR_LEN 8
struct ctag_layout_cmd_qr {
	int16_t x;
	int16_t y;
	uint8_t module_px; /* 1..8 */
	uint8_t ecc;
	uint8_t color;
	uint8_t len;
};

static inline int ctag_layout_cmd_qr_pack(const struct ctag_layout_cmd_qr *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_LAYOUT_CMD_QR_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le16(&buf[0], (uint16_t)m->x);
	ctag_put_le16(&buf[2], (uint16_t)m->y);
	buf[4] = m->module_px;
	buf[5] = m->ecc;
	buf[6] = m->color;
	buf[7] = m->len;
	return CTAG_LAYOUT_CMD_QR_LEN;
}

static inline int ctag_layout_cmd_qr_unpack(struct ctag_layout_cmd_qr *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_LAYOUT_CMD_QR_LEN) {
		return -EINVAL;
	}
	m->x = ctag_get_le16s(&buf[0]);
	m->y = ctag_get_le16s(&buf[2]);
	m->module_px = buf[4];
	m->ecc = buf[5];
	m->color = buf[6];
	m->len = buf[7];
	return 0;
}

/* One GLYPHS entry: 4 bytes. */
#define CTAG_LAYOUT_GLYPH_LEN 4
struct ctag_layout_glyph {
	uint16_t glyph_id;
	int8_t dx; /* Pen offset from the previous glyph origin (the first: from origin_x) */
	int8_t dy;
};

static inline int ctag_layout_glyph_pack(const struct ctag_layout_glyph *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_LAYOUT_GLYPH_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le16(&buf[0], m->glyph_id);
	buf[2] = (uint8_t)m->dx;
	buf[3] = (uint8_t)m->dy;
	return CTAG_LAYOUT_GLYPH_LEN;
}

static inline int ctag_layout_glyph_unpack(struct ctag_layout_glyph *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_LAYOUT_GLYPH_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_LAYOUT_GLYPH_LEN) {
		return -EMSGSIZE;
	}
	m->glyph_id = ctag_get_le16(&buf[0]);
	m->dx = ctag_get_i8(&buf[2]);
	m->dy = ctag_get_i8(&buf[3]);
	return 0;
}

/* Tag CAPS characteristic value: 18 bytes. */
#define CTAG_TAG_CAPS_LEN 18
struct ctag_tag_caps {
	uint8_t proto;
	uint32_t tag_id;
	uint8_t board;
	uint8_t panel;
	uint16_t width; /* Native panel width */
	uint16_t height; /* Native panel height */
	uint8_t planes; /* 1 = BW, 2 = BW + red */
	uint8_t plane_flags; /* bit0: plane0 bit 1 = white; bit1: plane1 bit 1 = red */
	uint8_t fw_major;
	uint8_t fw_minor;
	uint8_t fw_patch;
	uint8_t max_record; /* TAG_RECORD_PAYLOAD_MAX */
	uint8_t credits; /* Initial record credits after AUTH_OK */
};

static inline int ctag_tag_caps_pack(const struct ctag_tag_caps *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_TAG_CAPS_LEN) {
		return -EMSGSIZE;
	}
	buf[0] = m->proto;
	ctag_put_le32(&buf[1], m->tag_id);
	buf[5] = m->board;
	buf[6] = m->panel;
	ctag_put_le16(&buf[7], m->width);
	ctag_put_le16(&buf[9], m->height);
	buf[11] = m->planes;
	buf[12] = m->plane_flags;
	buf[13] = m->fw_major;
	buf[14] = m->fw_minor;
	buf[15] = m->fw_patch;
	buf[16] = m->max_record;
	buf[17] = m->credits;
	return CTAG_TAG_CAPS_LEN;
}

static inline int ctag_tag_caps_unpack(struct ctag_tag_caps *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_TAG_CAPS_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_TAG_CAPS_LEN) {
		return -EMSGSIZE;
	}
	m->proto = buf[0];
	m->tag_id = ctag_get_le32(&buf[1]);
	m->board = buf[5];
	m->panel = buf[6];
	m->width = ctag_get_le16(&buf[7]);
	m->height = ctag_get_le16(&buf[9]);
	m->planes = buf[11];
	m->plane_flags = buf[12];
	m->fw_major = buf[13];
	m->fw_minor = buf[14];
	m->fw_patch = buf[15];
	m->max_record = buf[16];
	m->credits = buf[17];
	return 0;
}

/* CTRL HELLO (type 0x01, b2t), after the type byte: 25 bytes. */
#define CTAG_CTRL_HELLO_LEN 25
struct ctag_ctrl_hello {
	uint8_t proto;
	uint32_t tag_id;
	uint32_t epoch;
	uint8_t nonce_b[16];
};

static inline int ctag_ctrl_hello_pack(const struct ctag_ctrl_hello *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_CTRL_HELLO_LEN) {
		return -EMSGSIZE;
	}
	buf[0] = m->proto;
	ctag_put_le32(&buf[1], m->tag_id);
	ctag_put_le32(&buf[5], m->epoch);
	memcpy(&buf[9], m->nonce_b, 16);
	return CTAG_CTRL_HELLO_LEN;
}

static inline int ctag_ctrl_hello_unpack(struct ctag_ctrl_hello *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_CTRL_HELLO_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_CTRL_HELLO_LEN) {
		return -EMSGSIZE;
	}
	m->proto = buf[0];
	m->tag_id = ctag_get_le32(&buf[1]);
	m->epoch = ctag_get_le32(&buf[5]);
	memcpy(m->nonce_b, &buf[9], 16);
	return 0;
}

/* CTRL CHALLENGE (type 0x02, t2b), after the type byte: 29 bytes. */
#define CTAG_CTRL_CHALLENGE_LEN 29
struct ctag_ctrl_challenge {
	uint8_t proto;
	uint8_t nonce_t[16];
	uint32_t stored_epoch;
	uint32_t displayed_rev;
	uint8_t last_status;
	uint16_t battery_mv;
	uint8_t flags; /* bit0 DISPLAY_STATE_UNKNOWN pending, bit1 low battery */
};

static inline int ctag_ctrl_challenge_pack(const struct ctag_ctrl_challenge *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_CTRL_CHALLENGE_LEN) {
		return -EMSGSIZE;
	}
	buf[0] = m->proto;
	memcpy(&buf[1], m->nonce_t, 16);
	ctag_put_le32(&buf[17], m->stored_epoch);
	ctag_put_le32(&buf[21], m->displayed_rev);
	buf[25] = m->last_status;
	ctag_put_le16(&buf[26], m->battery_mv);
	buf[28] = m->flags;
	return CTAG_CTRL_CHALLENGE_LEN;
}

static inline int ctag_ctrl_challenge_unpack(struct ctag_ctrl_challenge *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_CTRL_CHALLENGE_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_CTRL_CHALLENGE_LEN) {
		return -EMSGSIZE;
	}
	m->proto = buf[0];
	memcpy(m->nonce_t, &buf[1], 16);
	m->stored_epoch = ctag_get_le32(&buf[17]);
	m->displayed_rev = ctag_get_le32(&buf[21]);
	m->last_status = buf[25];
	m->battery_mv = ctag_get_le16(&buf[26]);
	m->flags = buf[28];
	return 0;
}

/* CTRL AUTH (type 0x03, b2t), after the type byte: 16 bytes. */
#define CTAG_CTRL_AUTH_LEN 16
struct ctag_ctrl_auth {
	uint8_t mac_b[16];
};

static inline int ctag_ctrl_auth_pack(const struct ctag_ctrl_auth *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_CTRL_AUTH_LEN) {
		return -EMSGSIZE;
	}
	memcpy(&buf[0], m->mac_b, 16);
	return CTAG_CTRL_AUTH_LEN;
}

static inline int ctag_ctrl_auth_unpack(struct ctag_ctrl_auth *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_CTRL_AUTH_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_CTRL_AUTH_LEN) {
		return -EMSGSIZE;
	}
	memcpy(m->mac_b, &buf[0], 16);
	return 0;
}

/* CTRL AUTH_OK (type 0x04, t2b), after the type byte: 16 bytes. */
#define CTAG_CTRL_AUTH_OK_LEN 16
struct ctag_ctrl_auth_ok {
	uint8_t mac_t[16];
};

static inline int ctag_ctrl_auth_ok_pack(const struct ctag_ctrl_auth_ok *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_CTRL_AUTH_OK_LEN) {
		return -EMSGSIZE;
	}
	memcpy(&buf[0], m->mac_t, 16);
	return CTAG_CTRL_AUTH_OK_LEN;
}

static inline int ctag_ctrl_auth_ok_unpack(struct ctag_ctrl_auth_ok *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_CTRL_AUTH_OK_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_CTRL_AUTH_OK_LEN) {
		return -EMSGSIZE;
	}
	memcpy(m->mac_t, &buf[0], 16);
	return 0;
}

/* CTRL ERROR (type 0x05, t2b), after the type byte: 5 bytes. */
#define CTAG_CTRL_ERROR_LEN 5
struct ctag_ctrl_error {
	uint8_t status;
	uint32_t stored_epoch; /* The tag's stored epoch, always filled (epochs are not secret); lets a bridge report how far a STALE_EPOCH refusal is behind */
};

static inline int ctag_ctrl_error_pack(const struct ctag_ctrl_error *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_CTRL_ERROR_LEN) {
		return -EMSGSIZE;
	}
	buf[0] = m->status;
	ctag_put_le32(&buf[1], m->stored_epoch);
	return CTAG_CTRL_ERROR_LEN;
}

static inline int ctag_ctrl_error_unpack(struct ctag_ctrl_error *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_CTRL_ERROR_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_CTRL_ERROR_LEN) {
		return -EMSGSIZE;
	}
	m->status = buf[0];
	m->stored_epoch = ctag_get_le32(&buf[1]);
	return 0;
}

/* Record FRAME_BEGIN plaintext (type 0x10, b2t): 47 bytes. */
#define CTAG_REC_FRAME_BEGIN_LEN 47
struct ctag_rec_frame_begin {
	uint32_t revision;
	uint64_t update_id;
	uint8_t digest[32]; /* Frame digest the tag must reproduce */
	uint8_t planes;
	uint16_t plane_len; /* Bytes per plane = ceil(width/8) * height */
};

static inline int ctag_rec_frame_begin_pack(const struct ctag_rec_frame_begin *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_REC_FRAME_BEGIN_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le32(&buf[0], m->revision);
	ctag_put_le64(&buf[4], m->update_id);
	memcpy(&buf[12], m->digest, 32);
	buf[44] = m->planes;
	ctag_put_le16(&buf[45], m->plane_len);
	return CTAG_REC_FRAME_BEGIN_LEN;
}

static inline int ctag_rec_frame_begin_unpack(struct ctag_rec_frame_begin *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_REC_FRAME_BEGIN_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_REC_FRAME_BEGIN_LEN) {
		return -EMSGSIZE;
	}
	m->revision = ctag_get_le32(&buf[0]);
	m->update_id = ctag_get_le64(&buf[4]);
	memcpy(m->digest, &buf[12], 32);
	m->planes = buf[44];
	m->plane_len = ctag_get_le16(&buf[45]);
	return 0;
}

/* Record PLANE_DATA plaintext (type 0x11, b2t): 3 bytes + data (<= CTAG_TAG_PLANE_DATA_MAX). */
#define CTAG_REC_PLANE_DATA_LEN 3
#define CTAG_REC_PLANE_DATA_MAX_LEN (CTAG_REC_PLANE_DATA_LEN + CTAG_TAG_PLANE_DATA_MAX)
struct ctag_rec_plane_data {
	uint8_t plane;
	uint16_t offset; /* Must equal bytes already received for this plane */
	const uint8_t *data;
	size_t data_len;
};

static inline int ctag_rec_plane_data_pack(const struct ctag_rec_plane_data *m, uint8_t *buf, size_t size)
{
	if (m->data_len > CTAG_TAG_PLANE_DATA_MAX) {
		return -EMSGSIZE;
	}
	if (m->data_len > 0u && m->data == NULL) {
		return -EINVAL;
	}
	if (size < CTAG_REC_PLANE_DATA_LEN + m->data_len) {
		return -EMSGSIZE;
	}
	buf[0] = m->plane;
	ctag_put_le16(&buf[1], m->offset);
	if (m->data_len > 0u) {
		memcpy(&buf[3], m->data, m->data_len);
	}
	return (int)(CTAG_REC_PLANE_DATA_LEN + m->data_len);
}

static inline int ctag_rec_plane_data_unpack(struct ctag_rec_plane_data *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_REC_PLANE_DATA_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_REC_PLANE_DATA_MAX_LEN) {
		return -EMSGSIZE;
	}
	m->plane = buf[0];
	m->offset = ctag_get_le16(&buf[1]);
	m->data = &buf[3];
	m->data_len = len - CTAG_REC_PLANE_DATA_LEN;
	return 0;
}

/* Record FRAME_END plaintext (type 0x12, b2t): 0 bytes. */
#define CTAG_REC_FRAME_END_LEN 0

/* Record FRAME_ABORT plaintext (type 0x13, b2t): 1 bytes. */
#define CTAG_REC_FRAME_ABORT_LEN 1
struct ctag_rec_frame_abort {
	uint8_t status;
};

static inline int ctag_rec_frame_abort_pack(const struct ctag_rec_frame_abort *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_REC_FRAME_ABORT_LEN) {
		return -EMSGSIZE;
	}
	buf[0] = m->status;
	return CTAG_REC_FRAME_ABORT_LEN;
}

static inline int ctag_rec_frame_abort_unpack(struct ctag_rec_frame_abort *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_REC_FRAME_ABORT_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_REC_FRAME_ABORT_LEN) {
		return -EMSGSIZE;
	}
	m->status = buf[0];
	return 0;
}

/* Record CMD plaintext (type 0x14, b2t): 9 bytes. */
#define CTAG_REC_CMD_LEN 9
struct ctag_rec_cmd {
	uint8_t cmd;
	uint64_t update_id;
};

static inline int ctag_rec_cmd_pack(const struct ctag_rec_cmd *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_REC_CMD_LEN) {
		return -EMSGSIZE;
	}
	buf[0] = m->cmd;
	ctag_put_le64(&buf[1], m->update_id);
	return CTAG_REC_CMD_LEN;
}

static inline int ctag_rec_cmd_unpack(struct ctag_rec_cmd *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_REC_CMD_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_REC_CMD_LEN) {
		return -EMSGSIZE;
	}
	m->cmd = buf[0];
	m->update_id = ctag_get_le64(&buf[1]);
	return 0;
}

/* Record RESULT plaintext (type 0x20, t2b): 30 bytes. */
#define CTAG_REC_RESULT_LEN 30
struct ctag_rec_result {
	uint64_t update_id;
	uint32_t epoch;
	uint32_t revision;
	uint8_t status;
	uint8_t digest[8];
	uint16_t battery_mv;
	uint16_t refresh_ms;
	uint8_t flags; /* bit0 duplicate (stored ACK re-sent) */
};

static inline int ctag_rec_result_pack(const struct ctag_rec_result *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_REC_RESULT_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le64(&buf[0], m->update_id);
	ctag_put_le32(&buf[8], m->epoch);
	ctag_put_le32(&buf[12], m->revision);
	buf[16] = m->status;
	memcpy(&buf[17], m->digest, 8);
	ctag_put_le16(&buf[25], m->battery_mv);
	ctag_put_le16(&buf[27], m->refresh_ms);
	buf[29] = m->flags;
	return CTAG_REC_RESULT_LEN;
}

static inline int ctag_rec_result_unpack(struct ctag_rec_result *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_REC_RESULT_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_REC_RESULT_LEN) {
		return -EMSGSIZE;
	}
	m->update_id = ctag_get_le64(&buf[0]);
	m->epoch = ctag_get_le32(&buf[8]);
	m->revision = ctag_get_le32(&buf[12]);
	m->status = buf[16];
	memcpy(m->digest, &buf[17], 8);
	m->battery_mv = ctag_get_le16(&buf[25]);
	m->refresh_ms = ctag_get_le16(&buf[27]);
	m->flags = buf[29];
	return 0;
}

/* Record PROGRESS plaintext (type 0x21, t2b): 1 bytes. */
#define CTAG_REC_PROGRESS_LEN 1
struct ctag_rec_progress {
	uint8_t stage; /* delivery_stages.REFRESHING when validated and refresh starts */
};

static inline int ctag_rec_progress_pack(const struct ctag_rec_progress *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_REC_PROGRESS_LEN) {
		return -EMSGSIZE;
	}
	buf[0] = m->stage;
	return CTAG_REC_PROGRESS_LEN;
}

static inline int ctag_rec_progress_unpack(struct ctag_rec_progress *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_REC_PROGRESS_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_REC_PROGRESS_LEN) {
		return -EMSGSIZE;
	}
	m->stage = buf[0];
	return 0;
}

/* STATUS plain CREDIT (type 0xC0, t2b), after the type byte: 1 bytes. */
#define CTAG_PLAIN_CREDIT_LEN 1
struct ctag_plain_credit {
	uint8_t credits; /* Incremental grant of DATA records the bridge may send */
};

static inline int ctag_plain_credit_pack(const struct ctag_plain_credit *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_PLAIN_CREDIT_LEN) {
		return -EMSGSIZE;
	}
	buf[0] = m->credits;
	return CTAG_PLAIN_CREDIT_LEN;
}

static inline int ctag_plain_credit_unpack(struct ctag_plain_credit *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_PLAIN_CREDIT_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_PLAIN_CREDIT_LEN) {
		return -EMSGSIZE;
	}
	m->credits = buf[0];
	return 0;
}

/* Enrollment blob (UICR.CUSTOMER): 48 bytes. */
#define CTAG_ENROLLMENT_LEN 48
struct ctag_enrollment {
	uint32_t magic;
	uint8_t version;
	uint8_t board;
	uint8_t panel;
	uint8_t flags;
	uint32_t tag_id;
	uint8_t secret[32];
	uint32_t crc32; /* CRC-32/IEEE over all previous bytes */
};

static inline int ctag_enrollment_pack(const struct ctag_enrollment *m, uint8_t *buf, size_t size)
{
	if (size < CTAG_ENROLLMENT_LEN) {
		return -EMSGSIZE;
	}
	ctag_put_le32(&buf[0], m->magic);
	buf[4] = m->version;
	buf[5] = m->board;
	buf[6] = m->panel;
	buf[7] = m->flags;
	ctag_put_le32(&buf[8], m->tag_id);
	memcpy(&buf[12], m->secret, 32);
	ctag_put_le32(&buf[44], m->crc32);
	return CTAG_ENROLLMENT_LEN;
}

static inline int ctag_enrollment_unpack(struct ctag_enrollment *m, const uint8_t *buf, size_t len)
{
	if (len < CTAG_ENROLLMENT_LEN) {
		return -EINVAL;
	}
	if (len > CTAG_ENROLLMENT_LEN) {
		return -EMSGSIZE;
	}
	m->magic = ctag_get_le32(&buf[0]);
	m->version = buf[4];
	m->board = buf[5];
	m->panel = buf[6];
	m->flags = buf[7];
	m->tag_id = ctag_get_le32(&buf[8]);
	memcpy(m->secret, &buf[12], 32);
	m->crc32 = ctag_get_le32(&buf[44]);
	return 0;
}

#ifdef __cplusplus
}
#endif

#endif /* CTAG_PROTO_MSGS_H_ */
