/*
 * DO NOT EDIT: generated by tools/codegen.py from protocol/spec.yaml.
 * spec sha256: d74dca1ffd513bd0b743735875a650c50c446e8c1ed92105121cab9c7278af83
 *
 * Protocol identifiers and constants for Cremind Tag firmware.
 * Narrative and rules: docs/protocol.md. Field layouts: proto_msgs.h.
 */
#ifndef CTAG_PROTO_IDS_H_
#define CTAG_PROTO_IDS_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define CTAG_SPEC_VERSION 1
#define CTAG_SPEC_SHA256 "d74dca1ffd513bd0b743735875a650c50c446e8c1ed92105121cab9c7278af83"

/* ---- Constants (spec: constants) ---- */

#define CTAG_PROTO_VERSION 1 /* Version carried by serial frames, mesh CAPS, GATT HELLO and layout headers */
#define CTAG_SERIAL_MAX_FRAME 4096 /* Maximum DECODED serial frame (header + payload + CRC) */
#define CTAG_SERIAL_HEADER_LEN 8 /* Serial frame header length */
#define CTAG_SERIAL_CRC_LEN 4 /* CRC-32/IEEE trailer length */
#define CTAG_SERIAL_MAX_PAYLOAD 4084 /* SERIAL_MAX_FRAME - header - CRC */
#define CTAG_SERIAL_MAX_ENCODED 4128 /* Worst-case COBS-encoded frame incl. 0x00 delimiter (4096 + ceil(4096/254) + 1, rounded up) */
#define CTAG_SERIAL_DEFAULT_CREDITS 4 /* Frames each side may send before the first credit grant */
#define CTAG_SERIAL_EVENT_RETAIN 16 /* Unacknowledged gateway events (EVT_RESULT etc.) kept for re-send */
#define CTAG_SERIAL_IDEMPOTENCY_SLOTS 32 /* Recent op_id -> status entries the gateway remembers */
#define CTAG_MESH_COMPANY_ID 0xFFFF /* Bluetooth SIG company id used by vendor models. 0xFFFF = SIG test/unassigned value; production needs an assigned id */
#define CTAG_MESH_MAX_VENDOR_PARAMS 160 /* Maximum vendor-model message parameter bytes */
#define CTAG_MESH_MIN_SEG 16 /* Minimum CONFIG_BT_MESH_TX_SEG_MAX / RX_SEG_MAX */
#define CTAG_MESH_DEFAULT_TTL 5 /* Default TTL for gateway<->bridge messages */
#define CTAG_MESH_RESULT_RETRIES 5 /* Bridge re-sends of DELIVERY_RESULT until RESULT_ACK */
#define CTAG_MESH_RESULT_RETRY_MS 2000 /* Interval between DELIVERY_RESULT re-sends */
#define CTAG_LAYOUT_TYPICAL_MAX 1024 /* Typical logical card upper bound (design target, not enforced) */
#define CTAG_LAYOUT_HARD_MAX 4096 /* Hard maximum logical screen size in bytes */
#define CTAG_LAYOUT_MAX_GLYPHS 512 /* Hard maximum positioned glyphs per screen */
#define CTAG_LAYOUT_MAX_COMMANDS 256 /* Hard maximum commands per screen */
#define CTAG_LAYOUT_CHUNK_DATA_MAX 150 /* Layout bytes per mesh LAYOUT_CHUNK */
#define CTAG_LAYOUT_MAX_CHUNKS 28 /* ceil(LAYOUT_HARD_MAX / LAYOUT_CHUNK_DATA_MAX) */
#define CTAG_LAYOUT_DIGEST_LEN 16 /* Layout digest = SHA-256(layout bytes) truncated to 16 bytes */
#define CTAG_LAYOUT_QR_MAX_TEXT 96 /* Maximum QR payload bytes (short token-free https link) */
#define CTAG_FONTPACK_ID_LEN 8 /* Font-pack id = first 8 bytes of the pack content SHA-256 */
#define CTAG_FRAME_DIGEST_LEN 32 /* Frame digest = SHA-256 over plane 0 bytes then plane 1 bytes */
#define CTAG_MAX_BRIDGES 5 /* Bridges per gateway (qualified topology) */
#define CTAG_MAX_TAGS 20 /* Tags per gateway (qualified topology) */
#define CTAG_MAX_TAGS_PER_BRIDGE 20 /* Assignment table size on a bridge */
#define CTAG_TAG_KEY_LEN 16 /* Per-epoch tag authorization key length (K_epoch) */
#define CTAG_TAG_SECRET_LEN 32 /* Per-tag enrollment secret length */
#define CTAG_TAG_NONCE_LEN 16 /* Handshake nonce length, each side */
#define CTAG_TAG_MAC_LEN 16 /* Truncated HMAC-SHA256 length in the handshake */
#define CTAG_TAG_RECORD_MIC_LEN 8 /* AES-CCM tag length on records */
#define CTAG_TAG_RECORD_BUF 256 /* Tag reassembly buffer size (two of these) */
#define CTAG_TAG_RECORD_PAYLOAD_MAX 192 /* Maximum plaintext payload per authenticated record */
#define CTAG_TAG_PLANE_DATA_MAX 189 /* Image bytes per PLANE_DATA record (192 - 3 header bytes) */
#define CTAG_TAG_RECORD_WIRE_MAX 205 /* type(1) + counter(4) + TAG_RECORD_PAYLOAD_MAX + mic(8) */
#define CTAG_TAG_CTRL_MSG_MAX 64 /* Maximum reassembled control message */
#define CTAG_ATT_MTU 23 /* Compatibility baseline ATT MTU */
#define CTAG_ATT_VALUE_MAX 20 /* ATT_MTU - 3 */
#define CTAG_FRAG_PAYLOAD_MAX 19 /* ATT_VALUE_MAX - 1 fragment header byte */
#define CTAG_TAG_WAKE_PERIOD_MS 30000 /* Nominal RTC wake period */
#define CTAG_TAG_WAKE_JITTER_MS 3000 /* Uniform +/- jitter added to each wake */
#define CTAG_TAG_ADV_WINDOW_MS 2000 /* Connectable advertising window per wake */
#define CTAG_TAG_ADV_INTERVAL_MS 250 /* Advertising interval during the window */
#define CTAG_TAG_SESSION_TIMEOUT_MS 20000 /* Tag drops a connection with no progress for this long */
#define CTAG_BRIDGE_CONN_ATTEMPT_MS 1000 /* Bounded BLE connection initiation (mesh is suspended meanwhile) */
#define CTAG_BRIDGE_STRIP_ROWS 16 /* Native panel rows per rendering strip */
#define CTAG_BRIDGE_TAG_BACKOFF_MS 15000 /* Minimum wait before retrying a tag after a failed attempt */
#define CTAG_BRIDGE_MAX_SUSPENDS_PER_MIN 6 /* Upper bound on mesh suspend/resume cycles per minute (anti-starvation) */

/* Glyph strike sizes in pixels */
#define CTAG_FONT_SIZES_COUNT 3
#define CTAG_FONT_SIZES_LIST 16, 24, 32
static inline uint32_t ctag_font_sizes_at(size_t i)
{
	static const uint8_t v[CTAG_FONT_SIZES_COUNT] = {CTAG_FONT_SIZES_LIST};

	return i < CTAG_FONT_SIZES_COUNT ? v[i] : 0u;
}

static inline bool ctag_font_sizes_contains(uint32_t value)
{
	size_t i;

	for (i = 0; i < CTAG_FONT_SIZES_COUNT; i++) {
		if (ctag_font_sizes_at(i) == value) {
			return true;
		}
	}
	return false;
}


/* Icon strike sizes in pixels */
#define CTAG_ICON_SIZES_COUNT 4
#define CTAG_ICON_SIZES_LIST 16, 24, 32, 48
static inline uint32_t ctag_icon_sizes_at(size_t i)
{
	static const uint8_t v[CTAG_ICON_SIZES_COUNT] = {CTAG_ICON_SIZES_LIST};

	return i < CTAG_ICON_SIZES_COUNT ? v[i] : 0u;
}

static inline bool ctag_icon_sizes_contains(uint32_t value)
{
	size_t i;

	for (i = 0; i < CTAG_ICON_SIZES_COUNT; i++) {
		if (ctag_icon_sizes_at(i) == value) {
			return true;
		}
	}
	return false;
}

#define CTAG_FONTPACK_WORKING_SPACE 16777216 /* 16 MiB bridge working space in the flash sizing rule (production parts; development boards may configure a smaller one, docs/fontpack.md ?3) */
#define CTAG_FONTPACK_DIR_SIZE 65536 /* Slot directory area at the START OF THE WORKING SPACE (offset 2 * slot_size), docs/fontpack.md ?3 */

/* ---- Status codes, delivery stages and outcomes ---- */

/* Status codes shared by serial, mesh, GATT and receipts. Never renumbered. */
enum ctag_status {
	CTAG_STATUS_OK = 0, /* Success */
	CTAG_STATUS_ACCEPTED = 1, /* Accepted for asynchronous processing */
	CTAG_STATUS_DUPLICATE = 2, /* Already processed; the stored result is returned */
	CTAG_STATUS_BUSY = 3, /* Temporarily unable (queue full, one-outstanding-send rule); retry later */
	CTAG_STATUS_NO_RESOURCES = 4, /* Out of memory/slots */
	CTAG_STATUS_INVALID = 5, /* Malformed or out-of-bounds input */
	CTAG_STATUS_UNSUPPORTED = 6, /* Unknown message/command/version feature */
	CTAG_STATUS_NOT_FOUND = 7, /* Unknown node, tag, update or op */
	CTAG_STATUS_STALE_EPOCH = 8, /* Assignment epoch older than the stored one */
	CTAG_STATUS_STALE_REVISION = 9, /* Revision older than the displayed/desired one */
	CTAG_STATUS_REVISION_CONFLICT = 10, /* Same (epoch, revision) with a different digest */
	CTAG_STATUS_FONTPACK_MISMATCH = 11, /* Layout references a font pack the bridge does not have active */
	CTAG_STATUS_DIGEST_MISMATCH = 12, /* Computed digest differs from the announced one */
	CTAG_STATUS_INCOMPLETE = 13, /* Missing chunks/records */
	CTAG_STATUS_AUTH_FAILED = 14, /* Handshake MAC, record MIC or counter check failed */
	CTAG_STATUS_TIMEOUT = 15, /* Operation timed out */
	CTAG_STATUS_CONNECT_FAILED = 16, /* BLE connection could not be established */
	CTAG_STATUS_DISCONNECTED = 17, /* Link dropped mid-session */
	CTAG_STATUS_MESH_SUSPEND_FAILED = 18, /* bt_mesh_suspend() rejected; no connection was attempted */
	CTAG_STATUS_MESH_RESUME_FAILED = 19, /* bt_mesh_resume() failed; session aborted, recovery entered */
	CTAG_STATUS_PANEL_ERROR = 20, /* Panel controller error (SPI, BUSY stuck, bad staging) */
	CTAG_STATUS_REFRESH_TIMEOUT = 21, /* BUSY did not release within the panel's refresh bound */
	CTAG_STATUS_STORAGE_ERROR = 22, /* Persistent storage read/write failed */
	CTAG_STATUS_DISPLAY_STATE_UNKNOWN = 23, /* Reset between physical refresh and result persistence; screen content uncertain */
	CTAG_STATUS_CANCELLED = 24, /* Cancelled by a newer revision, reassignment or operator */
	CTAG_STATUS_NOT_ASSIGNED = 25, /* Tag is not assigned to this bridge (or epoch differs) */
	CTAG_STATUS_TOO_LARGE = 26, /* Exceeds a hard size/count limit */
	CTAG_STATUS_CRC_ERROR = 27, /* Frame/strike CRC mismatch */
	CTAG_STATUS_VERSION_MISMATCH = 28, /* Peer protocol version not supported */
	CTAG_STATUS_SECURITY_CONFIG = 29, /* Missing/invalid key material or enrollment; stop and report */
	CTAG_STATUS_INTERNAL = 30, /* Unexpected internal error */
	CTAG_STATUS_PROVISIONING_ACTIVE = 31, /* Refused while provisioning/configuration is in progress */
	CTAG_STATUS_EXPIRED = 32, /* Job TTL elapsed before delivery */
	CTAG_STATUS_SUPERSEDED = 33, /* Replaced by a newer revision for the same tag/slot */
};

/* Delivery stages. */
enum ctag_stage {
	CTAG_STAGE_QUEUED = 0, /* Created by Cremind's projection worker */
	CTAG_STAGE_COMPANION_ACCEPTED = 1, /* Committed to the companion's durable queue */
	CTAG_STAGE_GATEWAY_RECEIVED = 2, /* Gateway acknowledged DELIVER_LAYOUT (serial ACK) */
	CTAG_STAGE_BRIDGE_RECEIVED = 3, /* Bridge validated the complete layout (LAYOUT_STATUS OK) */
	CTAG_STAGE_TRANSFERRING = 4, /* Bridge authenticated with the tag and is streaming the image */
	CTAG_STAGE_REFRESHING = 5, /* Tag validated the frame and started the panel refresh */
	CTAG_STAGE_DISPLAYED = 6, /* Tag reported BUSY complete and persisted the result (terminal) */
};

/* Terminal delivery outcomes. */
enum ctag_outcome {
	CTAG_OUTCOME_DISPLAYED = 0, /* Refresh completed and ACKed */
	CTAG_OUTCOME_SUPERSEDED = 1, /* A newer revision replaced this one before display */
	CTAG_OUTCOME_EXPIRED = 2, /* TTL elapsed */
	CTAG_OUTCOME_CANCELLED = 3, /* Operator/ownership change cancelled it */
	CTAG_OUTCOME_FAILED = 4, /* Permanent failure (security/config/invalid) - stop and report */
	CTAG_OUTCOME_UNCERTAIN = 5, /* Refresh may or may not have happened (DISPLAY_STATE_UNKNOWN, lost result) */
};

/* ---- Serial protocol (docs/protocol.md 1) ---- */

/* Serial header flags bits. */
enum ctag_serial_flag {
	CTAG_SERIAL_FLAG_RESPONSE = 0x01, /* This frame answers request_id */
	CTAG_SERIAL_FLAG_EVENT = 0x02, /* Unsolicited event (request_id = 0) */
};

/* Serial message types (header byte 1). */
enum ctag_serial_msg {
	CTAG_SERIAL_MSG_HELLO = 0x01, /* h2d: {proto, name} -> {status, proto, fw, build, boot_id, caps:{max_frame, credits, max_bridges, max_tags, role}} */
	CTAG_SERIAL_MSG_PING = 0x02, /* h2d: {} -> {status, uptime_s} */
	CTAG_SERIAL_MSG_REBOOT = 0x03, /* h2d: {op_id} -> {status}; device reboots after responding */
	CTAG_SERIAL_MSG_EVENT_ACK = 0x04, /* h2d: {seq} -> {status}; releases retained events with seq <= given */
	CTAG_SERIAL_MSG_INFO = 0x05, /* h2d: {} -> {status, fw, build, boot_id, caps, counters} */
	CTAG_SERIAL_MSG_SCAN_UNPROV = 0x10, /* h2d: {duration_s, uuid_filter?} -> {status}; emits EVT_UNPROV_BEACON */
	CTAG_SERIAL_MSG_PROVISION = 0x11, /* h2d: {op_id, uuid, name?} -> {status: ACCEPTED}; later EVT_PROVISIONED */
	CTAG_SERIAL_MSG_CONFIGURE_NODE = 0x12, /* h2d: {op_id, addr, relay, ttl} -> ACCEPTED; later EVT_NODE_CONFIGURED (app key add/bind + relay + TTL) */
	CTAG_SERIAL_MSG_REMOVE_NODE = 0x13, /* h2d: {op_id, addr} -> ACCEPTED; later EVT_NODE_REMOVED (node reset + CDB delete) */
	CTAG_SERIAL_MSG_LIST_NODES = 0x14, /* h2d: {} -> {status, nodes:[{addr, uuid, elements, configured, name, last_seen_s}]} */
	CTAG_SERIAL_MSG_ASSIGN_TAG = 0x20, /* h2d: {op_id, bridge, tag_id, epoch, key} -> ACCEPTED; later EVT_ASSIGN_RESULT */
	CTAG_SERIAL_MSG_UNASSIGN_TAG = 0x21, /* h2d: {op_id, bridge, tag_id, epoch} -> ACCEPTED; later EVT_ASSIGN_RESULT */
	CTAG_SERIAL_MSG_DELIVER_LAYOUT = 0x30, /* h2d: {op_id, bridge, tag_id, epoch, revision, update_id, fontpack_id, layout} -> {status: ACCEPTED|BUSY|INVALID|DUPLICATE}; later EVT_STAGE*, EVT_RESULT */
	CTAG_SERIAL_MSG_CANCEL_DELIVERY = 0x31, /* h2d: {op_id, update_id} -> {status} */
	CTAG_SERIAL_MSG_TAG_COMMAND = 0x32, /* h2d: {op_id, bridge, tag_id, epoch, cmd} -> ACCEPTED; later EVT_RESULT (update_id = op_id) */
	CTAG_SERIAL_MSG_GET_INVENTORY = 0x40, /* h2d: {} -> {status, items:[bridge info]}; also refreshes via mesh CAPS/HEALTH (EVT_BRIDGE_INFO) */
	CTAG_SERIAL_MSG_GET_COUNTERS = 0x41, /* h2d: {} -> {status, counters} */
	CTAG_SERIAL_MSG_IDENTIFY_NODE = 0x42, /* h2d: {op_id, addr} -> {status}; bridge blinks/beeps */
	CTAG_SERIAL_MSG_FONT_BEGIN = 0x60, /* h2d: {size, digest(32), fontpack_id} -> {status, slot, flash_size} */
	CTAG_SERIAL_MSG_FONT_DATA = 0x61, /* h2d: {offset, data} -> {status}; offsets strictly sequential */
	CTAG_SERIAL_MSG_FONT_COMMIT = 0x62, /* h2d: {} -> {status, fontpack_id}; verifies SHA-256 then flips the slot directory */
	CTAG_SERIAL_MSG_FONT_STATUS = 0x63, /* h2d: {} -> {status, fontpack_id, slot, size, flash_size} */
	CTAG_SERIAL_MSG_FONT_ABORT = 0x64, /* h2d: {} -> {status} */
	CTAG_SERIAL_MSG_FLASH_TEST = 0x65, /* h2d: {op_id} -> {status, flash_size, items:[{offset, status}]}; erase/write/read-back patterns at the first sector of the inactive slot, the sectors either side of the 16 MiB boundary and the last sector of the device (the working space ends there); never touches the active slot or the directory */
	CTAG_SERIAL_MSG_EVT_LOG = 0x80, /* d2h: {text} diagnostic, not retained */
	CTAG_SERIAL_MSG_EVT_UNPROV_BEACON = 0x81, /* d2h: {uuid, rssi, oob} */
	CTAG_SERIAL_MSG_EVT_PROVISIONED = 0x82, /* d2h: {seq, op_id, uuid, addr, elements, status} */
	CTAG_SERIAL_MSG_EVT_NODE_CONFIGURED = 0x83, /* d2h: {seq, op_id, addr, status} */
	CTAG_SERIAL_MSG_EVT_NODE_REMOVED = 0x84, /* d2h: {seq, op_id, addr, status} */
	CTAG_SERIAL_MSG_EVT_ASSIGN_RESULT = 0x85, /* d2h: {seq, op_id, bridge, tag_id, epoch, status} */
	CTAG_SERIAL_MSG_EVT_STAGE = 0x86, /* d2h: {update_id, tag_id, revision, stage} best effort, not retained */
	CTAG_SERIAL_MSG_EVT_RESULT = 0x87, /* d2h: {seq, update_id, bridge, tag_id, epoch, revision, status, digest(8), battery_mv, timing} */
	CTAG_SERIAL_MSG_EVT_BRIDGE_INFO = 0x88, /* d2h: {addr, fw, fontpack_id, caps, assigned, counters} */
	CTAG_SERIAL_MSG_EVT_TAG_SEEN = 0x89, /* d2h: {bridge, tag_id, rssi, battery_mv, flags} rate-limited sighting */
};

/* Integer keys of serial CBOR maps (one global dictionary). */
enum ctag_cbor_key {
	CTAG_CBOR_KEY_STATUS = 0,
	CTAG_CBOR_KEY_OP_ID = 1, /* uint64 chosen by the companion; idempotency key for side-effecting requests */
	CTAG_CBOR_KEY_ADDR = 2, /* mesh unicast address (uint) */
	CTAG_CBOR_KEY_UUID = 3, /* 16-byte mesh device UUID (bstr) */
	CTAG_CBOR_KEY_TAG_ID = 4, /* uint32 */
	CTAG_CBOR_KEY_EPOCH = 5, /* uint32 assignment epoch */
	CTAG_CBOR_KEY_REVISION = 6, /* uint32 display revision */
	CTAG_CBOR_KEY_UPDATE_ID = 7, /* uint64 Cremind delivery id */
	CTAG_CBOR_KEY_FONTPACK_ID = 8, /* bstr[8] */
	CTAG_CBOR_KEY_LAYOUT = 9, /* bstr (logical screen, <= LAYOUT_HARD_MAX) */
	CTAG_CBOR_KEY_STAGE = 10, /* uint delivery_stages */
	CTAG_CBOR_KEY_DETAIL = 11, /* uint status detail / sub-code */
	CTAG_CBOR_KEY_RSSI = 12, /* int */
	CTAG_CBOR_KEY_OOB = 13, /* uint OOB info bits */
	CTAG_CBOR_KEY_DURATION_S = 14, /* uint */
	CTAG_CBOR_KEY_RELAY = 15, /* bool */
	CTAG_CBOR_KEY_TTL = 16, /* uint */
	CTAG_CBOR_KEY_KEY = 17, /* bstr[16] */
	CTAG_CBOR_KEY_FW = 18, /* tstr "x.y.z" */
	CTAG_CBOR_KEY_BUILD = 19, /* tstr build id / git hash */
	CTAG_CBOR_KEY_BOOT_ID = 20, /* uint32 random per boot */
	CTAG_CBOR_KEY_CAPS = 21, /* map */
	CTAG_CBOR_KEY_NODES = 22, /* array of maps */
	CTAG_CBOR_KEY_ELEMENTS = 23, /* uint */
	CTAG_CBOR_KEY_NAME = 24, /* tstr */
	CTAG_CBOR_KEY_COUNTERS = 25, /* map tstr -> uint */
	CTAG_CBOR_KEY_BATTERY_MV = 26, /* uint */
	CTAG_CBOR_KEY_TIMING = 27, /* map {wake_ms, mesh_ms, transfer_ms, refresh_ms, suspend_ms} */
	CTAG_CBOR_KEY_DIGEST = 28, /* bstr */
	CTAG_CBOR_KEY_PROTO = 29, /* uint protocol version */
	CTAG_CBOR_KEY_MAX_FRAME = 30, /* uint */
	CTAG_CBOR_KEY_CREDITS = 31, /* uint initial credits */
	CTAG_CBOR_KEY_FLAGS = 32, /* uint */
	CTAG_CBOR_KEY_BRIDGE = 33, /* uint mesh unicast address of a bridge */
	CTAG_CBOR_KEY_ITEMS = 34, /* array */
	CTAG_CBOR_KEY_CMD = 35, /* uint tag_commands */
	CTAG_CBOR_KEY_SEQ = 36, /* uint event sequence number (EVENT_ACK) */
	CTAG_CBOR_KEY_TIME_MS = 37, /* uint */
	CTAG_CBOR_KEY_TEXT = 38, /* tstr human-readable error text */
	CTAG_CBOR_KEY_SIZE = 39, /* uint byte size */
	CTAG_CBOR_KEY_OFFSET = 40, /* uint byte offset */
	CTAG_CBOR_KEY_DATA = 41, /* bstr */
	CTAG_CBOR_KEY_ROLE = 42, /* uint node_roles */
	CTAG_CBOR_KEY_CONFIGURED = 43, /* bool */
	CTAG_CBOR_KEY_LAST_SEEN_S = 44, /* uint seconds since last contact */
	CTAG_CBOR_KEY_BOARD = 45, /* uint board id */
	CTAG_CBOR_KEY_PANEL = 46, /* uint panel id */
	CTAG_CBOR_KEY_FLASH_SIZE = 47, /* uint bytes */
	CTAG_CBOR_KEY_SLOT = 48, /* uint font slot */
	CTAG_CBOR_KEY_ASSIGNED = 49, /* array of {tag_id, epoch} */
	CTAG_CBOR_KEY_UPTIME_S = 50, /* uint */
	CTAG_CBOR_KEY_WAKE_MS = 51,
	CTAG_CBOR_KEY_MESH_MS = 52,
	CTAG_CBOR_KEY_TRANSFER_MS = 53,
	CTAG_CBOR_KEY_REFRESH_MS = 54,
	CTAG_CBOR_KEY_SUSPEND_MS = 55,
	CTAG_CBOR_KEY_QUEUE_DEPTH = 56,
	CTAG_CBOR_KEY_MAX_BRIDGES = 57,
	CTAG_CBOR_KEY_MAX_TAGS = 58,
	CTAG_CBOR_KEY_UUID_FILTER = 59, /* bstr prefix filter for SCAN_UNPROV */
	CTAG_CBOR_KEY_NET_IDX = 60,
	CTAG_CBOR_KEY_APP_IDX = 61,
};

/* Tag commands. */
enum ctag_tag_cmd {
	CTAG_TAG_CMD_CLEAR = 1, /* Clear to white (full refresh) and persist revision 0 for the epoch */
	CTAG_TAG_CMD_IDENTIFY = 2, /* Show an identify pattern with the tag id (bridge renders it) */
	CTAG_TAG_CMD_REFRESH = 3, /* Re-send the current layout (repeat refresh) */
	CTAG_TAG_CMD_SLEEP = 4, /* Enter shipping mode (System OFF) - only if external wake is verified */
};

/* Node roles. */
enum ctag_node_role {
	CTAG_NODE_ROLE_GATEWAY = 1, /* Mesh provisioner + serial bridge to the companion */
	CTAG_NODE_ROLE_BRIDGE = 2, /* Mesh relay + BLE central + renderer */
	CTAG_NODE_ROLE_TAG = 3, /* Battery e-paper BLE peripheral */
};

/* ---- Bluetooth Mesh vendor models (docs/protocol.md 2-3) ---- */

/* Vendor model ids (company CTAG_MESH_COMPANY_ID). */
enum ctag_mesh_model {
	CTAG_MESH_MODEL_LAYOUT_SRV = 0x0001, /* on bridge: Receives layouts; sends stage/result */
	CTAG_MESH_MODEL_LAYOUT_CLI = 0x0002, /* on gateway: Sends layouts; receives stage/result */
	CTAG_MESH_MODEL_MGMT_SRV = 0x0003, /* on bridge: Capabilities, health, assignments, tag commands, counters */
	CTAG_MESH_MODEL_MGMT_CLI = 0x0004, /* on gateway: Management client */
};

/* 6-bit vendor opcode numbers. */
enum ctag_mesh_op {
	CTAG_MESH_OP_LAYOUT_BEGIN = 0x01, /* handled by LAYOUT_SRV */
	CTAG_MESH_OP_LAYOUT_CHUNK = 0x02, /* handled by LAYOUT_SRV */
	CTAG_MESH_OP_LAYOUT_COMMIT = 0x03, /* handled by LAYOUT_SRV */
	CTAG_MESH_OP_LAYOUT_CANCEL = 0x04, /* handled by LAYOUT_SRV */
	CTAG_MESH_OP_LAYOUT_STATUS = 0x05, /* handled by LAYOUT_CLI */
	CTAG_MESH_OP_DELIVERY_STAGE = 0x06, /* handled by LAYOUT_CLI */
	CTAG_MESH_OP_DELIVERY_RESULT = 0x07, /* handled by LAYOUT_CLI */
	CTAG_MESH_OP_RESULT_ACK = 0x08, /* handled by LAYOUT_SRV */
	CTAG_MESH_OP_CAPS_GET = 0x10, /* handled by MGMT_SRV */
	CTAG_MESH_OP_CAPS_STATUS = 0x11, /* handled by MGMT_CLI */
	CTAG_MESH_OP_HEALTH_GET = 0x12, /* handled by MGMT_SRV */
	CTAG_MESH_OP_HEALTH_STATUS = 0x13, /* handled by MGMT_CLI */
	CTAG_MESH_OP_ASSIGN_SET = 0x14, /* handled by MGMT_SRV */
	CTAG_MESH_OP_ASSIGN_DEL = 0x15, /* handled by MGMT_SRV */
	CTAG_MESH_OP_ASSIGN_STATUS = 0x16, /* handled by MGMT_CLI */
	CTAG_MESH_OP_TAG_CMD = 0x17, /* handled by MGMT_SRV */
	CTAG_MESH_OP_IDENTIFY = 0x18, /* handled by MGMT_SRV */
	CTAG_MESH_OP_TAG_SEEN = 0x19, /* handled by MGMT_CLI */
};

/*
 * 3-octet vendor opcode, equal to Zephyr's BT_MESH_MODEL_OP_3(op, CTAG_MESH_COMPANY_ID):
 * bits 16..23 = 0xC0 | op, bits 0..15 = the company id in HOST order (no byte
 * swap). bt_mesh_model_msg_init() writes octet 0xC0|op and then the company id
 * little-endian, so the on-air octets are {0xC0|op, cid & 0xFF, cid >> 8}.
 */
#define CTAG_MESH_VENDOR_OPCODE(op) \
	((uint32_t)(((0xC0u | (uint32_t)(op)) << 16) | (uint32_t)CTAG_MESH_COMPANY_ID))
#define CTAG_MESH_OPCODE_LAYOUT_BEGIN CTAG_MESH_VENDOR_OPCODE(CTAG_MESH_OP_LAYOUT_BEGIN)
#define CTAG_MESH_OPCODE_LAYOUT_CHUNK CTAG_MESH_VENDOR_OPCODE(CTAG_MESH_OP_LAYOUT_CHUNK)
#define CTAG_MESH_OPCODE_LAYOUT_COMMIT CTAG_MESH_VENDOR_OPCODE(CTAG_MESH_OP_LAYOUT_COMMIT)
#define CTAG_MESH_OPCODE_LAYOUT_CANCEL CTAG_MESH_VENDOR_OPCODE(CTAG_MESH_OP_LAYOUT_CANCEL)
#define CTAG_MESH_OPCODE_LAYOUT_STATUS CTAG_MESH_VENDOR_OPCODE(CTAG_MESH_OP_LAYOUT_STATUS)
#define CTAG_MESH_OPCODE_DELIVERY_STAGE CTAG_MESH_VENDOR_OPCODE(CTAG_MESH_OP_DELIVERY_STAGE)
#define CTAG_MESH_OPCODE_DELIVERY_RESULT CTAG_MESH_VENDOR_OPCODE(CTAG_MESH_OP_DELIVERY_RESULT)
#define CTAG_MESH_OPCODE_RESULT_ACK CTAG_MESH_VENDOR_OPCODE(CTAG_MESH_OP_RESULT_ACK)
#define CTAG_MESH_OPCODE_CAPS_GET CTAG_MESH_VENDOR_OPCODE(CTAG_MESH_OP_CAPS_GET)
#define CTAG_MESH_OPCODE_CAPS_STATUS CTAG_MESH_VENDOR_OPCODE(CTAG_MESH_OP_CAPS_STATUS)
#define CTAG_MESH_OPCODE_HEALTH_GET CTAG_MESH_VENDOR_OPCODE(CTAG_MESH_OP_HEALTH_GET)
#define CTAG_MESH_OPCODE_HEALTH_STATUS CTAG_MESH_VENDOR_OPCODE(CTAG_MESH_OP_HEALTH_STATUS)
#define CTAG_MESH_OPCODE_ASSIGN_SET CTAG_MESH_VENDOR_OPCODE(CTAG_MESH_OP_ASSIGN_SET)
#define CTAG_MESH_OPCODE_ASSIGN_DEL CTAG_MESH_VENDOR_OPCODE(CTAG_MESH_OP_ASSIGN_DEL)
#define CTAG_MESH_OPCODE_ASSIGN_STATUS CTAG_MESH_VENDOR_OPCODE(CTAG_MESH_OP_ASSIGN_STATUS)
#define CTAG_MESH_OPCODE_TAG_CMD CTAG_MESH_VENDOR_OPCODE(CTAG_MESH_OP_TAG_CMD)
#define CTAG_MESH_OPCODE_IDENTIFY CTAG_MESH_VENDOR_OPCODE(CTAG_MESH_OP_IDENTIFY)
#define CTAG_MESH_OPCODE_TAG_SEEN CTAG_MESH_VENDOR_OPCODE(CTAG_MESH_OP_TAG_SEEN)

/* ---- Logical screen layout (docs/protocol.md 4) ---- */

#define CTAG_LAYOUT_MAGIC 0x4C43 /* bytes 'C','L' */

/* Layout colours. */
enum ctag_color {
	CTAG_COLOR_WHITE = 0,
	CTAG_COLOR_BLACK = 1,
	CTAG_COLOR_RED = 2,
};

/* QR error-correction levels (= Nayuki qrcodegen_Ecc). */
enum ctag_qr_ecc {
	CTAG_QR_ECC_LOW = 0,
	CTAG_QR_ECC_MEDIUM = 1,
	CTAG_QR_ECC_QUARTILE = 2,
	CTAG_QR_ECC_HIGH = 3,
};

/* Layout command ops (first byte of every command). */
enum ctag_layout_cmd {
	CTAG_LAYOUT_CMD_CLEAR = 0x01,
	CTAG_LAYOUT_CMD_GLYPHS = 0x02, /* A run of positioned glyphs from one (face, size) strike. Each glyph origin is relative to the previous glyph origin (the first to origin_x/origin_y). Origin = pen position on the baseline. */
	CTAG_LAYOUT_CMD_ICON = 0x03,
	CTAG_LAYOUT_CMD_LINE = 0x04,
	CTAG_LAYOUT_CMD_RECT = 0x05,
	CTAG_LAYOUT_CMD_PROGRESS = 0x06,
	CTAG_LAYOUT_CMD_QR = 0x07,
};

/* Built-in icon ids (glyph ids of face 0). */
enum ctag_icon {
	CTAG_ICON_INFO = 1,
	CTAG_ICON_CHECK_CIRCLE = 2,
	CTAG_ICON_ERROR = 3,
	CTAG_ICON_WARNING = 4,
	CTAG_ICON_HELP = 5,
	CTAG_ICON_CHAT = 6,
	CTAG_ICON_TASK = 7,
	CTAG_ICON_SCHEDULE = 8,
	CTAG_ICON_EVENT = 9,
	CTAG_ICON_NOTIFICATIONS = 10,
	CTAG_ICON_SYNC = 11,
	CTAG_ICON_BATTERY_FULL = 12,
	CTAG_ICON_BATTERY_LOW = 13,
	CTAG_ICON_WIFI_OFF = 14,
	CTAG_ICON_LINK_OFF = 15,
	CTAG_ICON_DESCRIPTION = 16,
	CTAG_ICON_BOLT = 17,
	CTAG_ICON_PUSH_PIN = 18,
	CTAG_ICON_BAR_CHART = 19,
	CTAG_ICON_APPROVAL = 20,
	CTAG_ICON_HOURGLASS = 21,
	CTAG_ICON_BUG_REPORT = 22,
	CTAG_ICON_FOLDER = 23,
	CTAG_ICON_PERSON = 24,
};

#define CTAG_ICON_COUNT 24
#define CTAG_ICON_MAX_ID 24

/* ---- Tag GATT service (docs/protocol.md 5) ---- */

#define CTAG_GATT_BASE_UUID_STR "6a7c0000-4c1e-4b9f-9d2a-43524d544147"

/* Apply a macro to an argument list macro, e.g.
 * CTAG_APPLY(BT_UUID_128_ENCODE, CTAG_GATT_SERVICE_UUID_ARGS). */
#define CTAG_APPLY(m, ...) m(__VA_ARGS__)

/* Tag service: 6a7c0001-4c1e-4b9f-9d2a-43524d544147 */
#define CTAG_GATT_SERVICE_SHORT 0x0001
#define CTAG_GATT_SERVICE_UUID_ARGS 0x6a7c0001, 0x4c1e, 0x4b9f, 0x9d2a, 0x43524d544147
#define CTAG_GATT_SERVICE_UUID_VAL CTAG_APPLY(BT_UUID_128_ENCODE, CTAG_GATT_SERVICE_UUID_ARGS)
#define CTAG_GATT_SERVICE_UUID_BYTES 0x47, 0x41, 0x54, 0x4d, 0x52, 0x43, 0x2a, 0x9d, 0x9f, 0x4b, 0x1e, 0x4c, 0x01, 0x00, 0x7c, 0x6a

/* read: tag_caps struct (long read allowed): 6a7c0002-4c1e-4b9f-9d2a-43524d544147 */
#define CTAG_GATT_CHR_CAPS_SHORT 0x0002
#define CTAG_GATT_CHR_CAPS_UUID_ARGS 0x6a7c0002, 0x4c1e, 0x4b9f, 0x9d2a, 0x43524d544147
#define CTAG_GATT_CHR_CAPS_UUID_VAL CTAG_APPLY(BT_UUID_128_ENCODE, CTAG_GATT_CHR_CAPS_UUID_ARGS)
#define CTAG_GATT_CHR_CAPS_UUID_BYTES 0x47, 0x41, 0x54, 0x4d, 0x52, 0x43, 0x2a, 0x9d, 0x9f, 0x4b, 0x1e, 0x4c, 0x02, 0x00, 0x7c, 0x6a

/* write, indicate: Fragmented control messages: handshake + plaintext errors: 6a7c0003-4c1e-4b9f-9d2a-43524d544147 */
#define CTAG_GATT_CHR_CTRL_SHORT 0x0003
#define CTAG_GATT_CHR_CTRL_UUID_ARGS 0x6a7c0003, 0x4c1e, 0x4b9f, 0x9d2a, 0x43524d544147
#define CTAG_GATT_CHR_CTRL_UUID_VAL CTAG_APPLY(BT_UUID_128_ENCODE, CTAG_GATT_CHR_CTRL_UUID_ARGS)
#define CTAG_GATT_CHR_CTRL_UUID_BYTES 0x47, 0x41, 0x54, 0x4d, 0x52, 0x43, 0x2a, 0x9d, 0x9f, 0x4b, 0x1e, 0x4c, 0x03, 0x00, 0x7c, 0x6a

/* write_without_response: Fragmented authenticated records (bridge -> tag): 6a7c0004-4c1e-4b9f-9d2a-43524d544147 */
#define CTAG_GATT_CHR_DATA_SHORT 0x0004
#define CTAG_GATT_CHR_DATA_UUID_ARGS 0x6a7c0004, 0x4c1e, 0x4b9f, 0x9d2a, 0x43524d544147
#define CTAG_GATT_CHR_DATA_UUID_VAL CTAG_APPLY(BT_UUID_128_ENCODE, CTAG_GATT_CHR_DATA_UUID_ARGS)
#define CTAG_GATT_CHR_DATA_UUID_BYTES 0x47, 0x41, 0x54, 0x4d, 0x52, 0x43, 0x2a, 0x9d, 0x9f, 0x4b, 0x1e, 0x4c, 0x04, 0x00, 0x7c, 0x6a

/* notify: Credit grants (plaintext) and fragmented authenticated records (tag -> bridge): 6a7c0005-4c1e-4b9f-9d2a-43524d544147 */
#define CTAG_GATT_CHR_STATUS_SHORT 0x0005
#define CTAG_GATT_CHR_STATUS_UUID_ARGS 0x6a7c0005, 0x4c1e, 0x4b9f, 0x9d2a, 0x43524d544147
#define CTAG_GATT_CHR_STATUS_UUID_VAL CTAG_APPLY(BT_UUID_128_ENCODE, CTAG_GATT_CHR_STATUS_UUID_ARGS)
#define CTAG_GATT_CHR_STATUS_UUID_BYTES 0x47, 0x41, 0x54, 0x4d, 0x52, 0x43, 0x2a, 0x9d, 0x9f, 0x4b, 0x1e, 0x4c, 0x05, 0x00, 0x7c, 0x6a

#define CTAG_FRAG_START 0x80 /* First fragment of a message/record */
#define CTAG_FRAG_END 0x40 /* Last fragment */
#define CTAG_FRAG_SEQ_MASK 0x3F /* Fragment counter mod 64 per characteristic and direction, continuous across messages, reset to 0 on connect */

/* CTRL message types (plaintext, first byte of the reassembled message). */
enum ctag_ctrl_msg {
	CTAG_CTRL_HELLO = 0x01, /* b2t */
	CTAG_CTRL_CHALLENGE = 0x02, /* t2b */
	CTAG_CTRL_AUTH = 0x03, /* b2t */
	CTAG_CTRL_AUTH_OK = 0x04, /* t2b */
	CTAG_CTRL_ERROR = 0x05, /* t2b */
};

/* Authenticated record types (record header byte 0). */
enum ctag_rec_type {
	CTAG_REC_FRAME_BEGIN = 0x10, /* b2t */
	CTAG_REC_PLANE_DATA = 0x11, /* b2t */
	CTAG_REC_FRAME_END = 0x12, /* b2t */
	CTAG_REC_FRAME_ABORT = 0x13, /* b2t */
	CTAG_REC_CMD = 0x14, /* b2t */
	CTAG_REC_RESULT = 0x20, /* t2b */
	CTAG_REC_PROGRESS = 0x21, /* t2b */
};

/* Record nonce direction byte. */
enum ctag_rec_dir {
	CTAG_REC_DIR_B2T = 0,
	CTAG_REC_DIR_T2B = 1,
};

/* Plaintext STATUS message types. */
enum ctag_plain_msg {
	CTAG_PLAIN_CREDIT = 0xC0, /* t2b */
};

/* ---- Key schedule labels (docs/protocol.md 5.4) ---- */

#define CTAG_CRYPTO_HKDF_SALT_EPOCH "cremind-tag/v1/epoch"
#define CTAG_CRYPTO_HKDF_SALT_EPOCH_LEN 20
#define CTAG_CRYPTO_HKDF_INFO_EPOCH_PREFIX "K_epoch"
#define CTAG_CRYPTO_HKDF_INFO_EPOCH_PREFIX_LEN 7
#define CTAG_CRYPTO_MAC_LABEL_BRIDGE "B"
#define CTAG_CRYPTO_MAC_LABEL_BRIDGE_LEN 1
#define CTAG_CRYPTO_MAC_LABEL_TAG "T"
#define CTAG_CRYPTO_MAC_LABEL_TAG_LEN 1
#define CTAG_CRYPTO_HKDF_INFO_SESSION "cremind-tag/v1/session"
#define CTAG_CRYPTO_HKDF_INFO_SESSION_LEN 22

/* ---- Enrollment, boards and panels (docs/protocol.md 9) ---- */

#define CTAG_ENROLLMENT_MAGIC 0x47415443 /* bytes 'C','T','A','G' */

/* Board ids. */
enum ctag_board {
	CTAG_BOARD_NRF52840DK_GATEWAY = 1, /* nRF52840 DK / dongle gateway (USB CDC ACM) */
	CTAG_BOARD_NRF52832_GATEWAY = 2, /* nRF52832 + CH340 UART gateway */
	CTAG_BOARD_NRF52840_BRIDGE = 3, /* nRF52840 bridge with soldered external flash */
	CTAG_BOARD_NRF52832_BRIDGE = 4, /* nRF52832 bridge variant (resource qualification pending) */
	CTAG_BOARD_LAOWU_BW_NRF51822 = 16, /* Laowu 4.2in black/white, nRF51822 128K/16K */
	CTAG_BOARD_LAOWU_BWR_NRF51802 = 17, /* Laowu 4.2in black/white/red, nRF51802 256K/16K */
	CTAG_BOARD_SIFEI_NRF52810 = 18, /* Sifei 52810, 192K/24K */
	CTAG_BOARD_HEMA_NRF52811 = 19, /* Hema/Alibaba 52811, 192K/24K */
	CTAG_BOARD_NRF52DK_TAG = 20, /* nRF52 DK development tag (display optional) */
};

/* Panel ids. */
enum ctag_panel {
	CTAG_PANEL_NONE = 0, /* No panel (dev/test) */
	CTAG_PANEL_UC8176_420_BW = 1, /* 4.2in 400x300 UC8176 monochrome */
	CTAG_PANEL_UC8176_420_BWR = 2, /* 4.2in 400x300 UC8176 black/white/red */
	CTAG_PANEL_UNVERIFIED = 255, /* Panel not yet physically verified (Sifei/Hema) */
};

/* ---- Font pack (docs/fontpack.md) ---- */

#define CTAG_FONTPACK_MAGIC 0x50465443
#define CTAG_FONTPACK_VERSION 1
#define CTAG_FONTPACK_HEADER_SIZE 128
#define CTAG_FONTPACK_FACE_RECORD_SIZE 16
#define CTAG_FONTPACK_STRIKE_RECORD_SIZE 24
#define CTAG_FONTPACK_GLYPH_ENTRY_SIZE 12
#define CTAG_FONTPACK_EMPTY_BITMAP 0xFFFFFFFFu
#define CTAG_FONTPACK_SLOT_DIR_MAGIC 0x4C535443

#ifdef __cplusplus
}
#endif

#endif /* CTAG_PROTO_IDS_H_ */
